language: go
go:
- 1.11.x

dist: trusty

addons:
  sonarcloud:
    organization: "paysuper"

stages:
  - test
  - name: deploy 
    if: branch = develop 

jobs:
  include:
  - stage: test
    services:
      - mongodb
    env:
      - GO111MODULE=on
      - MONGO_HOST=127.0.0.1:27017
      - MONGO_DB=paysuper_repository_test
    install: true
    script:
    - echo "tests here"
    - go test ./... -coverprofile=coverage.out -covermode=atomic -p=1
    #- sonar-scanner
    after_success:
    - bash <(curl -s https://codecov.io/bash)
  - stage: deploy
    services: docker
    install: true
    script:
    - docker run -it
      -e JENKINS_AUTH_TOKEN=$JENKINS_AUTH_TOKEN
      -e JENKINS_BUILD_TOKEN=$JENKINS_BUILD_TOKEN
      -e JENKINS_BUILD_PROJECT=$TRAVIS_REPO_SLUG
      -e JENKINS_BUILD_BRANCH=$TRAVIS_BRANCH
      p1hub/p1jenkinstrigger 

notifications:
  email: false
  slack:
    secure: bWWsv0Shc4FBIwuSZU+ia/juCFYDe3z72JbodEJI/Yt+UHZNGkajpILCHNPHSxFht3l9uIDhKAm+yc82FpENtr0fTTW5IcqSnwkO+S8Gd0wuNB3VlmK1EfX0st044cu8PvnGYu5jOjsw1fj32yAEo+WOnTgIJX3/+yVPWZgRe+TprIL5hS+UMYPo90+zMr+fw1hZ6Bfr18nshSQUsKEZkv27xHq8NDB6l+1TLb+YZ1fENwn8OoUGIkrIdwdoo8mqNIM6LhcCNhW6kzHdJR7de1oEiYccEhyL9uf2qGysuv2XktKVEC1LMABD3Qofm4B9EbpU6x2z1GmJSjU9Cw73OjIjs35R4xCygU8OPhkPtYESkFqZy640ULkRQhW+dcY1TRXW8r/0DjC50RU/xz2/dqQ5E7bhAB9Ty1ZPAmONfxcs8+fdNDMMcYgIpt+FdfnDISCZw+PamV7QPI9BGm1yVsYcI1m9ifqhGUTZ+h7AZUe+6gSxWwDVB4mbce/6WBftyTBhYdyhhh3SA9C/MfoQ9pCNxc+yYMNbJrvHL8FNJIUN6Q4MfVdz1pvSh3STlAv9ybCYZc9xDj3mmhRf4JS+Vd0stAH2O0mVDDffQ3D+lbtt9m1Z7KHq5hqoafI+fut9dCJTRlAZIAZkAoqC2hibKKcdkGgu0ks7Pg11c4MjTkY=
