version: "3.6"

services:
  paysuper-recurring-repository:
    build: .
    container_name: paysuper-recurring-repository
    networks:
      - p1devnet
    external_links:
      - p1pay-api-mongo
    restart: unless-stopped
    ports:
      - "8085:8085"
    tty: true
    environment:
      MONGO_HOST: "localhost:3002"
      MONGO_DB: p1payapi
      MONGO_USER: ""
      MONGO_PASSWORD: ""

networks:
  p1devnet:
    external: true