version: "3.6"

services:
  paysuper-recurring-repository:
    build: .
    container_name: paysuper-recurring-repository
    networks:
      - p1devnet
    restart: unless-stopped
    ports:
      - "8085:8085"
    tty: true
    environment:
      MONGO_HOST: "payone-mongo:27017"
      MONGO_DB: p1payapi
      MONGO_USER: ""
      MONGO_PASSWORD: ""
      MICRO_REGISTRY: consul
      MICRO_REGISTRY_ADDRESS: consul

networks:
  p1devnet:
    external: true