// Code generated by protoc-gen-go. DO NOT EDIT.
// source: repository/repository.proto

package repository // import "github.com/paysuper/paysuper-recurring-repository/pkg/proto/repository"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import entity "github.com/paysuper/paysuper-recurring-repository/pkg/proto/entity"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Result struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_repository_dc7824f2ff208506, []int{0}
}
func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (dst *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(dst, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

type FindByStringValue struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-"`
}

func (m *FindByStringValue) Reset()         { *m = FindByStringValue{} }
func (m *FindByStringValue) String() string { return proto.CompactTextString(m) }
func (*FindByStringValue) ProtoMessage()    {}
func (*FindByStringValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_repository_dc7824f2ff208506, []int{1}
}
func (m *FindByStringValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindByStringValue.Unmarshal(m, b)
}
func (m *FindByStringValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindByStringValue.Marshal(b, m, deterministic)
}
func (dst *FindByStringValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindByStringValue.Merge(dst, src)
}
func (m *FindByStringValue) XXX_Size() int {
	return xxx_messageInfo_FindByStringValue.Size(m)
}
func (m *FindByStringValue) XXX_DiscardUnknown() {
	xxx_messageInfo_FindByStringValue.DiscardUnknown(m)
}

var xxx_messageInfo_FindByStringValue proto.InternalMessageInfo

func (m *FindByStringValue) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type SavedCardRequest struct {
	Account              string             `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	ProjectId            string             `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	MaskedPan            string             `protobuf:"bytes,3,opt,name=masked_pan,json=maskedPan,proto3" json:"masked_pan,omitempty"`
	RecurringId          string             `protobuf:"bytes,4,opt,name=recurring_id,json=recurringId,proto3" json:"recurring_id,omitempty"`
	Expire               *entity.CardExpire `protobuf:"bytes,5,opt,name=expire,proto3" json:"expire,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-" bson:"-" structure:"-"`
	XXX_unrecognized     []byte             `json:"-" bson:"-" structure:"-"`
	XXX_sizecache        int32              `json:"-" bson:"-" structure:"-"`
}

func (m *SavedCardRequest) Reset()         { *m = SavedCardRequest{} }
func (m *SavedCardRequest) String() string { return proto.CompactTextString(m) }
func (*SavedCardRequest) ProtoMessage()    {}
func (*SavedCardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_repository_dc7824f2ff208506, []int{2}
}
func (m *SavedCardRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SavedCardRequest.Unmarshal(m, b)
}
func (m *SavedCardRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SavedCardRequest.Marshal(b, m, deterministic)
}
func (dst *SavedCardRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SavedCardRequest.Merge(dst, src)
}
func (m *SavedCardRequest) XXX_Size() int {
	return xxx_messageInfo_SavedCardRequest.Size(m)
}
func (m *SavedCardRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SavedCardRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SavedCardRequest proto.InternalMessageInfo

func (m *SavedCardRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *SavedCardRequest) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *SavedCardRequest) GetMaskedPan() string {
	if m != nil {
		return m.MaskedPan
	}
	return ""
}

func (m *SavedCardRequest) GetRecurringId() string {
	if m != nil {
		return m.RecurringId
	}
	return ""
}

func (m *SavedCardRequest) GetExpire() *entity.CardExpire {
	if m != nil {
		return m.Expire
	}
	return nil
}

type SavedCardList struct {
	SavedCards           []*entity.SavedCard `protobuf:"bytes,1,rep,name=saved_cards,json=savedCards,proto3" json:"saved_cards,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-" bson:"-" structure:"-"`
	XXX_unrecognized     []byte              `json:"-" bson:"-" structure:"-"`
	XXX_sizecache        int32               `json:"-" bson:"-" structure:"-"`
}

func (m *SavedCardList) Reset()         { *m = SavedCardList{} }
func (m *SavedCardList) String() string { return proto.CompactTextString(m) }
func (*SavedCardList) ProtoMessage()    {}
func (*SavedCardList) Descriptor() ([]byte, []int) {
	return fileDescriptor_repository_dc7824f2ff208506, []int{3}
}
func (m *SavedCardList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SavedCardList.Unmarshal(m, b)
}
func (m *SavedCardList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SavedCardList.Marshal(b, m, deterministic)
}
func (dst *SavedCardList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SavedCardList.Merge(dst, src)
}
func (m *SavedCardList) XXX_Size() int {
	return xxx_messageInfo_SavedCardList.Size(m)
}
func (m *SavedCardList) XXX_DiscardUnknown() {
	xxx_messageInfo_SavedCardList.DiscardUnknown(m)
}

var xxx_messageInfo_SavedCardList proto.InternalMessageInfo

func (m *SavedCardList) GetSavedCards() []*entity.SavedCard {
	if m != nil {
		return m.SavedCards
	}
	return nil
}

func init() {
	proto.RegisterType((*Result)(nil), "repository.Result")
	proto.RegisterType((*FindByStringValue)(nil), "repository.FindByStringValue")
	proto.RegisterType((*SavedCardRequest)(nil), "repository.SavedCardRequest")
	proto.RegisterType((*SavedCardList)(nil), "repository.SavedCardList")
}

func init() {
	proto.RegisterFile("repository/repository.proto", fileDescriptor_repository_dc7824f2ff208506)
}

var fileDescriptor_repository_dc7824f2ff208506 = []byte{
	// 391 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xc1, 0xae, 0xd2, 0x40,
	0x14, 0xa5, 0xef, 0xf9, 0xd0, 0x77, 0xab, 0x3e, 0x19, 0x5d, 0x54, 0x94, 0x04, 0xbb, 0x42, 0x13,
	0xda, 0xa4, 0xfe, 0x01, 0x08, 0xda, 0xe8, 0xc2, 0x94, 0xc4, 0x85, 0x1b, 0x32, 0x74, 0x6e, 0x70,
	0x04, 0xda, 0x71, 0x66, 0x4a, 0xec, 0x67, 0xb9, 0xf4, 0xef, 0xcc, 0xb4, 0x65, 0xda, 0x88, 0x86,
	0x55, 0xef, 0x9c, 0x73, 0x7a, 0x73, 0xee, 0xb9, 0x17, 0x5e, 0x48, 0x14, 0xb9, 0xe2, 0x3a, 0x97,
	0x65, 0xd8, 0x96, 0x81, 0x90, 0xb9, 0xce, 0x09, 0xb4, 0xc8, 0xf0, 0x29, 0x66, 0x9a, 0xeb, 0x32,
	0xac, 0x3f, 0xb5, 0xc0, 0x7f, 0x00, 0xfd, 0x04, 0x55, 0xb1, 0xd7, 0xfe, 0x6b, 0x18, 0x2c, 0x79,
	0xc6, 0x66, 0xe5, 0x4a, 0x4b, 0x9e, 0x6d, 0xbf, 0xd0, 0x7d, 0x81, 0xe4, 0x19, 0xdc, 0x1c, 0x4d,
	0xe1, 0x39, 0x63, 0x67, 0x72, 0x9b, 0xd4, 0x0f, 0xff, 0xb7, 0x03, 0x4f, 0x56, 0xf4, 0x88, 0x6c,
	0x4e, 0x25, 0x4b, 0xf0, 0x47, 0x81, 0x4a, 0x13, 0x0f, 0xee, 0xd3, 0x34, 0xcd, 0x8b, 0x4c, 0x37,
	0xe2, 0xd3, 0x93, 0x8c, 0x00, 0x84, 0xcc, 0xbf, 0x63, 0xaa, 0xd7, 0x9c, 0x79, 0x57, 0x15, 0x79,
	0xdb, 0x20, 0x31, 0x33, 0xf4, 0x81, 0xaa, 0x1d, 0xb2, 0xb5, 0xa0, 0x99, 0x77, 0x5d, 0xd3, 0x35,
	0xf2, 0x99, 0x66, 0xe4, 0x15, 0x3c, 0x94, 0x98, 0x16, 0xd2, 0x98, 0x32, 0xff, 0xdf, 0xab, 0x04,
	0xae, 0xc5, 0x62, 0x46, 0xde, 0x40, 0x1f, 0x7f, 0x0a, 0x2e, 0xd1, 0xbb, 0x19, 0x3b, 0x13, 0x37,
	0x22, 0x41, 0x33, 0xa3, 0xf1, 0xb7, 0xa8, 0x98, 0xa4, 0x51, 0xf8, 0x73, 0x78, 0x64, 0xad, 0x7f,
	0xe2, 0x4a, 0x93, 0x08, 0x5c, 0x65, 0x80, 0x75, 0x4a, 0x25, 0x53, 0x9e, 0x33, 0xbe, 0x9e, 0xb8,
	0xd1, 0xe0, 0xd4, 0xa1, 0x1d, 0x13, 0xd4, 0xa9, 0x54, 0xd1, 0xaf, 0x2b, 0x80, 0xc4, 0x26, 0x4b,
	0x16, 0x70, 0x17, 0x67, 0x0a, 0xa5, 0xb6, 0x6a, 0xf2, 0x32, 0xe8, 0xec, 0xe2, 0xef, 0xac, 0x86,
	0xa4, 0xcb, 0x36, 0xf9, 0xf7, 0xc8, 0x12, 0xee, 0xde, 0xe1, 0x1e, 0x35, 0xb6, 0x6d, 0x46, 0x5d,
	0xe1, 0xd9, 0x7a, 0xfe, 0xd3, 0xe7, 0x23, 0x3c, 0x36, 0x52, 0xdb, 0x45, 0x5d, 0x70, 0xf3, 0xfc,
	0x9f, 0xac, 0x09, 0xc7, 0xef, 0x91, 0xf7, 0xf5, 0x59, 0x58, 0x78, 0x56, 0xc6, 0x17, 0x6d, 0x9d,
	0xa7, 0xe7, 0xf7, 0x66, 0x1f, 0xbe, 0x2e, 0xb7, 0x5c, 0x7f, 0x2b, 0x36, 0x41, 0x9a, 0x1f, 0x42,
	0x41, 0x4b, 0x55, 0x08, 0x94, 0xb6, 0x98, 0xda, 0x85, 0x4e, 0x3b, 0x07, 0x2d, 0x76, 0xdb, 0xb0,
	0x3a, 0xd4, 0xce, 0x69, 0x6f, 0xfa, 0x15, 0xf2, 0xf6, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe7,
	0x91, 0xe0, 0x2e, 0xfa, 0x02, 0x00, 0x00,
}
