// Code generated by protoc-gen-go. DO NOT EDIT.
// source: repository/repository.proto

package repository // import "github.com/paysuper/paysuper-recurring-repository/pkg/proto/repository"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import entity "github.com/paysuper/paysuper-recurring-repository/pkg/proto/entity"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Result struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_repository_2f52a3ac17d90a6e, []int{0}
}
func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (dst *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(dst, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

type FindByStringValue struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-"`
}

func (m *FindByStringValue) Reset()         { *m = FindByStringValue{} }
func (m *FindByStringValue) String() string { return proto.CompactTextString(m) }
func (*FindByStringValue) ProtoMessage()    {}
func (*FindByStringValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_repository_2f52a3ac17d90a6e, []int{1}
}
func (m *FindByStringValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindByStringValue.Unmarshal(m, b)
}
func (m *FindByStringValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindByStringValue.Marshal(b, m, deterministic)
}
func (dst *FindByStringValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindByStringValue.Merge(dst, src)
}
func (m *FindByStringValue) XXX_Size() int {
	return xxx_messageInfo_FindByStringValue.Size(m)
}
func (m *FindByStringValue) XXX_DiscardUnknown() {
	xxx_messageInfo_FindByStringValue.DiscardUnknown(m)
}

var xxx_messageInfo_FindByStringValue proto.InternalMessageInfo

func (m *FindByStringValue) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type SavedCardRequest struct {
	Token                string             `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ProjectId            string             `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	MerchantId           string             `protobuf:"bytes,3,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	MaskedPan            string             `protobuf:"bytes,4,opt,name=masked_pan,json=maskedPan,proto3" json:"masked_pan,omitempty"`
	CardHolder           string             `protobuf:"bytes,5,opt,name=card_holder,json=cardHolder,proto3" json:"card_holder,omitempty"`
	RecurringId          string             `protobuf:"bytes,6,opt,name=recurring_id,json=recurringId,proto3" json:"recurring_id,omitempty"`
	Expire               *entity.CardExpire `protobuf:"bytes,7,opt,name=expire,proto3" json:"expire,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-" bson:"-" structure:"-"`
	XXX_unrecognized     []byte             `json:"-" bson:"-" structure:"-"`
	XXX_sizecache        int32              `json:"-" bson:"-" structure:"-"`
}

func (m *SavedCardRequest) Reset()         { *m = SavedCardRequest{} }
func (m *SavedCardRequest) String() string { return proto.CompactTextString(m) }
func (*SavedCardRequest) ProtoMessage()    {}
func (*SavedCardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_repository_2f52a3ac17d90a6e, []int{2}
}
func (m *SavedCardRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SavedCardRequest.Unmarshal(m, b)
}
func (m *SavedCardRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SavedCardRequest.Marshal(b, m, deterministic)
}
func (dst *SavedCardRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SavedCardRequest.Merge(dst, src)
}
func (m *SavedCardRequest) XXX_Size() int {
	return xxx_messageInfo_SavedCardRequest.Size(m)
}
func (m *SavedCardRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SavedCardRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SavedCardRequest proto.InternalMessageInfo

func (m *SavedCardRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *SavedCardRequest) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *SavedCardRequest) GetMerchantId() string {
	if m != nil {
		return m.MerchantId
	}
	return ""
}

func (m *SavedCardRequest) GetMaskedPan() string {
	if m != nil {
		return m.MaskedPan
	}
	return ""
}

func (m *SavedCardRequest) GetCardHolder() string {
	if m != nil {
		return m.CardHolder
	}
	return ""
}

func (m *SavedCardRequest) GetRecurringId() string {
	if m != nil {
		return m.RecurringId
	}
	return ""
}

func (m *SavedCardRequest) GetExpire() *entity.CardExpire {
	if m != nil {
		return m.Expire
	}
	return nil
}

type SavedCardList struct {
	SavedCards           []*entity.SavedCard `protobuf:"bytes,1,rep,name=saved_cards,json=savedCards,proto3" json:"saved_cards,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-" bson:"-" structure:"-"`
	XXX_unrecognized     []byte              `json:"-" bson:"-" structure:"-"`
	XXX_sizecache        int32               `json:"-" bson:"-" structure:"-"`
}

func (m *SavedCardList) Reset()         { *m = SavedCardList{} }
func (m *SavedCardList) String() string { return proto.CompactTextString(m) }
func (*SavedCardList) ProtoMessage()    {}
func (*SavedCardList) Descriptor() ([]byte, []int) {
	return fileDescriptor_repository_2f52a3ac17d90a6e, []int{3}
}
func (m *SavedCardList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SavedCardList.Unmarshal(m, b)
}
func (m *SavedCardList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SavedCardList.Marshal(b, m, deterministic)
}
func (dst *SavedCardList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SavedCardList.Merge(dst, src)
}
func (m *SavedCardList) XXX_Size() int {
	return xxx_messageInfo_SavedCardList.Size(m)
}
func (m *SavedCardList) XXX_DiscardUnknown() {
	xxx_messageInfo_SavedCardList.DiscardUnknown(m)
}

var xxx_messageInfo_SavedCardList proto.InternalMessageInfo

func (m *SavedCardList) GetSavedCards() []*entity.SavedCard {
	if m != nil {
		return m.SavedCards
	}
	return nil
}

func init() {
	proto.RegisterType((*Result)(nil), "repository.Result")
	proto.RegisterType((*FindByStringValue)(nil), "repository.FindByStringValue")
	proto.RegisterType((*SavedCardRequest)(nil), "repository.SavedCardRequest")
	proto.RegisterType((*SavedCardList)(nil), "repository.SavedCardList")
}

func init() {
	proto.RegisterFile("repository/repository.proto", fileDescriptor_repository_2f52a3ac17d90a6e)
}

var fileDescriptor_repository_2f52a3ac17d90a6e = []byte{
	// 423 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0x41, 0x6f, 0xd3, 0x30,
	0x14, 0x6e, 0x36, 0x56, 0xd8, 0x0b, 0x30, 0x66, 0x38, 0x84, 0xc1, 0x44, 0xc9, 0xa9, 0x20, 0xad,
	0x95, 0xca, 0x3f, 0xe8, 0x58, 0x59, 0x04, 0x07, 0x94, 0x49, 0x1c, 0xb8, 0x54, 0x5e, 0xfc, 0xd4,
	0x9a, 0xb6, 0xb6, 0xb1, 0x9d, 0x89, 0xfc, 0x2c, 0x7e, 0x1d, 0x57, 0x64, 0x27, 0x71, 0x22, 0xc6,
	0xb4, 0x93, 0x9f, 0xbf, 0xef, 0x7b, 0xcf, 0x7e, 0xef, 0xb3, 0xe1, 0x95, 0x46, 0x25, 0x0d, 0xb7,
	0x52, 0x57, 0xd3, 0x2e, 0x9c, 0x28, 0x2d, 0xad, 0x24, 0xd0, 0x21, 0x27, 0xcf, 0x51, 0x58, 0x6e,
	0xab, 0x69, 0xbd, 0xd4, 0x82, 0xf4, 0x11, 0x0c, 0x73, 0x34, 0xe5, 0xd6, 0xa6, 0xef, 0xe0, 0x78,
	0xc1, 0x05, 0x9b, 0x57, 0x57, 0x56, 0x73, 0xb1, 0xfa, 0x46, 0xb7, 0x25, 0x92, 0x17, 0x70, 0x70,
	0xe3, 0x82, 0x24, 0x1a, 0x45, 0xe3, 0xc3, 0xbc, 0xde, 0xa4, 0x7f, 0x22, 0x78, 0x76, 0x45, 0x6f,
	0x90, 0x9d, 0x53, 0xcd, 0x72, 0xfc, 0x59, 0xa2, 0xb1, 0x4e, 0x6a, 0xe5, 0x06, 0x45, 0x2b, 0xf5,
	0x1b, 0x72, 0x0a, 0xa0, 0xb4, 0xfc, 0x81, 0x85, 0x5d, 0x72, 0x96, 0xec, 0x79, 0xea, 0xb0, 0x41,
	0x32, 0x46, 0xde, 0x40, 0xbc, 0x43, 0x5d, 0xac, 0xa9, 0xf0, 0xfc, 0xbe, 0xe7, 0xa1, 0x85, 0x32,
	0xe6, 0xf2, 0x77, 0xd4, 0x6c, 0x90, 0x2d, 0x15, 0x15, 0xc9, 0x83, 0x3a, 0xbf, 0x46, 0xbe, 0x52,
	0xe1, 0xf2, 0x0b, 0xaa, 0xd9, 0x72, 0x2d, 0xb7, 0x0c, 0x75, 0x72, 0x50, 0xe7, 0x3b, 0xe8, 0xd2,
	0x23, 0xe4, 0x2d, 0x3c, 0xd6, 0x58, 0x94, 0xda, 0xb5, 0xe4, 0x4e, 0x18, 0x7a, 0x45, 0x1c, 0xb0,
	0x8c, 0x91, 0xf7, 0x30, 0xc4, 0x5f, 0x8a, 0x6b, 0x4c, 0x1e, 0x8e, 0xa2, 0x71, 0x3c, 0x23, 0x93,
	0x66, 0x42, 0xae, 0xbb, 0x0b, 0xcf, 0xe4, 0x8d, 0x22, 0x3d, 0x87, 0x27, 0xa1, 0xf1, 0x2f, 0xdc,
	0x58, 0x32, 0x83, 0xd8, 0x38, 0x60, 0xe9, 0xce, 0x34, 0x49, 0x34, 0xda, 0x1f, 0xc7, 0xb3, 0xe3,
	0xb6, 0x42, 0x37, 0x24, 0x30, 0x6d, 0x68, 0x66, 0xbf, 0xf7, 0x00, 0xf2, 0xe0, 0x0b, 0xb9, 0x80,
	0xa3, 0x4c, 0x18, 0xd4, 0x36, 0xa8, 0xc9, 0xeb, 0x49, 0xcf, 0xc9, 0x7f, 0x27, 0x7d, 0x42, 0xfa,
	0x6c, 0xe3, 0xde, 0x80, 0x2c, 0xe0, 0xe8, 0x23, 0x6e, 0xd1, 0x62, 0x57, 0xe6, 0xb4, 0x2f, 0xbc,
	0x65, 0xee, 0x1d, 0x75, 0x3e, 0xc3, 0x53, 0x27, 0x0d, 0x55, 0xcc, 0x3d, 0xb7, 0x79, 0xf9, 0x5f,
	0xd6, 0x0d, 0x27, 0x1d, 0x90, 0x4f, 0xf5, 0xa3, 0x0a, 0xf0, 0xbc, 0xca, 0xee, 0xbd, 0xd6, 0xed,
	0xe9, 0xa5, 0x83, 0xf9, 0xe5, 0xf7, 0xc5, 0x8a, 0xdb, 0x75, 0x79, 0x3d, 0x29, 0xe4, 0x6e, 0xaa,
	0x68, 0x65, 0x4a, 0x85, 0x3a, 0x04, 0x67, 0xc1, 0xd0, 0xb3, 0xde, 0x77, 0x50, 0x9b, 0xd5, 0xd4,
	0x3f, 0xf3, 0xde, 0xc7, 0xb8, 0x1e, 0x7a, 0xe4, 0xc3, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc3,
	0xae, 0x51, 0x1e, 0x38, 0x03, 0x00, 0x00,
}
