// Code generated by protoc-gen-go. DO NOT EDIT.
// source: repository/repository.proto

package repository // import "github.com/ProtocolONE/payone-repository/pkg/proto/repository"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import billing "github.com/ProtocolONE/payone-repository/pkg/proto/billing"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Result struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_repository_4f7234a8268002f6, []int{0}
}
func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (dst *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(dst, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

type ConvertRequest struct {
	CurrencyFrom         int32    `protobuf:"varint,1,opt,name=currency_from,json=currencyFrom,proto3" json:"currency_from,omitempty"`
	CurrencyTo           int32    `protobuf:"varint,2,opt,name=currency_to,json=currencyTo,proto3" json:"currency_to,omitempty"`
	Amount               float64  `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-"`
}

func (m *ConvertRequest) Reset()         { *m = ConvertRequest{} }
func (m *ConvertRequest) String() string { return proto.CompactTextString(m) }
func (*ConvertRequest) ProtoMessage()    {}
func (*ConvertRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_repository_4f7234a8268002f6, []int{1}
}
func (m *ConvertRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConvertRequest.Unmarshal(m, b)
}
func (m *ConvertRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConvertRequest.Marshal(b, m, deterministic)
}
func (dst *ConvertRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConvertRequest.Merge(dst, src)
}
func (m *ConvertRequest) XXX_Size() int {
	return xxx_messageInfo_ConvertRequest.Size(m)
}
func (m *ConvertRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConvertRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConvertRequest proto.InternalMessageInfo

func (m *ConvertRequest) GetCurrencyFrom() int32 {
	if m != nil {
		return m.CurrencyFrom
	}
	return 0
}

func (m *ConvertRequest) GetCurrencyTo() int32 {
	if m != nil {
		return m.CurrencyTo
	}
	return 0
}

func (m *ConvertRequest) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type ConvertResponse struct {
	Amount               float64  `protobuf:"fixed64,1,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-"`
}

func (m *ConvertResponse) Reset()         { *m = ConvertResponse{} }
func (m *ConvertResponse) String() string { return proto.CompactTextString(m) }
func (*ConvertResponse) ProtoMessage()    {}
func (*ConvertResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_repository_4f7234a8268002f6, []int{2}
}
func (m *ConvertResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConvertResponse.Unmarshal(m, b)
}
func (m *ConvertResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConvertResponse.Marshal(b, m, deterministic)
}
func (dst *ConvertResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConvertResponse.Merge(dst, src)
}
func (m *ConvertResponse) XXX_Size() int {
	return xxx_messageInfo_ConvertResponse.Size(m)
}
func (m *ConvertResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConvertResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConvertResponse proto.InternalMessageInfo

func (m *ConvertResponse) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type FindByUnderscoreId struct {
	// @inject_tag: bson:"_id" structure:"_id,bsonobjectid"
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"_id" structure:"_id,bsonobjectid"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-"`
}

func (m *FindByUnderscoreId) Reset()         { *m = FindByUnderscoreId{} }
func (m *FindByUnderscoreId) String() string { return proto.CompactTextString(m) }
func (*FindByUnderscoreId) ProtoMessage()    {}
func (*FindByUnderscoreId) Descriptor() ([]byte, []int) {
	return fileDescriptor_repository_4f7234a8268002f6, []int{3}
}
func (m *FindByUnderscoreId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindByUnderscoreId.Unmarshal(m, b)
}
func (m *FindByUnderscoreId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindByUnderscoreId.Marshal(b, m, deterministic)
}
func (dst *FindByUnderscoreId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindByUnderscoreId.Merge(dst, src)
}
func (m *FindByUnderscoreId) XXX_Size() int {
	return xxx_messageInfo_FindByUnderscoreId.Size(m)
}
func (m *FindByUnderscoreId) XXX_DiscardUnknown() {
	xxx_messageInfo_FindByUnderscoreId.DiscardUnknown(m)
}

var xxx_messageInfo_FindByUnderscoreId proto.InternalMessageInfo

func (m *FindByUnderscoreId) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type FindByStringValue struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-"`
}

func (m *FindByStringValue) Reset()         { *m = FindByStringValue{} }
func (m *FindByStringValue) String() string { return proto.CompactTextString(m) }
func (*FindByStringValue) ProtoMessage()    {}
func (*FindByStringValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_repository_4f7234a8268002f6, []int{4}
}
func (m *FindByStringValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindByStringValue.Unmarshal(m, b)
}
func (m *FindByStringValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindByStringValue.Marshal(b, m, deterministic)
}
func (dst *FindByStringValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindByStringValue.Merge(dst, src)
}
func (m *FindByStringValue) XXX_Size() int {
	return xxx_messageInfo_FindByStringValue.Size(m)
}
func (m *FindByStringValue) XXX_DiscardUnknown() {
	xxx_messageInfo_FindByStringValue.DiscardUnknown(m)
}

var xxx_messageInfo_FindByStringValue proto.InternalMessageInfo

func (m *FindByStringValue) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type FloatValue struct {
	Value                float64  `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-"`
}

func (m *FloatValue) Reset()         { *m = FloatValue{} }
func (m *FloatValue) String() string { return proto.CompactTextString(m) }
func (*FloatValue) ProtoMessage()    {}
func (*FloatValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_repository_4f7234a8268002f6, []int{5}
}
func (m *FloatValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FloatValue.Unmarshal(m, b)
}
func (m *FloatValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FloatValue.Marshal(b, m, deterministic)
}
func (dst *FloatValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FloatValue.Merge(dst, src)
}
func (m *FloatValue) XXX_Size() int {
	return xxx_messageInfo_FloatValue.Size(m)
}
func (m *FloatValue) XXX_DiscardUnknown() {
	xxx_messageInfo_FloatValue.DiscardUnknown(m)
}

var xxx_messageInfo_FloatValue proto.InternalMessageInfo

func (m *FloatValue) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type FindByIntValue struct {
	Value                int32    `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-"`
}

func (m *FindByIntValue) Reset()         { *m = FindByIntValue{} }
func (m *FindByIntValue) String() string { return proto.CompactTextString(m) }
func (*FindByIntValue) ProtoMessage()    {}
func (*FindByIntValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_repository_4f7234a8268002f6, []int{6}
}
func (m *FindByIntValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindByIntValue.Unmarshal(m, b)
}
func (m *FindByIntValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindByIntValue.Marshal(b, m, deterministic)
}
func (dst *FindByIntValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindByIntValue.Merge(dst, src)
}
func (m *FindByIntValue) XXX_Size() int {
	return xxx_messageInfo_FindByIntValue.Size(m)
}
func (m *FindByIntValue) XXX_DiscardUnknown() {
	xxx_messageInfo_FindByIntValue.DiscardUnknown(m)
}

var xxx_messageInfo_FindByIntValue proto.InternalMessageInfo

func (m *FindByIntValue) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type FindByGroupCurrencyRequest struct {
	// @inject_tag: bson:"group_alias" structure:"group_alias"
	Group string `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty" bson:"group_alias" structure:"group_alias"`
	// @inject_tag: bson:"currencies" structure:"currencies"
	Currency             int32    `protobuf:"varint,2,opt,name=currency,proto3" json:"currency,omitempty" bson:"currencies" structure:"currencies"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-"`
}

func (m *FindByGroupCurrencyRequest) Reset()         { *m = FindByGroupCurrencyRequest{} }
func (m *FindByGroupCurrencyRequest) String() string { return proto.CompactTextString(m) }
func (*FindByGroupCurrencyRequest) ProtoMessage()    {}
func (*FindByGroupCurrencyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_repository_4f7234a8268002f6, []int{7}
}
func (m *FindByGroupCurrencyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindByGroupCurrencyRequest.Unmarshal(m, b)
}
func (m *FindByGroupCurrencyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindByGroupCurrencyRequest.Marshal(b, m, deterministic)
}
func (dst *FindByGroupCurrencyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindByGroupCurrencyRequest.Merge(dst, src)
}
func (m *FindByGroupCurrencyRequest) XXX_Size() int {
	return xxx_messageInfo_FindByGroupCurrencyRequest.Size(m)
}
func (m *FindByGroupCurrencyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindByGroupCurrencyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindByGroupCurrencyRequest proto.InternalMessageInfo

func (m *FindByGroupCurrencyRequest) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *FindByGroupCurrencyRequest) GetCurrency() int32 {
	if m != nil {
		return m.Currency
	}
	return 0
}

type FindByProjectOrderId struct {
	// @inject_tag: structure:"project.id,bsonobjectid"
	ProjectId string `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty" structure:"project.id,bsonobjectid"`
	// @inject_tag: structure:"project_order_id"
	OrderId              string   `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty" structure:"project_order_id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-"`
}

func (m *FindByProjectOrderId) Reset()         { *m = FindByProjectOrderId{} }
func (m *FindByProjectOrderId) String() string { return proto.CompactTextString(m) }
func (*FindByProjectOrderId) ProtoMessage()    {}
func (*FindByProjectOrderId) Descriptor() ([]byte, []int) {
	return fileDescriptor_repository_4f7234a8268002f6, []int{8}
}
func (m *FindByProjectOrderId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindByProjectOrderId.Unmarshal(m, b)
}
func (m *FindByProjectOrderId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindByProjectOrderId.Marshal(b, m, deterministic)
}
func (dst *FindByProjectOrderId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindByProjectOrderId.Merge(dst, src)
}
func (m *FindByProjectOrderId) XXX_Size() int {
	return xxx_messageInfo_FindByProjectOrderId.Size(m)
}
func (m *FindByProjectOrderId) XXX_DiscardUnknown() {
	xxx_messageInfo_FindByProjectOrderId.DiscardUnknown(m)
}

var xxx_messageInfo_FindByProjectOrderId proto.InternalMessageInfo

func (m *FindByProjectOrderId) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *FindByProjectOrderId) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

type Projects struct {
	Projects             []*billing.Project `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-" bson:"-" structure:"-"`
	XXX_unrecognized     []byte             `json:"-" bson:"-" structure:"-"`
	XXX_sizecache        int32              `json:"-" bson:"-" structure:"-"`
}

func (m *Projects) Reset()         { *m = Projects{} }
func (m *Projects) String() string { return proto.CompactTextString(m) }
func (*Projects) ProtoMessage()    {}
func (*Projects) Descriptor() ([]byte, []int) {
	return fileDescriptor_repository_4f7234a8268002f6, []int{9}
}
func (m *Projects) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Projects.Unmarshal(m, b)
}
func (m *Projects) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Projects.Marshal(b, m, deterministic)
}
func (dst *Projects) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Projects.Merge(dst, src)
}
func (m *Projects) XXX_Size() int {
	return xxx_messageInfo_Projects.Size(m)
}
func (m *Projects) XXX_DiscardUnknown() {
	xxx_messageInfo_Projects.DiscardUnknown(m)
}

var xxx_messageInfo_Projects proto.InternalMessageInfo

func (m *Projects) GetProjects() []*billing.Project {
	if m != nil {
		return m.Projects
	}
	return nil
}

type PaymentMethods struct {
	PaymentMethods       []*billing.PaymentMethod `protobuf:"bytes,1,rep,name=payment_methods,json=paymentMethods,proto3" json:"payment_methods,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-" bson:"-" structure:"-"`
	XXX_unrecognized     []byte                   `json:"-" bson:"-" structure:"-"`
	XXX_sizecache        int32                    `json:"-" bson:"-" structure:"-"`
}

func (m *PaymentMethods) Reset()         { *m = PaymentMethods{} }
func (m *PaymentMethods) String() string { return proto.CompactTextString(m) }
func (*PaymentMethods) ProtoMessage()    {}
func (*PaymentMethods) Descriptor() ([]byte, []int) {
	return fileDescriptor_repository_4f7234a8268002f6, []int{10}
}
func (m *PaymentMethods) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentMethods.Unmarshal(m, b)
}
func (m *PaymentMethods) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentMethods.Marshal(b, m, deterministic)
}
func (dst *PaymentMethods) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentMethods.Merge(dst, src)
}
func (m *PaymentMethods) XXX_Size() int {
	return xxx_messageInfo_PaymentMethods.Size(m)
}
func (m *PaymentMethods) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentMethods.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentMethods proto.InternalMessageInfo

func (m *PaymentMethods) GetPaymentMethods() []*billing.PaymentMethod {
	if m != nil {
		return m.PaymentMethods
	}
	return nil
}

type CommissionRequest struct {
	// @inject_tag: structure:"project_id,bsonobjectid"
	ProjectId string `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty" structure:"project_id,bsonobjectid"`
	// @inject_tag: structure:"pm_id,bsonobjectid"
	PaymentMethodId      string   `protobuf:"bytes,2,opt,name=payment_method_id,json=paymentMethodId,proto3" json:"payment_method_id,omitempty" structure:"pm_id,bsonobjectid"`
	Amount               float64  `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-"`
}

func (m *CommissionRequest) Reset()         { *m = CommissionRequest{} }
func (m *CommissionRequest) String() string { return proto.CompactTextString(m) }
func (*CommissionRequest) ProtoMessage()    {}
func (*CommissionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_repository_4f7234a8268002f6, []int{11}
}
func (m *CommissionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommissionRequest.Unmarshal(m, b)
}
func (m *CommissionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommissionRequest.Marshal(b, m, deterministic)
}
func (dst *CommissionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommissionRequest.Merge(dst, src)
}
func (m *CommissionRequest) XXX_Size() int {
	return xxx_messageInfo_CommissionRequest.Size(m)
}
func (m *CommissionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CommissionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CommissionRequest proto.InternalMessageInfo

func (m *CommissionRequest) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *CommissionRequest) GetPaymentMethodId() string {
	if m != nil {
		return m.PaymentMethodId
	}
	return ""
}

func (m *CommissionRequest) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type CommissionResponse struct {
	PaymentMethod        float64  `protobuf:"fixed64,1,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	Psp                  float64  `protobuf:"fixed64,2,opt,name=psp,proto3" json:"psp,omitempty"`
	ToUser               float64  `protobuf:"fixed64,3,opt,name=to_user,json=toUser,proto3" json:"to_user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-"`
}

func (m *CommissionResponse) Reset()         { *m = CommissionResponse{} }
func (m *CommissionResponse) String() string { return proto.CompactTextString(m) }
func (*CommissionResponse) ProtoMessage()    {}
func (*CommissionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_repository_4f7234a8268002f6, []int{12}
}
func (m *CommissionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommissionResponse.Unmarshal(m, b)
}
func (m *CommissionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommissionResponse.Marshal(b, m, deterministic)
}
func (dst *CommissionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommissionResponse.Merge(dst, src)
}
func (m *CommissionResponse) XXX_Size() int {
	return xxx_messageInfo_CommissionResponse.Size(m)
}
func (m *CommissionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CommissionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CommissionResponse proto.InternalMessageInfo

func (m *CommissionResponse) GetPaymentMethod() float64 {
	if m != nil {
		return m.PaymentMethod
	}
	return 0
}

func (m *CommissionResponse) GetPsp() float64 {
	if m != nil {
		return m.Psp
	}
	return 0
}

func (m *CommissionResponse) GetToUser() float64 {
	if m != nil {
		return m.ToUser
	}
	return 0
}

type CalculateVatRequest struct {
	CountryCodeA2        string   `protobuf:"bytes,1,opt,name=country_code_a2,json=countryCodeA2,proto3" json:"country_code_a2,omitempty"`
	Subdivision          string   `protobuf:"bytes,2,opt,name=subdivision,proto3" json:"subdivision,omitempty"`
	Amount               float64  `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-"`
}

func (m *CalculateVatRequest) Reset()         { *m = CalculateVatRequest{} }
func (m *CalculateVatRequest) String() string { return proto.CompactTextString(m) }
func (*CalculateVatRequest) ProtoMessage()    {}
func (*CalculateVatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_repository_4f7234a8268002f6, []int{13}
}
func (m *CalculateVatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalculateVatRequest.Unmarshal(m, b)
}
func (m *CalculateVatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalculateVatRequest.Marshal(b, m, deterministic)
}
func (dst *CalculateVatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalculateVatRequest.Merge(dst, src)
}
func (m *CalculateVatRequest) XXX_Size() int {
	return xxx_messageInfo_CalculateVatRequest.Size(m)
}
func (m *CalculateVatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CalculateVatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CalculateVatRequest proto.InternalMessageInfo

func (m *CalculateVatRequest) GetCountryCodeA2() string {
	if m != nil {
		return m.CountryCodeA2
	}
	return ""
}

func (m *CalculateVatRequest) GetSubdivision() string {
	if m != nil {
		return m.Subdivision
	}
	return ""
}

func (m *CalculateVatRequest) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type SavedCardRequest struct {
	Account              string              `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	ProjectId            string              `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Pan                  string              `protobuf:"bytes,3,opt,name=pan,proto3" json:"pan,omitempty"`
	Expire               *billing.CardExpire `protobuf:"bytes,4,opt,name=expire,proto3" json:"expire,omitempty"`
	CardHolder           string              `protobuf:"bytes,5,opt,name=card_holder,json=cardHolder,proto3" json:"card_holder,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-" bson:"-" structure:"-"`
	XXX_unrecognized     []byte              `json:"-" bson:"-" structure:"-"`
	XXX_sizecache        int32               `json:"-" bson:"-" structure:"-"`
}

func (m *SavedCardRequest) Reset()         { *m = SavedCardRequest{} }
func (m *SavedCardRequest) String() string { return proto.CompactTextString(m) }
func (*SavedCardRequest) ProtoMessage()    {}
func (*SavedCardRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_repository_4f7234a8268002f6, []int{14}
}
func (m *SavedCardRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SavedCardRequest.Unmarshal(m, b)
}
func (m *SavedCardRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SavedCardRequest.Marshal(b, m, deterministic)
}
func (dst *SavedCardRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SavedCardRequest.Merge(dst, src)
}
func (m *SavedCardRequest) XXX_Size() int {
	return xxx_messageInfo_SavedCardRequest.Size(m)
}
func (m *SavedCardRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SavedCardRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SavedCardRequest proto.InternalMessageInfo

func (m *SavedCardRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *SavedCardRequest) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *SavedCardRequest) GetPan() string {
	if m != nil {
		return m.Pan
	}
	return ""
}

func (m *SavedCardRequest) GetExpire() *billing.CardExpire {
	if m != nil {
		return m.Expire
	}
	return nil
}

func (m *SavedCardRequest) GetCardHolder() string {
	if m != nil {
		return m.CardHolder
	}
	return ""
}

type SavedCardList struct {
	SavedCards           []*billing.SavedCard `protobuf:"bytes,1,rep,name=saved_cards,json=savedCards,proto3" json:"saved_cards,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-" bson:"-" structure:"-"`
	XXX_unrecognized     []byte               `json:"-" bson:"-" structure:"-"`
	XXX_sizecache        int32                `json:"-" bson:"-" structure:"-"`
}

func (m *SavedCardList) Reset()         { *m = SavedCardList{} }
func (m *SavedCardList) String() string { return proto.CompactTextString(m) }
func (*SavedCardList) ProtoMessage()    {}
func (*SavedCardList) Descriptor() ([]byte, []int) {
	return fileDescriptor_repository_4f7234a8268002f6, []int{15}
}
func (m *SavedCardList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SavedCardList.Unmarshal(m, b)
}
func (m *SavedCardList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SavedCardList.Marshal(b, m, deterministic)
}
func (dst *SavedCardList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SavedCardList.Merge(dst, src)
}
func (m *SavedCardList) XXX_Size() int {
	return xxx_messageInfo_SavedCardList.Size(m)
}
func (m *SavedCardList) XXX_DiscardUnknown() {
	xxx_messageInfo_SavedCardList.DiscardUnknown(m)
}

var xxx_messageInfo_SavedCardList proto.InternalMessageInfo

func (m *SavedCardList) GetSavedCards() []*billing.SavedCard {
	if m != nil {
		return m.SavedCards
	}
	return nil
}

func init() {
	proto.RegisterType((*Result)(nil), "repository.Result")
	proto.RegisterType((*ConvertRequest)(nil), "repository.ConvertRequest")
	proto.RegisterType((*ConvertResponse)(nil), "repository.ConvertResponse")
	proto.RegisterType((*FindByUnderscoreId)(nil), "repository.FindByUnderscoreId")
	proto.RegisterType((*FindByStringValue)(nil), "repository.FindByStringValue")
	proto.RegisterType((*FloatValue)(nil), "repository.FloatValue")
	proto.RegisterType((*FindByIntValue)(nil), "repository.FindByIntValue")
	proto.RegisterType((*FindByGroupCurrencyRequest)(nil), "repository.FindByGroupCurrencyRequest")
	proto.RegisterType((*FindByProjectOrderId)(nil), "repository.FindByProjectOrderId")
	proto.RegisterType((*Projects)(nil), "repository.Projects")
	proto.RegisterType((*PaymentMethods)(nil), "repository.PaymentMethods")
	proto.RegisterType((*CommissionRequest)(nil), "repository.CommissionRequest")
	proto.RegisterType((*CommissionResponse)(nil), "repository.CommissionResponse")
	proto.RegisterType((*CalculateVatRequest)(nil), "repository.CalculateVatRequest")
	proto.RegisterType((*SavedCardRequest)(nil), "repository.SavedCardRequest")
	proto.RegisterType((*SavedCardList)(nil), "repository.SavedCardList")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RepositoryClient is the client API for Repository service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RepositoryClient interface {
	InsertSavedCard(ctx context.Context, in *SavedCardRequest, opts ...grpc.CallOption) (*Result, error)
	DeleteSavedCard(ctx context.Context, in *FindByStringValue, opts ...grpc.CallOption) (*Result, error)
	FindSavedCards(ctx context.Context, in *SavedCardRequest, opts ...grpc.CallOption) (*SavedCardList, error)
	FindSavedCard(ctx context.Context, in *SavedCardRequest, opts ...grpc.CallOption) (*billing.SavedCard, error)
	FindSavedCardById(ctx context.Context, in *FindByStringValue, opts ...grpc.CallOption) (*billing.SavedCard, error)
}

type repositoryClient struct {
	cc *grpc.ClientConn
}

func NewRepositoryClient(cc *grpc.ClientConn) RepositoryClient {
	return &repositoryClient{cc}
}

func (c *repositoryClient) InsertSavedCard(ctx context.Context, in *SavedCardRequest, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/repository.Repository/InsertSavedCard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repositoryClient) DeleteSavedCard(ctx context.Context, in *FindByStringValue, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/repository.Repository/DeleteSavedCard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repositoryClient) FindSavedCards(ctx context.Context, in *SavedCardRequest, opts ...grpc.CallOption) (*SavedCardList, error) {
	out := new(SavedCardList)
	err := c.cc.Invoke(ctx, "/repository.Repository/FindSavedCards", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repositoryClient) FindSavedCard(ctx context.Context, in *SavedCardRequest, opts ...grpc.CallOption) (*billing.SavedCard, error) {
	out := new(billing.SavedCard)
	err := c.cc.Invoke(ctx, "/repository.Repository/FindSavedCard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repositoryClient) FindSavedCardById(ctx context.Context, in *FindByStringValue, opts ...grpc.CallOption) (*billing.SavedCard, error) {
	out := new(billing.SavedCard)
	err := c.cc.Invoke(ctx, "/repository.Repository/FindSavedCardById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RepositoryServer is the server API for Repository service.
type RepositoryServer interface {
	InsertSavedCard(context.Context, *SavedCardRequest) (*Result, error)
	DeleteSavedCard(context.Context, *FindByStringValue) (*Result, error)
	FindSavedCards(context.Context, *SavedCardRequest) (*SavedCardList, error)
	FindSavedCard(context.Context, *SavedCardRequest) (*billing.SavedCard, error)
	FindSavedCardById(context.Context, *FindByStringValue) (*billing.SavedCard, error)
}

func RegisterRepositoryServer(s *grpc.Server, srv RepositoryServer) {
	s.RegisterService(&_Repository_serviceDesc, srv)
}

func _Repository_InsertSavedCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SavedCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepositoryServer).InsertSavedCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/repository.Repository/InsertSavedCard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepositoryServer).InsertSavedCard(ctx, req.(*SavedCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Repository_DeleteSavedCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindByStringValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepositoryServer).DeleteSavedCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/repository.Repository/DeleteSavedCard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepositoryServer).DeleteSavedCard(ctx, req.(*FindByStringValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _Repository_FindSavedCards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SavedCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepositoryServer).FindSavedCards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/repository.Repository/FindSavedCards",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepositoryServer).FindSavedCards(ctx, req.(*SavedCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Repository_FindSavedCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SavedCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepositoryServer).FindSavedCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/repository.Repository/FindSavedCard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepositoryServer).FindSavedCard(ctx, req.(*SavedCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Repository_FindSavedCardById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindByStringValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepositoryServer).FindSavedCardById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/repository.Repository/FindSavedCardById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepositoryServer).FindSavedCardById(ctx, req.(*FindByStringValue))
	}
	return interceptor(ctx, in, info, handler)
}

var _Repository_serviceDesc = grpc.ServiceDesc{
	ServiceName: "repository.Repository",
	HandlerType: (*RepositoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InsertSavedCard",
			Handler:    _Repository_InsertSavedCard_Handler,
		},
		{
			MethodName: "DeleteSavedCard",
			Handler:    _Repository_DeleteSavedCard_Handler,
		},
		{
			MethodName: "FindSavedCards",
			Handler:    _Repository_FindSavedCards_Handler,
		},
		{
			MethodName: "FindSavedCard",
			Handler:    _Repository_FindSavedCard_Handler,
		},
		{
			MethodName: "FindSavedCardById",
			Handler:    _Repository_FindSavedCardById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "repository/repository.proto",
}

func init() {
	proto.RegisterFile("repository/repository.proto", fileDescriptor_repository_4f7234a8268002f6)
}

var fileDescriptor_repository_4f7234a8268002f6 = []byte{
	// 757 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x55, 0xcf, 0x53, 0xdb, 0x38,
	0x18, 0xc5, 0x61, 0x13, 0x92, 0x2f, 0x9b, 0x04, 0x04, 0xcb, 0x86, 0xec, 0x32, 0x9b, 0xf1, 0xee,
	0x32, 0x61, 0x7f, 0x24, 0x33, 0xe1, 0xd2, 0x4b, 0x87, 0x29, 0x81, 0x94, 0x4c, 0x5b, 0x48, 0x4d,
	0xe1, 0xd0, 0x8b, 0xc7, 0xb1, 0x44, 0x70, 0x6b, 0x4b, 0xae, 0x24, 0xa7, 0xcd, 0xdf, 0xd4, 0x3f,
	0xb0, 0xd7, 0x8e, 0x6c, 0xd9, 0x71, 0x20, 0x0c, 0x3d, 0x45, 0x7a, 0x7a, 0x7a, 0x4f, 0xef, 0x8b,
	0xfc, 0x09, 0x7e, 0xe3, 0x24, 0x64, 0xc2, 0x93, 0x8c, 0xcf, 0x7b, 0x8b, 0x61, 0x37, 0xe4, 0x4c,
	0x32, 0x04, 0x0b, 0xa4, 0xf5, 0xcb, 0xc4, 0xf3, 0x7d, 0x8f, 0x4e, 0x7b, 0xfa, 0x37, 0xa1, 0x98,
	0x65, 0x28, 0x59, 0x44, 0x44, 0xbe, 0x34, 0x29, 0xd4, 0x07, 0x8c, 0xce, 0x08, 0x97, 0x16, 0xf9,
	0x14, 0x11, 0x21, 0xd1, 0x9f, 0x50, 0x73, 0x23, 0xce, 0x09, 0x75, 0xe7, 0xf6, 0x2d, 0x67, 0x41,
	0xd3, 0x68, 0x1b, 0x9d, 0xa2, 0xf5, 0x73, 0x0a, 0x0e, 0x39, 0x0b, 0xd0, 0x1f, 0x50, 0xcd, 0x48,
	0x92, 0x35, 0x0b, 0x31, 0x05, 0x52, 0xe8, 0x1d, 0x43, 0xbb, 0x50, 0x72, 0x02, 0x16, 0x51, 0xd9,
	0x5c, 0x6f, 0x1b, 0x1d, 0xc3, 0xd2, 0x33, 0xf3, 0x10, 0x1a, 0x99, 0x9f, 0x08, 0x19, 0x15, 0x24,
	0x47, 0x35, 0x96, 0xa8, 0x7f, 0x01, 0x1a, 0x7a, 0x14, 0x9f, 0xcc, 0xaf, 0x29, 0x26, 0x5c, 0xb8,
	0x8c, 0x93, 0x11, 0x46, 0x75, 0x28, 0x78, 0x38, 0x66, 0x56, 0xac, 0x82, 0x87, 0xcd, 0x43, 0xd8,
	0x4a, 0x58, 0x57, 0x92, 0x7b, 0x74, 0x7a, 0xe3, 0xf8, 0x11, 0x41, 0x3b, 0x50, 0x9c, 0xa9, 0x81,
	0xe6, 0x25, 0x13, 0xd3, 0x04, 0x18, 0xfa, 0xcc, 0x91, 0x2b, 0x38, 0x46, 0xca, 0x39, 0x80, 0x7a,
	0x22, 0x37, 0xa2, 0xab, 0x78, 0xc5, 0x94, 0x77, 0x01, 0xad, 0x84, 0xf7, 0x92, 0xb3, 0x28, 0x1c,
	0xe8, 0xe0, 0x69, 0x0d, 0x77, 0xa0, 0x38, 0x55, 0x78, 0xea, 0x1f, 0x4f, 0x50, 0x0b, 0xca, 0x69,
	0x85, 0x74, 0xc5, 0xb2, 0xb9, 0x39, 0x86, 0x9d, 0x44, 0x6f, 0xcc, 0xd9, 0x07, 0xe2, 0xca, 0x4b,
	0x8e, 0x09, 0x1f, 0x61, 0xb4, 0x0f, 0x10, 0x26, 0x88, 0x9d, 0xc5, 0xae, 0x68, 0x64, 0x84, 0xd1,
	0x1e, 0x94, 0x99, 0x62, 0xaa, 0xc5, 0x42, 0xbc, 0xb8, 0xc1, 0x92, 0x9d, 0xe6, 0x33, 0x28, 0x6b,
	0x2d, 0x81, 0xfe, 0x83, 0xb2, 0xde, 0x23, 0x9a, 0x46, 0x7b, 0xbd, 0x53, 0xed, 0x6f, 0x76, 0xd3,
	0x1b, 0xa1, 0x49, 0x56, 0xc6, 0x30, 0xdf, 0x42, 0x7d, 0xec, 0xcc, 0x03, 0x42, 0xe5, 0x1b, 0x22,
	0xef, 0x18, 0x16, 0xe8, 0x18, 0x1a, 0x61, 0x82, 0xd8, 0x41, 0x02, 0x69, 0x99, 0xdd, 0x85, 0x4c,
	0x7e, 0x87, 0x55, 0x0f, 0x97, 0x04, 0xcc, 0x19, 0x6c, 0x0d, 0x58, 0x10, 0x78, 0x42, 0x78, 0x8c,
	0xa6, 0x55, 0x7a, 0x22, 0xdb, 0x3f, 0xb0, 0xb5, 0x6c, 0xba, 0x08, 0xd9, 0x58, 0x92, 0x1f, 0xe1,
	0x47, 0xaf, 0xdb, 0x2d, 0xa0, 0xbc, 0xaf, 0xbe, 0x71, 0x7f, 0x43, 0x7d, 0x59, 0x59, 0xdf, 0x81,
	0xda, 0x92, 0x2c, 0xda, 0x84, 0xf5, 0x50, 0x84, 0xb1, 0xa5, 0x61, 0xa9, 0x21, 0xfa, 0x15, 0x36,
	0x24, 0xb3, 0x23, 0x41, 0x78, 0xea, 0x23, 0xd9, 0xb5, 0x20, 0xdc, 0xfc, 0x0c, 0xdb, 0x03, 0xc7,
	0x77, 0x23, 0xdf, 0x91, 0xe4, 0xc6, 0xc9, 0xbe, 0xa5, 0x03, 0x68, 0xb8, 0xea, 0x1c, 0x7c, 0x6e,
	0xbb, 0x0c, 0x13, 0xdb, 0xe9, 0xeb, 0x98, 0x35, 0x0d, 0x0f, 0x18, 0x26, 0x2f, 0xfa, 0xa8, 0x0d,
	0x55, 0x11, 0x4d, 0xb0, 0x37, 0xf3, 0xd4, 0x39, 0x75, 0xc8, 0x3c, 0xf4, 0x68, 0xc0, 0xaf, 0x06,
	0x6c, 0x5e, 0x39, 0x33, 0x82, 0x07, 0x0e, 0xc7, 0xa9, 0x6d, 0x13, 0x36, 0x1c, 0xd7, 0xcd, 0x3e,
	0xa9, 0x8a, 0x95, 0x4e, 0xef, 0x95, 0xbc, 0x70, 0xbf, 0xe4, 0x2a, 0xb1, 0x43, 0x63, 0x8b, 0x8a,
	0xa5, 0x86, 0xe8, 0x5f, 0x28, 0x91, 0x2f, 0xa1, 0xc7, 0x49, 0xf3, 0xa7, 0xb6, 0xd1, 0xa9, 0xf6,
	0xb7, 0xb3, 0x3f, 0x5c, 0x19, 0x9e, 0xc5, 0x4b, 0x96, 0xa6, 0xc4, 0x5d, 0xc1, 0xe1, 0xd8, 0xbe,
	0x63, 0x3e, 0x26, 0xbc, 0x59, 0x8c, 0x65, 0x40, 0x41, 0xe7, 0x31, 0x62, 0x9e, 0x42, 0x2d, 0x3b,
	0xec, 0x6b, 0x4f, 0x48, 0x74, 0x04, 0x55, 0xa1, 0x00, 0x5b, 0x91, 0xd2, 0x4b, 0x85, 0x32, 0x8f,
	0x45, 0x32, 0x10, 0xe9, 0x50, 0xf4, 0xbf, 0x15, 0x00, 0xac, 0xac, 0xc7, 0xa1, 0x33, 0x68, 0x8c,
	0xa8, 0x20, 0x5c, 0x66, 0x6c, 0xf4, 0x7b, 0x37, 0xd7, 0x15, 0xef, 0x97, 0xa7, 0x85, 0xf2, 0xab,
	0xba, 0x0f, 0xae, 0xa1, 0x21, 0x34, 0x4e, 0x89, 0x4f, 0x24, 0x59, 0xc8, 0xec, 0xe7, 0x89, 0x0f,
	0xba, 0xcc, 0x23, 0x3a, 0xaf, 0x92, 0x0e, 0x92, 0xa9, 0x88, 0x27, 0x4e, 0xb3, 0xb7, 0x72, 0x55,
	0x55, 0xc7, 0x5c, 0x43, 0x03, 0xa8, 0x2d, 0x89, 0x3d, 0x99, 0xec, 0x41, 0xe5, 0xcc, 0x35, 0x74,
	0x9e, 0xb4, 0xc8, 0x0c, 0x3a, 0x99, 0x8f, 0x7e, 0x20, 0xdb, 0x0a, 0xa5, 0x93, 0xe3, 0xf7, 0xcf,
	0xa7, 0x9e, 0xbc, 0x8b, 0x26, 0x5d, 0x97, 0x05, 0xbd, 0xb1, 0x7a, 0x4b, 0x5c, 0xe6, 0x5f, 0x5e,
	0x9c, 0xf5, 0x42, 0x67, 0xce, 0x28, 0xf9, 0x3f, 0xf7, 0x2e, 0x85, 0x1f, 0xa7, 0xbd, 0xf8, 0xb5,
	0xc9, 0xbd, 0x50, 0x93, 0x52, 0x8c, 0x1c, 0x7d, 0x0f, 0x00, 0x00, 0xff, 0xff, 0xbe, 0x99, 0x2b,
	0x83, 0xc1, 0x06, 0x00, 0x00,
}
