// Code generated by protoc-gen-go. DO NOT EDIT.
// source: entity/entity.proto

package entity // import "github.com/ProtocolONE/payone-repository/pkg/proto/entity"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SavedCard struct {
	// @inject_tag: bson:"_id"
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"_id"`
	// @inject_tag: bson:"account"
	Account string `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty" bson:"account"`
	// @inject_tag: bson:"project_id"
	ProjectId string `protobuf:"bytes,3,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty" bson:"project_id"`
	// @inject_tag: bson:"masked_pan"
	MaskedPan string `protobuf:"bytes,4,opt,name=masked_pan,json=maskedPan,proto3" json:"masked_pan,omitempty" bson:"masked_pan"`
	// @inject_tag: bson:"pan"
	Pan string `protobuf:"bytes,5,opt,name=pan,proto3" json:"pan,omitempty" bson:"pan"`
	// @inject_tag: bson:"card_holder"
	CardHolder string `protobuf:"bytes,6,opt,name=card_holder,json=cardHolder,proto3" json:"card_holder,omitempty" bson:"card_holder"`
	// @inject_tag: bson:"expire"
	Expire *CardExpire `protobuf:"bytes,7,opt,name=expire,proto3" json:"expire,omitempty" bson:"expire"`
	// @inject_tag: bson:"is_active"
	IsActive bool `protobuf:"varint,8,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty" bson:"is_active"`
	// @inject_tag: bson:"created_at"
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty" bson:"created_at"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-" bson:"-" structure:"-"`
	XXX_unrecognized     []byte               `json:"-" bson:"-" structure:"-"`
	XXX_sizecache        int32                `json:"-" bson:"-" structure:"-"`
}

func (m *SavedCard) Reset()         { *m = SavedCard{} }
func (m *SavedCard) String() string { return proto.CompactTextString(m) }
func (*SavedCard) ProtoMessage()    {}
func (*SavedCard) Descriptor() ([]byte, []int) {
	return fileDescriptor_entity_07b8abe4d97f2182, []int{0}
}
func (m *SavedCard) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SavedCard.Unmarshal(m, b)
}
func (m *SavedCard) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SavedCard.Marshal(b, m, deterministic)
}
func (dst *SavedCard) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SavedCard.Merge(dst, src)
}
func (m *SavedCard) XXX_Size() int {
	return xxx_messageInfo_SavedCard.Size(m)
}
func (m *SavedCard) XXX_DiscardUnknown() {
	xxx_messageInfo_SavedCard.DiscardUnknown(m)
}

var xxx_messageInfo_SavedCard proto.InternalMessageInfo

func (m *SavedCard) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SavedCard) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *SavedCard) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *SavedCard) GetMaskedPan() string {
	if m != nil {
		return m.MaskedPan
	}
	return ""
}

func (m *SavedCard) GetPan() string {
	if m != nil {
		return m.Pan
	}
	return ""
}

func (m *SavedCard) GetCardHolder() string {
	if m != nil {
		return m.CardHolder
	}
	return ""
}

func (m *SavedCard) GetExpire() *CardExpire {
	if m != nil {
		return m.Expire
	}
	return nil
}

func (m *SavedCard) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

func (m *SavedCard) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type CardExpire struct {
	// @inject_tag: bson:"month"
	Month string `protobuf:"bytes,1,opt,name=month,proto3" json:"month,omitempty" bson:"month"`
	// @inject_tag: bson:"year"
	Year                 string   `protobuf:"bytes,2,opt,name=year,proto3" json:"year,omitempty" bson:"year"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-" structure:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-" structure:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-" structure:"-"`
}

func (m *CardExpire) Reset()         { *m = CardExpire{} }
func (m *CardExpire) String() string { return proto.CompactTextString(m) }
func (*CardExpire) ProtoMessage()    {}
func (*CardExpire) Descriptor() ([]byte, []int) {
	return fileDescriptor_entity_07b8abe4d97f2182, []int{1}
}
func (m *CardExpire) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CardExpire.Unmarshal(m, b)
}
func (m *CardExpire) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CardExpire.Marshal(b, m, deterministic)
}
func (dst *CardExpire) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CardExpire.Merge(dst, src)
}
func (m *CardExpire) XXX_Size() int {
	return xxx_messageInfo_CardExpire.Size(m)
}
func (m *CardExpire) XXX_DiscardUnknown() {
	xxx_messageInfo_CardExpire.DiscardUnknown(m)
}

var xxx_messageInfo_CardExpire proto.InternalMessageInfo

func (m *CardExpire) GetMonth() string {
	if m != nil {
		return m.Month
	}
	return ""
}

func (m *CardExpire) GetYear() string {
	if m != nil {
		return m.Year
	}
	return ""
}

func init() {
	proto.RegisterType((*SavedCard)(nil), "entity.SavedCard")
	proto.RegisterType((*CardExpire)(nil), "entity.CardExpire")
}

func init() { proto.RegisterFile("entity/entity.proto", fileDescriptor_entity_07b8abe4d97f2182) }

var fileDescriptor_entity_07b8abe4d97f2182 = []byte{
	// 343 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x91, 0x41, 0x6b, 0xe3, 0x30,
	0x10, 0x85, 0xb1, 0x93, 0x38, 0xf1, 0x04, 0x96, 0x45, 0xbb, 0x07, 0x91, 0x65, 0x49, 0xc8, 0x29,
	0x14, 0x6a, 0x43, 0x0b, 0x85, 0xd0, 0x53, 0x5a, 0x02, 0xed, 0xa5, 0x0d, 0x6e, 0x4f, 0xbd, 0x18,
	0x45, 0x9a, 0x3a, 0x6a, 0x62, 0x4b, 0xc8, 0x4a, 0xa8, 0xff, 0x52, 0x7f, 0x65, 0xb1, 0xe4, 0xd0,
	0x93, 0xe6, 0x7d, 0x6f, 0xd0, 0x48, 0x6f, 0xe0, 0x0f, 0x56, 0x56, 0xda, 0x26, 0xf5, 0x47, 0xa2,
	0x8d, 0xb2, 0x8a, 0x44, 0x5e, 0x4d, 0xa6, 0x85, 0x52, 0xc5, 0x01, 0x53, 0x47, 0xb7, 0xc7, 0xf7,
	0xd4, 0xca, 0x12, 0x6b, 0xcb, 0x4a, 0xed, 0x1b, 0xe7, 0x5f, 0x21, 0xc4, 0x2f, 0xec, 0x84, 0xe2,
	0x9e, 0x19, 0x41, 0x7e, 0x41, 0x28, 0x05, 0x0d, 0x66, 0xc1, 0x22, 0xce, 0x42, 0x29, 0x08, 0x85,
	0x21, 0xe3, 0x5c, 0x1d, 0x2b, 0x4b, 0x43, 0x07, 0xcf, 0x92, 0xfc, 0x07, 0xd0, 0x46, 0x7d, 0x20,
	0xb7, 0xb9, 0x14, 0xb4, 0xe7, 0xcc, 0xb8, 0x23, 0x8f, 0xa2, 0xb5, 0x4b, 0x56, 0xef, 0x51, 0xe4,
	0x9a, 0x55, 0xb4, 0xef, 0x6d, 0x4f, 0x36, 0xac, 0x22, 0xbf, 0xa1, 0xd7, 0xf2, 0x81, 0xe3, 0x6d,
	0x49, 0xa6, 0x30, 0xe6, 0xcc, 0x88, 0x7c, 0xa7, 0x0e, 0x02, 0x0d, 0x8d, 0x9c, 0x03, 0x2d, 0x7a,
	0x70, 0x84, 0x5c, 0x40, 0x84, 0x9f, 0x5a, 0x1a, 0xa4, 0xc3, 0x59, 0xb0, 0x18, 0x5f, 0x91, 0xa4,
	0xfb, 0x70, 0xfb, 0xf0, 0xb5, 0x73, 0xb2, 0xae, 0x83, 0xfc, 0x83, 0x58, 0xd6, 0x39, 0xe3, 0x56,
	0x9e, 0x90, 0x8e, 0x66, 0xc1, 0x62, 0x94, 0x8d, 0x64, 0xbd, 0x72, 0x9a, 0x2c, 0x01, 0xb8, 0x41,
	0x66, 0x51, 0xe4, 0xcc, 0xd2, 0xd8, 0x5d, 0x36, 0x49, 0x7c, 0x4e, 0xc9, 0x39, 0xa7, 0xe4, 0xf5,
	0x9c, 0x53, 0x16, 0x77, 0xdd, 0x2b, 0x3b, 0xbf, 0x01, 0xf8, 0x99, 0x46, 0xfe, 0xc2, 0xa0, 0x54,
	0x95, 0xdd, 0x75, 0x79, 0x79, 0x41, 0x08, 0xf4, 0x1b, 0x64, 0xa6, 0xcb, 0xcb, 0xd5, 0x77, 0xb7,
	0x6f, 0xcb, 0x42, 0xda, 0xdd, 0x71, 0x9b, 0x70, 0x55, 0xa6, 0x9b, 0x76, 0x06, 0x57, 0x87, 0xe7,
	0xa7, 0x75, 0xaa, 0x59, 0xa3, 0x2a, 0xbc, 0x34, 0xa8, 0x55, 0x2d, 0xad, 0x32, 0x4d, 0xaa, 0xf7,
	0x85, 0xdf, 0x56, 0xb7, 0xd0, 0x6d, 0xe4, 0xd4, 0xf5, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x17,
	0x40, 0x89, 0x79, 0xe8, 0x01, 0x00, 0x00,
}
