{{- $deployment := .Values.backend -}}
{{- $deploymentName := printf "%s-%s" .Release.Name $deployment.name }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $deploymentName }}
  labels:
    app: {{ .Chart.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    role: {{ $deployment.role }}
  annotations: 
    released: {{ .Release.Time}}    
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
      role: {{ $deployment.role }}
  replicas: {{ $deployment.replicas }} 
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        role: {{ $deployment.role }}
    spec:
      containers:
      - name: {{ $deployment.name }}
        image: {{ $deployment.image }}:{{ $deployment.imageTag }}
        env:
          - name: MONGO_HOST
            valueFrom:
              secretKeyRef:
                name: p1payapi-mongo-connection
                key: MONGO_HOST
          - name: MONGO_DB
            valueFrom:
              secretKeyRef:
                name: p1payapi-mongo-connection
                key: MONGO_DB
          - name: MONGO_USER
            valueFrom:
              secretKeyRef:
                name: p1payapi-mongo-connection
                key: MONGO_USER
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: p1payapi-mongo-connection
                key: MONGO_PASSWORD
          - name: MICRO_SERVER_ADDRESS
            value: "0.0.0.0:{{ $deployment.port }}"
          - name: MICRO_REGISTRY
            value: "kubernetes"
          - name: MICRO_SELECTOR
            value: "static"
          - name: METRICS_PORT
            value: "{{ $deployment.healthPort }}"

        #livenessProbe:
        #  httpGet:
        #    path: /_healthz
        #    port: {{ $deployment.port }}
        #  initialDelaySeconds: 5
        #  timeoutSeconds: 3
        #  failureThreshold: 2
