// Code generated by protoc-gen-go. DO NOT EDIT.
// source: payment_method.proto

package payment_method

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PaymentSystem struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Country              *Country             `protobuf:"bytes,3,opt,name=Country,proto3" json:"Country,omitempty"`
	AccountingCurrency   *Currency            `protobuf:"bytes,4,opt,name=accounting_currency,json=accountingCurrency,proto3" json:"accounting_currency,omitempty"`
	AccountingPeriod     string               `protobuf:"bytes,5,opt,name=accounting_period,json=accountingPeriod,proto3" json:"accounting_period,omitempty"`
	IsActive             bool                 `protobuf:"varint,6,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PaymentSystem) Reset()         { *m = PaymentSystem{} }
func (m *PaymentSystem) String() string { return proto.CompactTextString(m) }
func (*PaymentSystem) ProtoMessage()    {}
func (*PaymentSystem) Descriptor() ([]byte, []int) {
	return fileDescriptor_payment_method_ee5cd0bcebe6c0e7, []int{0}
}
func (m *PaymentSystem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentSystem.Unmarshal(m, b)
}
func (m *PaymentSystem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentSystem.Marshal(b, m, deterministic)
}
func (dst *PaymentSystem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentSystem.Merge(dst, src)
}
func (m *PaymentSystem) XXX_Size() int {
	return xxx_messageInfo_PaymentSystem.Size(m)
}
func (m *PaymentSystem) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentSystem.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentSystem proto.InternalMessageInfo

func (m *PaymentSystem) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PaymentSystem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PaymentSystem) GetCountry() *Country {
	if m != nil {
		return m.Country
	}
	return nil
}

func (m *PaymentSystem) GetAccountingCurrency() *Currency {
	if m != nil {
		return m.AccountingCurrency
	}
	return nil
}

func (m *PaymentSystem) GetAccountingPeriod() string {
	if m != nil {
		return m.AccountingPeriod
	}
	return ""
}

func (m *PaymentSystem) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

func (m *PaymentSystem) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *PaymentSystem) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type PaymentMethodParams struct {
	Handler              string            `protobuf:"bytes,1,opt,name=handler,proto3" json:"handler,omitempty"`
	Terminal             string            `protobuf:"bytes,2,opt,name=terminal,proto3" json:"terminal,omitempty"`
	ExternalId           string            `protobuf:"bytes,3,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	Other                map[string]string `protobuf:"bytes,4,rep,name=other,proto3" json:"other,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PaymentMethodParams) Reset()         { *m = PaymentMethodParams{} }
func (m *PaymentMethodParams) String() string { return proto.CompactTextString(m) }
func (*PaymentMethodParams) ProtoMessage()    {}
func (*PaymentMethodParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_payment_method_ee5cd0bcebe6c0e7, []int{1}
}
func (m *PaymentMethodParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentMethodParams.Unmarshal(m, b)
}
func (m *PaymentMethodParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentMethodParams.Marshal(b, m, deterministic)
}
func (dst *PaymentMethodParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentMethodParams.Merge(dst, src)
}
func (m *PaymentMethodParams) XXX_Size() int {
	return xxx_messageInfo_PaymentMethodParams.Size(m)
}
func (m *PaymentMethodParams) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentMethodParams.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentMethodParams proto.InternalMessageInfo

func (m *PaymentMethodParams) GetHandler() string {
	if m != nil {
		return m.Handler
	}
	return ""
}

func (m *PaymentMethodParams) GetTerminal() string {
	if m != nil {
		return m.Terminal
	}
	return ""
}

func (m *PaymentMethodParams) GetExternalId() string {
	if m != nil {
		return m.ExternalId
	}
	return ""
}

func (m *PaymentMethodParams) GetOther() map[string]string {
	if m != nil {
		return m.Other
	}
	return nil
}

type PaymentMethodOrder struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Params               *PaymentMethodParams `protobuf:"bytes,3,opt,name=params,proto3" json:"params,omitempty"`
	PaymentSystem        *PaymentSystem       `protobuf:"bytes,4,opt,name=payment_system,json=paymentSystem,proto3" json:"payment_system,omitempty"`
	GroupAlias           string               `protobuf:"bytes,5,opt,name=group_alias,json=groupAlias,proto3" json:"group_alias,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PaymentMethodOrder) Reset()         { *m = PaymentMethodOrder{} }
func (m *PaymentMethodOrder) String() string { return proto.CompactTextString(m) }
func (*PaymentMethodOrder) ProtoMessage()    {}
func (*PaymentMethodOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_payment_method_ee5cd0bcebe6c0e7, []int{2}
}
func (m *PaymentMethodOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentMethodOrder.Unmarshal(m, b)
}
func (m *PaymentMethodOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentMethodOrder.Marshal(b, m, deterministic)
}
func (dst *PaymentMethodOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentMethodOrder.Merge(dst, src)
}
func (m *PaymentMethodOrder) XXX_Size() int {
	return xxx_messageInfo_PaymentMethodOrder.Size(m)
}
func (m *PaymentMethodOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentMethodOrder.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentMethodOrder proto.InternalMessageInfo

func (m *PaymentMethodOrder) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PaymentMethodOrder) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PaymentMethodOrder) GetParams() *PaymentMethodParams {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *PaymentMethodOrder) GetPaymentSystem() *PaymentSystem {
	if m != nil {
		return m.PaymentSystem
	}
	return nil
}

func (m *PaymentMethodOrder) GetGroupAlias() string {
	if m != nil {
		return m.GroupAlias
	}
	return ""
}

func init() {
	proto.RegisterType((*PaymentSystem)(nil), "PaymentSystem")
	proto.RegisterType((*PaymentMethodParams)(nil), "PaymentMethodParams")
	proto.RegisterMapType((map[string]string)(nil), "PaymentMethodParams.OtherEntry")
	proto.RegisterType((*PaymentMethodOrder)(nil), "PaymentMethodOrder")
}

func init() {
	proto.RegisterFile("payment_method.proto", fileDescriptor_payment_method_ee5cd0bcebe6c0e7)
}

var fileDescriptor_payment_method_ee5cd0bcebe6c0e7 = []byte{
	// 453 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x4d, 0x8b, 0xdb, 0x30,
	0x10, 0xc5, 0xce, 0x97, 0x3d, 0x61, 0x43, 0xaa, 0xcd, 0xc1, 0xa4, 0x87, 0x84, 0x9c, 0x02, 0x2d,
	0x5a, 0xd8, 0xb2, 0xb0, 0xdd, 0x5b, 0x58, 0x7a, 0xe8, 0xa1, 0x6c, 0x70, 0x7b, 0x37, 0x5a, 0x6b,
	0x9a, 0x88, 0xda, 0x92, 0x91, 0xe5, 0xa5, 0xfe, 0x73, 0xfd, 0x13, 0x3d, 0xf7, 0xbf, 0x14, 0xcb,
	0x52, 0xd3, 0x40, 0xa0, 0xbd, 0xe9, 0xbd, 0x79, 0xa3, 0x19, 0xde, 0x3c, 0x58, 0x54, 0xac, 0x2d,
	0x51, 0x9a, 0xac, 0x44, 0x73, 0x54, 0x9c, 0x56, 0x5a, 0x19, 0xb5, 0x9c, 0x73, 0x91, 0x1b, 0xa1,
	0x24, 0xd3, 0xad, 0x63, 0x56, 0x07, 0xa5, 0x0e, 0x05, 0xde, 0x58, 0xf4, 0xdc, 0x7c, 0xbd, 0x31,
	0xa2, 0xc4, 0xda, 0xb0, 0xb2, 0xea, 0x05, 0x9b, 0x9f, 0x21, 0x5c, 0xed, 0xfb, 0xbf, 0x3e, 0xb7,
	0xb5, 0xc1, 0x92, 0xcc, 0x20, 0x14, 0x3c, 0x09, 0xd6, 0xc1, 0x36, 0x4e, 0x43, 0xc1, 0x09, 0x81,
	0xa1, 0x64, 0x25, 0x26, 0xa1, 0x65, 0xec, 0x9b, 0x6c, 0x60, 0xf2, 0xa8, 0x1a, 0x69, 0x74, 0x9b,
	0x0c, 0xd6, 0xc1, 0x76, 0x7a, 0x1b, 0x51, 0x87, 0x53, 0x5f, 0x20, 0x0f, 0x70, 0xcd, 0xf2, 0xbc,
	0x03, 0x42, 0x1e, 0xb2, 0xbc, 0xd1, 0x1a, 0x65, 0xde, 0x26, 0x43, 0xab, 0x8f, 0xe9, 0xa3, 0x23,
	0x52, 0x72, 0x52, 0x79, 0x8e, 0xbc, 0x81, 0x57, 0x7f, 0xf5, 0x56, 0xa8, 0x85, 0xe2, 0xc9, 0xc8,
	0x2e, 0x30, 0x3f, 0x15, 0xf6, 0x96, 0x27, 0xaf, 0x21, 0x16, 0x75, 0xc6, 0x72, 0x23, 0x5e, 0x30,
	0x19, 0xaf, 0x83, 0x6d, 0x94, 0x46, 0xa2, 0xde, 0x59, 0x4c, 0xde, 0x03, 0xe4, 0x1a, 0x99, 0x41,
	0x9e, 0x31, 0x93, 0x4c, 0xec, 0xf0, 0x25, 0xed, 0x5d, 0xa1, 0xde, 0x15, 0xfa, 0xc5, 0xbb, 0x92,
	0xc6, 0x4e, 0xbd, 0x33, 0x5d, 0x6b, 0x53, 0x71, 0xdf, 0x1a, 0xfd, 0xbb, 0xd5, 0xa9, 0x77, 0x66,
	0xf3, 0x2b, 0x80, 0x6b, 0xe7, 0xea, 0x27, 0x7b, 0xa0, 0x3d, 0xd3, 0xac, 0xac, 0x49, 0x02, 0x93,
	0x23, 0x93, 0xbc, 0x40, 0xed, 0x0c, 0xf6, 0x90, 0x2c, 0x21, 0x32, 0xa8, 0x4b, 0x21, 0x59, 0xe1,
	0x9c, 0xfe, 0x83, 0xc9, 0x0a, 0xa6, 0xf8, 0xdd, 0xa0, 0x96, 0xac, 0xc8, 0x04, 0xb7, 0x8e, 0xc7,
	0x29, 0x78, 0xea, 0x23, 0x27, 0x77, 0x30, 0x52, 0xe6, 0x88, 0x3a, 0x19, 0xae, 0x07, 0xdb, 0xe9,
	0xed, 0x8a, 0x5e, 0x98, 0x4d, 0x9f, 0x3a, 0xc5, 0x07, 0x7b, 0xa3, 0x5e, 0xbd, 0xbc, 0x07, 0x38,
	0x91, 0x64, 0x0e, 0x83, 0x6f, 0xd8, 0xba, 0xbd, 0xba, 0x27, 0x59, 0xc0, 0xe8, 0x85, 0x15, 0x8d,
	0x3f, 0x7d, 0x0f, 0x1e, 0xc2, 0xfb, 0x60, 0xf3, 0x23, 0x00, 0x72, 0x36, 0xe3, 0x49, 0x73, 0xd4,
	0xff, 0x15, 0x9d, 0xb7, 0x30, 0xae, 0xec, 0x42, 0x2e, 0x39, 0x8b, 0x4b, 0xcb, 0xa6, 0x4e, 0x43,
	0xee, 0x60, 0xe6, 0x93, 0x5e, 0xdb, 0x78, 0xba, 0xfc, 0xcc, 0xe8, 0x59, 0x68, 0xd3, 0xab, 0xea,
	0x2c, 0xc3, 0x2b, 0x98, 0x1e, 0xb4, 0x6a, 0xaa, 0x8c, 0x15, 0x82, 0xd5, 0x2e, 0x39, 0x60, 0xa9,
	0x5d, 0xc7, 0x3c, 0x8f, 0xed, 0xfd, 0xde, 0xfd, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xc7, 0x13, 0xea,
	0x64, 0x48, 0x03, 0x00, 0x00,
}
