// Code generated by protoc-gen-go. DO NOT EDIT.
// source: billing/billing.proto

package billing // import "github.com/ProtocolONE/payone-repository/pkg/proto/billing"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Name struct {
	// @inject_tag: bson:"EN"
	En string `protobuf:"bytes,1,opt,name=en,proto3" json:"en,omitempty" bson:"EN"`
	// @inject_tag: bson:"RU"
	Ru                   string   `protobuf:"bytes,2,opt,name=ru,proto3" json:"ru,omitempty" bson:"RU"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *Name) Reset()         { *m = Name{} }
func (m *Name) String() string { return proto.CompactTextString(m) }
func (*Name) ProtoMessage()    {}
func (*Name) Descriptor() ([]byte, []int) {
	return fileDescriptor_billing_aca9bda43472b59e, []int{0}
}
func (m *Name) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Name.Unmarshal(m, b)
}
func (m *Name) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Name.Marshal(b, m, deterministic)
}
func (dst *Name) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Name.Merge(dst, src)
}
func (m *Name) XXX_Size() int {
	return xxx_messageInfo_Name.Size(m)
}
func (m *Name) XXX_DiscardUnknown() {
	xxx_messageInfo_Name.DiscardUnknown(m)
}

var xxx_messageInfo_Name proto.InternalMessageInfo

func (m *Name) GetEn() string {
	if m != nil {
		return m.En
	}
	return ""
}

func (m *Name) GetRu() string {
	if m != nil {
		return m.Ru
	}
	return ""
}

type Country struct {
	// @inject_tag: bson:"code_int"
	CodeInt int32 `protobuf:"varint,1,opt,name=code_int,json=codeInt,proto3" json:"code_int,omitempty" bson:"code_int"`
	// @inject_tag: bson:"code_a2"
	CodeA2 string `protobuf:"bytes,2,opt,name=code_a2,json=codeA2,proto3" json:"code_a2,omitempty" bson:"code_a2"`
	// @inject_tag: bson:"code_a3"
	CodeA3 string `protobuf:"bytes,3,opt,name=code_a3,json=codeA3,proto3" json:"code_a3,omitempty" bson:"code_a3"`
	// @inject_tag: bson:"name"
	Name *Name `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty" bson:"name"`
	// @inject_tag: bson:"is_active"
	IsActive bool `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty" bson:"is_active"`
	// @inject_tag: bson:"created_at,timestamp"
	CreatedAt *timestamp.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty" bson:"created_at,timestamp"`
	// @inject_tag: bson:"updated_at,timestamp"
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty" bson:"updated_at,timestamp"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-" bson:"-"`
	XXX_unrecognized     []byte               `json:"-" bson:"-"`
	XXX_sizecache        int32                `json:"-" bson:"-"`
}

func (m *Country) Reset()         { *m = Country{} }
func (m *Country) String() string { return proto.CompactTextString(m) }
func (*Country) ProtoMessage()    {}
func (*Country) Descriptor() ([]byte, []int) {
	return fileDescriptor_billing_aca9bda43472b59e, []int{1}
}
func (m *Country) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Country.Unmarshal(m, b)
}
func (m *Country) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Country.Marshal(b, m, deterministic)
}
func (dst *Country) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Country.Merge(dst, src)
}
func (m *Country) XXX_Size() int {
	return xxx_messageInfo_Country.Size(m)
}
func (m *Country) XXX_DiscardUnknown() {
	xxx_messageInfo_Country.DiscardUnknown(m)
}

var xxx_messageInfo_Country proto.InternalMessageInfo

func (m *Country) GetCodeInt() int32 {
	if m != nil {
		return m.CodeInt
	}
	return 0
}

func (m *Country) GetCodeA2() string {
	if m != nil {
		return m.CodeA2
	}
	return ""
}

func (m *Country) GetCodeA3() string {
	if m != nil {
		return m.CodeA3
	}
	return ""
}

func (m *Country) GetName() *Name {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *Country) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

func (m *Country) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Country) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type Currency struct {
	// @inject_tag: bson:"code_int"
	CodeInt int32 `protobuf:"varint,1,opt,name=code_int,json=codeInt,proto3" json:"code_int,omitempty" bson:"code_int"`
	// @inject_tag: bson:"code_a3"
	CodeA3 string `protobuf:"bytes,2,opt,name=code_a3,json=codeA3,proto3" json:"code_a3,omitempty" bson:"code_a3"`
	// @inject_tag: bson:"name"
	Name *Name `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty" bson:"name"`
	// @inject_tag: bson:"is_active"
	IsActive bool `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty" bson:"is_active"`
	// @inject_tag: bson:"created_at,timestamp"
	CreatedAt *timestamp.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty" bson:"created_at,timestamp"`
	// @inject_tag: bson:"updated_at,timestamp"
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty" bson:"updated_at,timestamp"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-" bson:"-"`
	XXX_unrecognized     []byte               `json:"-" bson:"-"`
	XXX_sizecache        int32                `json:"-" bson:"-"`
}

func (m *Currency) Reset()         { *m = Currency{} }
func (m *Currency) String() string { return proto.CompactTextString(m) }
func (*Currency) ProtoMessage()    {}
func (*Currency) Descriptor() ([]byte, []int) {
	return fileDescriptor_billing_aca9bda43472b59e, []int{2}
}
func (m *Currency) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Currency.Unmarshal(m, b)
}
func (m *Currency) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Currency.Marshal(b, m, deterministic)
}
func (dst *Currency) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Currency.Merge(dst, src)
}
func (m *Currency) XXX_Size() int {
	return xxx_messageInfo_Currency.Size(m)
}
func (m *Currency) XXX_DiscardUnknown() {
	xxx_messageInfo_Currency.DiscardUnknown(m)
}

var xxx_messageInfo_Currency proto.InternalMessageInfo

func (m *Currency) GetCodeInt() int32 {
	if m != nil {
		return m.CodeInt
	}
	return 0
}

func (m *Currency) GetCodeA3() string {
	if m != nil {
		return m.CodeA3
	}
	return ""
}

func (m *Currency) GetName() *Name {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *Currency) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

func (m *Currency) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Currency) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type Merchant struct {
	// @inject_tag: bson:"_id,bsonobjectid"
	Id []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"_id,bsonobjectid"`
	// @inject_tag: bson:"external_id"
	ExternalId string `protobuf:"bytes,2,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty" bson:"external_id"`
	// @inject_tag: bson:"email"
	Email string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty" bson:"email"`
	// @inject_tag: bson:"name"
	Name string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty" bson:"name"`
	// @inject_tag: bson:"country"
	Country *Country `protobuf:"bytes,5,opt,name=country,proto3" json:"country,omitempty" bson:"country"`
	// @inject_tag: bson:"accounting_period"
	AccountingPeriod string `protobuf:"bytes,6,opt,name=accounting_period,json=accountingPeriod,proto3" json:"accounting_period,omitempty" bson:"accounting_period"`
	// @inject_tag: bson:"currency"
	Currency *Currency `protobuf:"bytes,7,opt,name=currency,proto3" json:"currency,omitempty" bson:"currency"`
	// @inject_tag: bson:"is_vat_enabled"
	IsVatEnabled bool `protobuf:"varint,8,opt,name=is_vat_enabled,json=isVatEnabled,proto3" json:"is_vat_enabled,omitempty" bson:"is_vat_enabled"`
	// @inject_tag: bson:"is_commission_to_user_enabled"
	IsCommissionToUserEnabled bool `protobuf:"varint,9,opt,name=is_commission_to_user_enabled,json=isCommissionToUserEnabled,proto3" json:"is_commission_to_user_enabled,omitempty" bson:"is_commission_to_user_enabled"`
	// @inject_tag: bson:"status"
	Status int32 `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty" bson:"status"`
	// @inject_tag: bson:"created_at,timestamp"
	CreatedAt *timestamp.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty" bson:"created_at,timestamp"`
	// @inject_tag: bson:"updated_at,timestamp"
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty" bson:"updated_at,timestamp"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-" bson:"-"`
	XXX_unrecognized     []byte               `json:"-" bson:"-"`
	XXX_sizecache        int32                `json:"-" bson:"-"`
}

func (m *Merchant) Reset()         { *m = Merchant{} }
func (m *Merchant) String() string { return proto.CompactTextString(m) }
func (*Merchant) ProtoMessage()    {}
func (*Merchant) Descriptor() ([]byte, []int) {
	return fileDescriptor_billing_aca9bda43472b59e, []int{3}
}
func (m *Merchant) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Merchant.Unmarshal(m, b)
}
func (m *Merchant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Merchant.Marshal(b, m, deterministic)
}
func (dst *Merchant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Merchant.Merge(dst, src)
}
func (m *Merchant) XXX_Size() int {
	return xxx_messageInfo_Merchant.Size(m)
}
func (m *Merchant) XXX_DiscardUnknown() {
	xxx_messageInfo_Merchant.DiscardUnknown(m)
}

var xxx_messageInfo_Merchant proto.InternalMessageInfo

func (m *Merchant) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Merchant) GetExternalId() string {
	if m != nil {
		return m.ExternalId
	}
	return ""
}

func (m *Merchant) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Merchant) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Merchant) GetCountry() *Country {
	if m != nil {
		return m.Country
	}
	return nil
}

func (m *Merchant) GetAccountingPeriod() string {
	if m != nil {
		return m.AccountingPeriod
	}
	return ""
}

func (m *Merchant) GetCurrency() *Currency {
	if m != nil {
		return m.Currency
	}
	return nil
}

func (m *Merchant) GetIsVatEnabled() bool {
	if m != nil {
		return m.IsVatEnabled
	}
	return false
}

func (m *Merchant) GetIsCommissionToUserEnabled() bool {
	if m != nil {
		return m.IsCommissionToUserEnabled
	}
	return false
}

func (m *Merchant) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Merchant) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Merchant) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type FixedPackage struct {
	// @inject_tag: bson:"id"
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"id"`
	// @inject_tag: bson:"name"
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" bson:"name"`
	// @inject_tag: bson:"currency_int"
	CurrencyInt int32 `protobuf:"varint,3,opt,name=currency_int,json=currencyInt,proto3" json:"currency_int,omitempty" bson:"currency_int"`
	// @inject_tag: bson:"price"
	Price float64 `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty" bson:"price"`
	// @inject_tag: bson:"is_active"
	IsActive bool `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty" bson:"is_active"`
	// @inject_tag: bson:"created_at,timestamp"
	CreatedAt *timestamp.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty" bson:"created_at,timestamp"`
	// @inject_tag: bson:"updated_at,timestamp"
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty" bson:"updated_at,timestamp"`
	Currency             *Currency            `protobuf:"bytes,8,opt,name=currency,proto3" json:"currency,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-" bson:"-"`
	XXX_unrecognized     []byte               `json:"-" bson:"-"`
	XXX_sizecache        int32                `json:"-" bson:"-"`
}

func (m *FixedPackage) Reset()         { *m = FixedPackage{} }
func (m *FixedPackage) String() string { return proto.CompactTextString(m) }
func (*FixedPackage) ProtoMessage()    {}
func (*FixedPackage) Descriptor() ([]byte, []int) {
	return fileDescriptor_billing_aca9bda43472b59e, []int{4}
}
func (m *FixedPackage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FixedPackage.Unmarshal(m, b)
}
func (m *FixedPackage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FixedPackage.Marshal(b, m, deterministic)
}
func (dst *FixedPackage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FixedPackage.Merge(dst, src)
}
func (m *FixedPackage) XXX_Size() int {
	return xxx_messageInfo_FixedPackage.Size(m)
}
func (m *FixedPackage) XXX_DiscardUnknown() {
	xxx_messageInfo_FixedPackage.DiscardUnknown(m)
}

var xxx_messageInfo_FixedPackage proto.InternalMessageInfo

func (m *FixedPackage) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *FixedPackage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FixedPackage) GetCurrencyInt() int32 {
	if m != nil {
		return m.CurrencyInt
	}
	return 0
}

func (m *FixedPackage) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *FixedPackage) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

func (m *FixedPackage) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *FixedPackage) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *FixedPackage) GetCurrency() *Currency {
	if m != nil {
		return m.Currency
	}
	return nil
}

type FixedPackages struct {
	FixedPackage         []*FixedPackage `protobuf:"bytes,1,rep,name=fixed_package,json=fixedPackage,proto3" json:"fixed_package,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-" bson:"-"`
	XXX_unrecognized     []byte          `json:"-" bson:"-"`
	XXX_sizecache        int32           `json:"-" bson:"-"`
}

func (m *FixedPackages) Reset()         { *m = FixedPackages{} }
func (m *FixedPackages) String() string { return proto.CompactTextString(m) }
func (*FixedPackages) ProtoMessage()    {}
func (*FixedPackages) Descriptor() ([]byte, []int) {
	return fileDescriptor_billing_aca9bda43472b59e, []int{5}
}
func (m *FixedPackages) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FixedPackages.Unmarshal(m, b)
}
func (m *FixedPackages) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FixedPackages.Marshal(b, m, deterministic)
}
func (dst *FixedPackages) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FixedPackages.Merge(dst, src)
}
func (m *FixedPackages) XXX_Size() int {
	return xxx_messageInfo_FixedPackages.Size(m)
}
func (m *FixedPackages) XXX_DiscardUnknown() {
	xxx_messageInfo_FixedPackages.DiscardUnknown(m)
}

var xxx_messageInfo_FixedPackages proto.InternalMessageInfo

func (m *FixedPackages) GetFixedPackage() []*FixedPackage {
	if m != nil {
		return m.FixedPackage
	}
	return nil
}

type ProjectPaymentMethod struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AddedAt              *timestamp.Timestamp `protobuf:"bytes,2,opt,name=added_at,json=addedAt,proto3" json:"added_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-" bson:"-"`
	XXX_unrecognized     []byte               `json:"-" bson:"-"`
	XXX_sizecache        int32                `json:"-" bson:"-"`
}

func (m *ProjectPaymentMethod) Reset()         { *m = ProjectPaymentMethod{} }
func (m *ProjectPaymentMethod) String() string { return proto.CompactTextString(m) }
func (*ProjectPaymentMethod) ProtoMessage()    {}
func (*ProjectPaymentMethod) Descriptor() ([]byte, []int) {
	return fileDescriptor_billing_aca9bda43472b59e, []int{6}
}
func (m *ProjectPaymentMethod) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectPaymentMethod.Unmarshal(m, b)
}
func (m *ProjectPaymentMethod) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectPaymentMethod.Marshal(b, m, deterministic)
}
func (dst *ProjectPaymentMethod) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectPaymentMethod.Merge(dst, src)
}
func (m *ProjectPaymentMethod) XXX_Size() int {
	return xxx_messageInfo_ProjectPaymentMethod.Size(m)
}
func (m *ProjectPaymentMethod) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectPaymentMethod.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectPaymentMethod proto.InternalMessageInfo

func (m *ProjectPaymentMethod) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ProjectPaymentMethod) GetAddedAt() *timestamp.Timestamp {
	if m != nil {
		return m.AddedAt
	}
	return nil
}

type ProjectPaymentMethods struct {
	PaymentMethods       []*ProjectPaymentMethod `protobuf:"bytes,1,rep,name=payment_methods,json=paymentMethods,proto3" json:"payment_methods,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-" bson:"-"`
	XXX_unrecognized     []byte                  `json:"-" bson:"-"`
	XXX_sizecache        int32                   `json:"-" bson:"-"`
}

func (m *ProjectPaymentMethods) Reset()         { *m = ProjectPaymentMethods{} }
func (m *ProjectPaymentMethods) String() string { return proto.CompactTextString(m) }
func (*ProjectPaymentMethods) ProtoMessage()    {}
func (*ProjectPaymentMethods) Descriptor() ([]byte, []int) {
	return fileDescriptor_billing_aca9bda43472b59e, []int{7}
}
func (m *ProjectPaymentMethods) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectPaymentMethods.Unmarshal(m, b)
}
func (m *ProjectPaymentMethods) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectPaymentMethods.Marshal(b, m, deterministic)
}
func (dst *ProjectPaymentMethods) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectPaymentMethods.Merge(dst, src)
}
func (m *ProjectPaymentMethods) XXX_Size() int {
	return xxx_messageInfo_ProjectPaymentMethods.Size(m)
}
func (m *ProjectPaymentMethods) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectPaymentMethods.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectPaymentMethods proto.InternalMessageInfo

func (m *ProjectPaymentMethods) GetPaymentMethods() []*ProjectPaymentMethod {
	if m != nil {
		return m.PaymentMethods
	}
	return nil
}

type Project struct {
	Id                         []byte                            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CallbackCurrency           *Currency                         `protobuf:"bytes,2,opt,name=callback_currency,json=callbackCurrency,proto3" json:"callback_currency,omitempty"`
	CallbackProtocol           string                            `protobuf:"bytes,3,opt,name=callback_protocol,json=callbackProtocol,proto3" json:"callback_protocol,omitempty"`
	CreateInvoiceAllowedUrls   []string                          `protobuf:"bytes,4,rep,name=create_invoice_allowed_urls,json=createInvoiceAllowedUrls,proto3" json:"create_invoice_allowed_urls,omitempty"`
	Merchant                   *Merchant                         `protobuf:"bytes,5,opt,name=merchant,proto3" json:"merchant,omitempty"`
	IsAllowDynamicNotifyUrls   bool                              `protobuf:"varint,6,opt,name=is_allow_dynamic_notify_urls,json=isAllowDynamicNotifyUrls,proto3" json:"is_allow_dynamic_notify_urls,omitempty"`
	IsAllowDynamicRedirectUrls bool                              `protobuf:"varint,7,opt,name=is_allow_dynamic_redirect_urls,json=isAllowDynamicRedirectUrls,proto3" json:"is_allow_dynamic_redirect_urls,omitempty"`
	LimitsCurrency             *Currency                         `protobuf:"bytes,8,opt,name=limits_currency,json=limitsCurrency,proto3" json:"limits_currency,omitempty"`
	MaxPaymentAmount           float64                           `protobuf:"fixed64,9,opt,name=MaxPaymentAmount,proto3" json:"MaxPaymentAmount,omitempty"`
	MinPaymentAmount           float64                           `protobuf:"fixed64,10,opt,name=MinPaymentAmount,proto3" json:"MinPaymentAmount,omitempty"`
	Name                       string                            `protobuf:"bytes,11,opt,name=Name,proto3" json:"Name,omitempty"`
	NotifyEmails               []string                          `protobuf:"bytes,12,rep,name=NotifyEmails,proto3" json:"NotifyEmails,omitempty"`
	OnlyFixedAmounts           bool                              `protobuf:"varint,13,opt,name=OnlyFixedAmounts,proto3" json:"OnlyFixedAmounts,omitempty"`
	SecretKey                  string                            `protobuf:"bytes,14,opt,name=SecretKey,proto3" json:"SecretKey,omitempty"`
	SendNotifyEmail            bool                              `protobuf:"varint,15,opt,name=SendNotifyEmail,proto3" json:"SendNotifyEmail,omitempty"`
	URLCheckAccount            string                            `protobuf:"bytes,16,opt,name=URLCheckAccount,proto3" json:"URLCheckAccount,omitempty"`
	URLProcessPayment          string                            `protobuf:"bytes,17,opt,name=URLProcessPayment,proto3" json:"URLProcessPayment,omitempty"`
	URLRedirectFail            string                            `protobuf:"bytes,18,opt,name=URLRedirectFail,proto3" json:"URLRedirectFail,omitempty"`
	URLRedirectSuccess         string                            `protobuf:"bytes,19,opt,name=URLRedirectSuccess,proto3" json:"URLRedirectSuccess,omitempty"`
	FixedPackage               map[string]*FixedPackages         `protobuf:"bytes,23,rep,name=fixed_package,json=fixedPackage,proto3" json:"fixed_package,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	PaymentMethods             map[string]*ProjectPaymentMethods `protobuf:"bytes,24,rep,name=payment_methods,json=paymentMethods,proto3" json:"payment_methods,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	IsActive                   bool                              `protobuf:"varint,20,opt,name=IsActive,proto3" json:"IsActive,omitempty"`
	// @inject_tag: bson:"created_at,timestamp"
	CreatedAt *timestamp.Timestamp `protobuf:"bytes,21,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty" bson:"created_at,timestamp"`
	// @inject_tag: bson:"updated_at,timestamp"
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,22,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty" bson:"updated_at,timestamp"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-" bson:"-"`
	XXX_unrecognized     []byte               `json:"-" bson:"-"`
	XXX_sizecache        int32                `json:"-" bson:"-"`
}

func (m *Project) Reset()         { *m = Project{} }
func (m *Project) String() string { return proto.CompactTextString(m) }
func (*Project) ProtoMessage()    {}
func (*Project) Descriptor() ([]byte, []int) {
	return fileDescriptor_billing_aca9bda43472b59e, []int{8}
}
func (m *Project) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Project.Unmarshal(m, b)
}
func (m *Project) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Project.Marshal(b, m, deterministic)
}
func (dst *Project) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Project.Merge(dst, src)
}
func (m *Project) XXX_Size() int {
	return xxx_messageInfo_Project.Size(m)
}
func (m *Project) XXX_DiscardUnknown() {
	xxx_messageInfo_Project.DiscardUnknown(m)
}

var xxx_messageInfo_Project proto.InternalMessageInfo

func (m *Project) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Project) GetCallbackCurrency() *Currency {
	if m != nil {
		return m.CallbackCurrency
	}
	return nil
}

func (m *Project) GetCallbackProtocol() string {
	if m != nil {
		return m.CallbackProtocol
	}
	return ""
}

func (m *Project) GetCreateInvoiceAllowedUrls() []string {
	if m != nil {
		return m.CreateInvoiceAllowedUrls
	}
	return nil
}

func (m *Project) GetMerchant() *Merchant {
	if m != nil {
		return m.Merchant
	}
	return nil
}

func (m *Project) GetIsAllowDynamicNotifyUrls() bool {
	if m != nil {
		return m.IsAllowDynamicNotifyUrls
	}
	return false
}

func (m *Project) GetIsAllowDynamicRedirectUrls() bool {
	if m != nil {
		return m.IsAllowDynamicRedirectUrls
	}
	return false
}

func (m *Project) GetLimitsCurrency() *Currency {
	if m != nil {
		return m.LimitsCurrency
	}
	return nil
}

func (m *Project) GetMaxPaymentAmount() float64 {
	if m != nil {
		return m.MaxPaymentAmount
	}
	return 0
}

func (m *Project) GetMinPaymentAmount() float64 {
	if m != nil {
		return m.MinPaymentAmount
	}
	return 0
}

func (m *Project) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Project) GetNotifyEmails() []string {
	if m != nil {
		return m.NotifyEmails
	}
	return nil
}

func (m *Project) GetOnlyFixedAmounts() bool {
	if m != nil {
		return m.OnlyFixedAmounts
	}
	return false
}

func (m *Project) GetSecretKey() string {
	if m != nil {
		return m.SecretKey
	}
	return ""
}

func (m *Project) GetSendNotifyEmail() bool {
	if m != nil {
		return m.SendNotifyEmail
	}
	return false
}

func (m *Project) GetURLCheckAccount() string {
	if m != nil {
		return m.URLCheckAccount
	}
	return ""
}

func (m *Project) GetURLProcessPayment() string {
	if m != nil {
		return m.URLProcessPayment
	}
	return ""
}

func (m *Project) GetURLRedirectFail() string {
	if m != nil {
		return m.URLRedirectFail
	}
	return ""
}

func (m *Project) GetURLRedirectSuccess() string {
	if m != nil {
		return m.URLRedirectSuccess
	}
	return ""
}

func (m *Project) GetFixedPackage() map[string]*FixedPackages {
	if m != nil {
		return m.FixedPackage
	}
	return nil
}

func (m *Project) GetPaymentMethods() map[string]*ProjectPaymentMethods {
	if m != nil {
		return m.PaymentMethods
	}
	return nil
}

func (m *Project) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

func (m *Project) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Project) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type ProjectOrder struct {
	// @inject_tag: bson:"id,bsonobjectid"
	Id []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"id,bsonobjectid"`
	// @inject_tag: bson:"name"
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" bson:"name"`
	// @inject_tag: bson:"url_success"
	UrlSuccess string `protobuf:"bytes,3,opt,name=url_success,json=urlSuccess,proto3" json:"url_success,omitempty" bson:"url_success"`
	// @inject_tag: bson:"url_fail"
	UrlFail string `protobuf:"bytes,4,opt,name=url_fail,json=urlFail,proto3" json:"url_fail,omitempty" bson:"url_fail"`
	// @inject_tag: bson:"notify_emails"
	NotifyEmails []string `protobuf:"bytes,5,rep,name=notify_emails,json=notifyEmails,proto3" json:"notify_emails,omitempty" bson:"notify_emails"`
	// @inject_tag: bson:"secret_key"
	SecretKey string `protobuf:"bytes,6,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty" bson:"secret_key"`
	// @inject_tag: bson:"send_notify_email"
	SendNotifyEmail bool `protobuf:"varint,7,opt,name=send_notify_email,json=sendNotifyEmail,proto3" json:"send_notify_email,omitempty" bson:"send_notify_email"`
	// @inject_tag: bson:"url_check_account"
	UrlCheckAccount string `protobuf:"bytes,8,opt,name=url_check_account,json=urlCheckAccount,proto3" json:"url_check_account,omitempty" bson:"url_check_account"`
	// @inject_tag: bson:"url_process_payment"
	UrlProcessPayment string `protobuf:"bytes,9,opt,name=url_process_payment,json=urlProcessPayment,proto3" json:"url_process_payment,omitempty" bson:"url_process_payment"`
	// @inject_tag: bson:"callback_protocol"
	CallbackProtocol string `protobuf:"bytes,10,opt,name=callback_protocol,json=callbackProtocol,proto3" json:"callback_protocol,omitempty" bson:"callback_protocol"`
	// @inject_tag: bson:"merchant"
	Merchant             *Merchant `protobuf:"bytes,11,opt,name=merchant,proto3" json:"merchant,omitempty" bson:"merchant"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-" bson:"-"`
	XXX_unrecognized     []byte    `json:"-" bson:"-"`
	XXX_sizecache        int32     `json:"-" bson:"-"`
}

func (m *ProjectOrder) Reset()         { *m = ProjectOrder{} }
func (m *ProjectOrder) String() string { return proto.CompactTextString(m) }
func (*ProjectOrder) ProtoMessage()    {}
func (*ProjectOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_billing_aca9bda43472b59e, []int{9}
}
func (m *ProjectOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectOrder.Unmarshal(m, b)
}
func (m *ProjectOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectOrder.Marshal(b, m, deterministic)
}
func (dst *ProjectOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectOrder.Merge(dst, src)
}
func (m *ProjectOrder) XXX_Size() int {
	return xxx_messageInfo_ProjectOrder.Size(m)
}
func (m *ProjectOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectOrder.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectOrder proto.InternalMessageInfo

func (m *ProjectOrder) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *ProjectOrder) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ProjectOrder) GetUrlSuccess() string {
	if m != nil {
		return m.UrlSuccess
	}
	return ""
}

func (m *ProjectOrder) GetUrlFail() string {
	if m != nil {
		return m.UrlFail
	}
	return ""
}

func (m *ProjectOrder) GetNotifyEmails() []string {
	if m != nil {
		return m.NotifyEmails
	}
	return nil
}

func (m *ProjectOrder) GetSecretKey() string {
	if m != nil {
		return m.SecretKey
	}
	return ""
}

func (m *ProjectOrder) GetSendNotifyEmail() bool {
	if m != nil {
		return m.SendNotifyEmail
	}
	return false
}

func (m *ProjectOrder) GetUrlCheckAccount() string {
	if m != nil {
		return m.UrlCheckAccount
	}
	return ""
}

func (m *ProjectOrder) GetUrlProcessPayment() string {
	if m != nil {
		return m.UrlProcessPayment
	}
	return ""
}

func (m *ProjectOrder) GetCallbackProtocol() string {
	if m != nil {
		return m.CallbackProtocol
	}
	return ""
}

func (m *ProjectOrder) GetMerchant() *Merchant {
	if m != nil {
		return m.Merchant
	}
	return nil
}

type PaymentSystem struct {
	// @inject_tag: bson:"_id,bsonobjectid"
	Id []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"_id,bsonobjectid"`
	// @inject_tag: bson:"name"
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" bson:"name"`
	// @inject_tag: bson:"country"
	Country *Country `protobuf:"bytes,3,opt,name=Country,proto3" json:"Country,omitempty" bson:"country"`
	// @inject_tag: bson:"accounting_currency"
	AccountingCurrency *Currency `protobuf:"bytes,4,opt,name=accounting_currency,json=accountingCurrency,proto3" json:"accounting_currency,omitempty" bson:"accounting_currency"`
	// @inject_tag: bson:"accounting_period"
	AccountingPeriod string `protobuf:"bytes,5,opt,name=accounting_period,json=accountingPeriod,proto3" json:"accounting_period,omitempty" bson:"accounting_period"`
	// @inject_tag: bson:"is_active"
	IsActive bool `protobuf:"varint,6,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty" bson:"is_active"`
	// @inject_tag: bson:"created_at,timestamp"
	CreatedAt *timestamp.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty" bson:"created_at,timestamp"`
	// @inject_tag: bson:"updated_at,timestamp"
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty" bson:"updated_at,timestamp"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-" bson:"-"`
	XXX_unrecognized     []byte               `json:"-" bson:"-"`
	XXX_sizecache        int32                `json:"-" bson:"-"`
}

func (m *PaymentSystem) Reset()         { *m = PaymentSystem{} }
func (m *PaymentSystem) String() string { return proto.CompactTextString(m) }
func (*PaymentSystem) ProtoMessage()    {}
func (*PaymentSystem) Descriptor() ([]byte, []int) {
	return fileDescriptor_billing_aca9bda43472b59e, []int{10}
}
func (m *PaymentSystem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentSystem.Unmarshal(m, b)
}
func (m *PaymentSystem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentSystem.Marshal(b, m, deterministic)
}
func (dst *PaymentSystem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentSystem.Merge(dst, src)
}
func (m *PaymentSystem) XXX_Size() int {
	return xxx_messageInfo_PaymentSystem.Size(m)
}
func (m *PaymentSystem) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentSystem.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentSystem proto.InternalMessageInfo

func (m *PaymentSystem) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *PaymentSystem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PaymentSystem) GetCountry() *Country {
	if m != nil {
		return m.Country
	}
	return nil
}

func (m *PaymentSystem) GetAccountingCurrency() *Currency {
	if m != nil {
		return m.AccountingCurrency
	}
	return nil
}

func (m *PaymentSystem) GetAccountingPeriod() string {
	if m != nil {
		return m.AccountingPeriod
	}
	return ""
}

func (m *PaymentSystem) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

func (m *PaymentSystem) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *PaymentSystem) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type PaymentMethodParams struct {
	// @inject_tag: bson:"handler"
	Handler string `protobuf:"bytes,1,opt,name=handler,proto3" json:"handler,omitempty" bson:"handler"`
	// @inject_tag: bson:"terminal"
	Terminal string `protobuf:"bytes,2,opt,name=terminal,proto3" json:"terminal,omitempty" bson:"terminal"`
	// @inject_tag: bson:"external_id"
	ExternalId string `protobuf:"bytes,3,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty" bson:"external_id"`
	// @inject_tag: bson:"other"
	Other                map[string]string `protobuf:"bytes,4,rep,name=other,proto3" json:"other,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3" bson:"other"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-" bson:"-"`
	XXX_unrecognized     []byte            `json:"-" bson:"-"`
	XXX_sizecache        int32             `json:"-" bson:"-"`
}

func (m *PaymentMethodParams) Reset()         { *m = PaymentMethodParams{} }
func (m *PaymentMethodParams) String() string { return proto.CompactTextString(m) }
func (*PaymentMethodParams) ProtoMessage()    {}
func (*PaymentMethodParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_billing_aca9bda43472b59e, []int{11}
}
func (m *PaymentMethodParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentMethodParams.Unmarshal(m, b)
}
func (m *PaymentMethodParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentMethodParams.Marshal(b, m, deterministic)
}
func (dst *PaymentMethodParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentMethodParams.Merge(dst, src)
}
func (m *PaymentMethodParams) XXX_Size() int {
	return xxx_messageInfo_PaymentMethodParams.Size(m)
}
func (m *PaymentMethodParams) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentMethodParams.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentMethodParams proto.InternalMessageInfo

func (m *PaymentMethodParams) GetHandler() string {
	if m != nil {
		return m.Handler
	}
	return ""
}

func (m *PaymentMethodParams) GetTerminal() string {
	if m != nil {
		return m.Terminal
	}
	return ""
}

func (m *PaymentMethodParams) GetExternalId() string {
	if m != nil {
		return m.ExternalId
	}
	return ""
}

func (m *PaymentMethodParams) GetOther() map[string]string {
	if m != nil {
		return m.Other
	}
	return nil
}

type PaymentMethodOrder struct {
	// @inject_tag: bson:"id,bsonobjectid"
	Id []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"id,bsonobjectid"`
	// @inject_tag: bson:"name"
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" bson:"name"`
	// @inject_tag: bson:"params"
	Params *PaymentMethodParams `protobuf:"bytes,3,opt,name=params,proto3" json:"params,omitempty" bson:"params"`
	// @inject_tag: bson:"payment_system"
	PaymentSystem *PaymentSystem `protobuf:"bytes,4,opt,name=payment_system,json=paymentSystem,proto3" json:"payment_system,omitempty" bson:"payment_system"`
	// @inject_tag: bson:"group_alias"
	GroupAlias           string   `protobuf:"bytes,5,opt,name=group_alias,json=groupAlias,proto3" json:"group_alias,omitempty" bson:"group_alias"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *PaymentMethodOrder) Reset()         { *m = PaymentMethodOrder{} }
func (m *PaymentMethodOrder) String() string { return proto.CompactTextString(m) }
func (*PaymentMethodOrder) ProtoMessage()    {}
func (*PaymentMethodOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_billing_aca9bda43472b59e, []int{12}
}
func (m *PaymentMethodOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentMethodOrder.Unmarshal(m, b)
}
func (m *PaymentMethodOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentMethodOrder.Marshal(b, m, deterministic)
}
func (dst *PaymentMethodOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentMethodOrder.Merge(dst, src)
}
func (m *PaymentMethodOrder) XXX_Size() int {
	return xxx_messageInfo_PaymentMethodOrder.Size(m)
}
func (m *PaymentMethodOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentMethodOrder.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentMethodOrder proto.InternalMessageInfo

func (m *PaymentMethodOrder) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *PaymentMethodOrder) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PaymentMethodOrder) GetParams() *PaymentMethodParams {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *PaymentMethodOrder) GetPaymentSystem() *PaymentSystem {
	if m != nil {
		return m.PaymentSystem
	}
	return nil
}

func (m *PaymentMethodOrder) GetGroupAlias() string {
	if m != nil {
		return m.GroupAlias
	}
	return ""
}

type PayerData struct {
	// @inject_tag: bson:"ip"
	Ip string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty" bson:"ip"`
	// @inject_tag: bson:"country_code_a2"
	CountryCodeA2 string `protobuf:"bytes,2,opt,name=country_code_a2,json=countryCodeA2,proto3" json:"country_code_a2,omitempty" bson:"country_code_a2"`
	// @inject_tag: bson:"country_name"
	CountryName *Name `protobuf:"bytes,3,opt,name=country_name,json=countryName,proto3" json:"country_name,omitempty" bson:"country_name"`
	// @inject_tag: bson:"city"
	City *Name `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty" bson:"city"`
	// @inject_tag: bson:"subdivision"
	Subdivision string `protobuf:"bytes,5,opt,name=subdivision,proto3" json:"subdivision,omitempty" bson:"subdivision"`
	// @inject_tag: bson:"timezone"
	Timezone string `protobuf:"bytes,6,opt,name=timezone,proto3" json:"timezone,omitempty" bson:"timezone"`
	// @inject_tag: bson:"phone"
	Phone string `protobuf:"bytes,7,opt,name=phone,proto3" json:"phone,omitempty" bson:"phone"`
	// @inject_tag: bson:"email"
	Email                string   `protobuf:"bytes,8,opt,name=email,proto3" json:"email,omitempty" bson:"email"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *PayerData) Reset()         { *m = PayerData{} }
func (m *PayerData) String() string { return proto.CompactTextString(m) }
func (*PayerData) ProtoMessage()    {}
func (*PayerData) Descriptor() ([]byte, []int) {
	return fileDescriptor_billing_aca9bda43472b59e, []int{13}
}
func (m *PayerData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayerData.Unmarshal(m, b)
}
func (m *PayerData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayerData.Marshal(b, m, deterministic)
}
func (dst *PayerData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayerData.Merge(dst, src)
}
func (m *PayerData) XXX_Size() int {
	return xxx_messageInfo_PayerData.Size(m)
}
func (m *PayerData) XXX_DiscardUnknown() {
	xxx_messageInfo_PayerData.DiscardUnknown(m)
}

var xxx_messageInfo_PayerData proto.InternalMessageInfo

func (m *PayerData) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *PayerData) GetCountryCodeA2() string {
	if m != nil {
		return m.CountryCodeA2
	}
	return ""
}

func (m *PayerData) GetCountryName() *Name {
	if m != nil {
		return m.CountryName
	}
	return nil
}

func (m *PayerData) GetCity() *Name {
	if m != nil {
		return m.City
	}
	return nil
}

func (m *PayerData) GetSubdivision() string {
	if m != nil {
		return m.Subdivision
	}
	return ""
}

func (m *PayerData) GetTimezone() string {
	if m != nil {
		return m.Timezone
	}
	return ""
}

func (m *PayerData) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *PayerData) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type OrderFee struct {
	// @inject_tag: bson:"amount_payment_method_currency"
	AmountPaymentMethodCurrency float64 `protobuf:"fixed64,1,opt,name=AmountPaymentMethodCurrency,proto3" json:"AmountPaymentMethodCurrency,omitempty" bson:"amount_payment_method_currency"`
	// @inject_tag: bson:"amount_merchant_currency"
	AmountMerchantCurrency float64  `protobuf:"fixed64,2,opt,name=AmountMerchantCurrency,proto3" json:"AmountMerchantCurrency,omitempty" bson:"amount_merchant_currency"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-" bson:"-"`
	XXX_unrecognized       []byte   `json:"-" bson:"-"`
	XXX_sizecache          int32    `json:"-" bson:"-"`
}

func (m *OrderFee) Reset()         { *m = OrderFee{} }
func (m *OrderFee) String() string { return proto.CompactTextString(m) }
func (*OrderFee) ProtoMessage()    {}
func (*OrderFee) Descriptor() ([]byte, []int) {
	return fileDescriptor_billing_aca9bda43472b59e, []int{14}
}
func (m *OrderFee) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderFee.Unmarshal(m, b)
}
func (m *OrderFee) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderFee.Marshal(b, m, deterministic)
}
func (dst *OrderFee) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderFee.Merge(dst, src)
}
func (m *OrderFee) XXX_Size() int {
	return xxx_messageInfo_OrderFee.Size(m)
}
func (m *OrderFee) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderFee.DiscardUnknown(m)
}

var xxx_messageInfo_OrderFee proto.InternalMessageInfo

func (m *OrderFee) GetAmountPaymentMethodCurrency() float64 {
	if m != nil {
		return m.AmountPaymentMethodCurrency
	}
	return 0
}

func (m *OrderFee) GetAmountMerchantCurrency() float64 {
	if m != nil {
		return m.AmountMerchantCurrency
	}
	return 0
}

type OrderFeePsp struct {
	// @inject_tag: bson:"amount_payment_method_currency"
	AmountPaymentMethodCurrency float64 `protobuf:"fixed64,1,opt,name=AmountPaymentMethodCurrency,proto3" json:"AmountPaymentMethodCurrency,omitempty" bson:"amount_payment_method_currency"`
	// @inject_tag: bson:"amount_merchant_currency"
	AmountMerchantCurrency float64 `protobuf:"fixed64,2,opt,name=AmountMerchantCurrency,proto3" json:"AmountMerchantCurrency,omitempty" bson:"amount_merchant_currency"`
	// @inject_tag: bson:"amount_psp_currency"
	AmountPspCurrency    float64  `protobuf:"fixed64,3,opt,name=AmountPspCurrency,proto3" json:"AmountPspCurrency,omitempty" bson:"amount_psp_currency"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *OrderFeePsp) Reset()         { *m = OrderFeePsp{} }
func (m *OrderFeePsp) String() string { return proto.CompactTextString(m) }
func (*OrderFeePsp) ProtoMessage()    {}
func (*OrderFeePsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_billing_aca9bda43472b59e, []int{15}
}
func (m *OrderFeePsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderFeePsp.Unmarshal(m, b)
}
func (m *OrderFeePsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderFeePsp.Marshal(b, m, deterministic)
}
func (dst *OrderFeePsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderFeePsp.Merge(dst, src)
}
func (m *OrderFeePsp) XXX_Size() int {
	return xxx_messageInfo_OrderFeePsp.Size(m)
}
func (m *OrderFeePsp) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderFeePsp.DiscardUnknown(m)
}

var xxx_messageInfo_OrderFeePsp proto.InternalMessageInfo

func (m *OrderFeePsp) GetAmountPaymentMethodCurrency() float64 {
	if m != nil {
		return m.AmountPaymentMethodCurrency
	}
	return 0
}

func (m *OrderFeePsp) GetAmountMerchantCurrency() float64 {
	if m != nil {
		return m.AmountMerchantCurrency
	}
	return 0
}

func (m *OrderFeePsp) GetAmountPspCurrency() float64 {
	if m != nil {
		return m.AmountPspCurrency
	}
	return 0
}

// Contain information about payment system commission in other currencies
type OrderFeePaymentSystem struct {
	// @inject_tag: bson:"amount_payment_method_currency"
	AmountPaymentMethodCurrency float64 `protobuf:"fixed64,1,opt,name=AmountPaymentMethodCurrency,proto3" json:"AmountPaymentMethodCurrency,omitempty" bson:"amount_payment_method_currency"`
	// @inject_tag: bson:"amount_merchant_currency"
	AmountMerchantCurrency float64 `protobuf:"fixed64,2,opt,name=AmountMerchantCurrency,proto3" json:"AmountMerchantCurrency,omitempty" bson:"amount_merchant_currency"`
	// @inject_tag: bson:"amount_payment_system_currency"
	AmountPaymentSystemCurrency float64  `protobuf:"fixed64,3,opt,name=AmountPaymentSystemCurrency,proto3" json:"AmountPaymentSystemCurrency,omitempty" bson:"amount_payment_system_currency"`
	XXX_NoUnkeyedLiteral        struct{} `json:"-" bson:"-"`
	XXX_unrecognized            []byte   `json:"-" bson:"-"`
	XXX_sizecache               int32    `json:"-" bson:"-"`
}

func (m *OrderFeePaymentSystem) Reset()         { *m = OrderFeePaymentSystem{} }
func (m *OrderFeePaymentSystem) String() string { return proto.CompactTextString(m) }
func (*OrderFeePaymentSystem) ProtoMessage()    {}
func (*OrderFeePaymentSystem) Descriptor() ([]byte, []int) {
	return fileDescriptor_billing_aca9bda43472b59e, []int{16}
}
func (m *OrderFeePaymentSystem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderFeePaymentSystem.Unmarshal(m, b)
}
func (m *OrderFeePaymentSystem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderFeePaymentSystem.Marshal(b, m, deterministic)
}
func (dst *OrderFeePaymentSystem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderFeePaymentSystem.Merge(dst, src)
}
func (m *OrderFeePaymentSystem) XXX_Size() int {
	return xxx_messageInfo_OrderFeePaymentSystem.Size(m)
}
func (m *OrderFeePaymentSystem) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderFeePaymentSystem.DiscardUnknown(m)
}

var xxx_messageInfo_OrderFeePaymentSystem proto.InternalMessageInfo

func (m *OrderFeePaymentSystem) GetAmountPaymentMethodCurrency() float64 {
	if m != nil {
		return m.AmountPaymentMethodCurrency
	}
	return 0
}

func (m *OrderFeePaymentSystem) GetAmountMerchantCurrency() float64 {
	if m != nil {
		return m.AmountMerchantCurrency
	}
	return 0
}

func (m *OrderFeePaymentSystem) GetAmountPaymentSystemCurrency() float64 {
	if m != nil {
		return m.AmountPaymentSystemCurrency
	}
	return 0
}

type Order struct {
	// @inject_tag: bson:"_id,bsonobjectid"
	Id []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"_id,bsonobjectid"`
	// @inject_tag: bson:"project"
	Project *ProjectOrder `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty" bson:"project"`
	// @inject_tag: bson:"project_order_id"
	ProjectOrderId string `protobuf:"bytes,3,opt,name=project_order_id,json=projectOrderId,proto3" json:"project_order_id,omitempty" bson:"project_order_id"`
	// @inject_tag: bson:"project_account"
	ProjectAccount string `protobuf:"bytes,4,opt,name=project_account,json=projectAccount,proto3" json:"project_account,omitempty" bson:"project_account"`
	// @inject_tag: bson:"description"
	Description string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty" bson:"description"`
	// @inject_tag: bson:"project_income_amount"
	ProjectIncomeAmount float64 `protobuf:"fixed64,6,opt,name=project_income_amount,json=projectIncomeAmount,proto3" json:"project_income_amount,omitempty" bson:"project_income_amount"`
	// @inject_tag: bson:"project_income_currency"
	ProjectIncomeCurrency *Currency `protobuf:"bytes,7,opt,name=project_income_currency,json=projectIncomeCurrency,proto3" json:"project_income_currency,omitempty" bson:"project_income_currency"`
	// @inject_tag: bson:"project_outcome_amount"
	ProjectOutcomeAmount float64 `protobuf:"fixed64,8,opt,name=project_outcome_amount,json=projectOutcomeAmount,proto3" json:"project_outcome_amount,omitempty" bson:"project_outcome_amount"`
	// @inject_tag: bson:"project_outcome_currency"
	ProjectOutcomeCurrency *Currency `protobuf:"bytes,9,opt,name=project_outcome_currency,json=projectOutcomeCurrency,proto3" json:"project_outcome_currency,omitempty" bson:"project_outcome_currency"`
	// @inject_tag: bson:"project_last_requested_at,timestamp"
	ProjectLastRequestedAt *timestamp.Timestamp `protobuf:"bytes,10,opt,name=project_last_requested_at,json=projectLastRequestedAt,proto3" json:"project_last_requested_at,omitempty" bson:"project_last_requested_at,timestamp"`
	// @inject_tag: bson:"project_params"
	ProjectParams map[string]string `protobuf:"bytes,11,rep,name=project_params,json=projectParams,proto3" json:"project_params,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3" bson:"project_params"`
	// @inject_tag: bson:"payer_data"
	PayerData *PayerData `protobuf:"bytes,12,opt,name=payer_data,json=payerData,proto3" json:"payer_data,omitempty" bson:"payer_data"`
	// @inject_tag: bson:"payment_method"
	PaymentMethod *PaymentMethodOrder `protobuf:"bytes,13,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty" bson:"payment_method"`
	// @inject_tag: bson:"pm_terminal_id"
	PaymentMethodTerminalId string `protobuf:"bytes,14,opt,name=payment_method_terminal_id,json=paymentMethodTerminalId,proto3" json:"payment_method_terminal_id,omitempty" bson:"pm_terminal_id"`
	// @inject_tag: bson:"pm_order_id"
	PaymentMethodOrderId string `protobuf:"bytes,15,opt,name=payment_method_order_id,json=paymentMethodOrderId,proto3" json:"payment_method_order_id,omitempty" bson:"pm_order_id"`
	// @inject_tag: bson:"pm_outcome_amount"
	PaymentMethodOutcomeAmount float64 `protobuf:"fixed64,16,opt,name=payment_method_outcome_amount,json=paymentMethodOutcomeAmount,proto3" json:"payment_method_outcome_amount,omitempty" bson:"pm_outcome_amount"`
	// @inject_tag: bson:"pm_outcome_currency"
	PaymentMethodOutcomeCurrency *Currency `protobuf:"bytes,17,opt,name=payment_method_outcome_currency,json=paymentMethodOutcomeCurrency,proto3" json:"payment_method_outcome_currency,omitempty" bson:"pm_outcome_currency"`
	// @inject_tag: bson:"pm_income_amount"
	PaymentMethodIncomeAmount float64 `protobuf:"fixed64,18,opt,name=payment_method_income_amount,json=paymentMethodIncomeAmount,proto3" json:"payment_method_income_amount,omitempty" bson:"pm_income_amount"`
	// @inject_tag: bson:"pm_income_currency"
	PaymentMethodIncomeCurrency *Currency `protobuf:"bytes,19,opt,name=payment_method_income_currency,json=paymentMethodIncomeCurrency,proto3" json:"payment_method_income_currency,omitempty" bson:"pm_income_currency"`
	// @inject_tag: bson:"-" json:"-"
	PaymentMethodIncomeCurrencyA3 string `protobuf:"bytes,20,opt,name=payment_method_income_currency_a3,json=paymentMethodIncomeCurrencyA3,proto3" json:"-" bson:"-"`
	// @inject_tag: bson:"pm_order_close_date,timestamp"
	PaymentMethodOrderClosedAt *timestamp.Timestamp `protobuf:"bytes,21,opt,name=payment_method_order_closed_at,json=paymentMethodOrderClosedAt,proto3" json:"payment_method_order_closed_at,omitempty" bson:"pm_order_close_date,timestamp"`
	// @inject_tag: bson:"status"
	Status int32 `protobuf:"varint,22,opt,name=status,proto3" json:"status,omitempty" bson:"status"`
	// @inject_tag: bson:"created_at,timestamp"
	CreatedAt *timestamp.Timestamp `protobuf:"bytes,23,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty" bson:"created_at,timestamp"`
	// @inject_tag: bson:"updated_at,timestamp"
	UpdatedAt *timestamp.Timestamp `protobuf:"bytes,24,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty" bson:"updated_at,timestamp"`
	// @inject_tag: bson:"created_by_json"
	IsJsonRequest bool `protobuf:"varint,25,opt,name=is_json_request,json=isJsonRequest,proto3" json:"is_json_request,omitempty" bson:"created_by_json"`
	// @inject_tag: bson:"amount_psp_ac"
	AmountInPspAccountingCurrency float64 `protobuf:"fixed64,26,opt,name=amount_in_psp_accounting_currency,json=amountInPspAccountingCurrency,proto3" json:"amount_in_psp_accounting_currency,omitempty" bson:"amount_psp_ac"`
	// @inject_tag: bson:"amount_in_merchant_ac"
	AmountInMerchantAccountingCurrency float64 `protobuf:"fixed64,27,opt,name=amount_in_merchant_accounting_currency,json=amountInMerchantAccountingCurrency,proto3" json:"amount_in_merchant_accounting_currency,omitempty" bson:"amount_in_merchant_ac"`
	// @inject_tag: bson:"amount_out_merchant_ac"
	AmountOutMerchantAccountingCurrency float64 `protobuf:"fixed64,28,opt,name=amount_out_merchant_accounting_currency,json=amountOutMerchantAccountingCurrency,proto3" json:"amount_out_merchant_accounting_currency,omitempty" bson:"amount_out_merchant_ac"`
	// @inject_tag: bson:"amount_ps_ac"
	AmountInPaymentSystemAccountingCurrency float64 `protobuf:"fixed64,29,opt,name=amount_in_payment_system_accounting_currency,json=amountInPaymentSystemAccountingCurrency,proto3" json:"amount_in_payment_system_accounting_currency,omitempty" bson:"amount_ps_ac"`
	// @inject_tag: bson:"pm_account"
	PaymentMethodPayerAccount string `protobuf:"bytes,30,opt,name=payment_method_payer_account,json=paymentMethodPayerAccount,proto3" json:"payment_method_payer_account,omitempty" bson:"pm_account"`
	// @inject_tag: bson:"pm_txn_params"
	PaymentMethodTxnParams map[string]string `protobuf:"bytes,31,rep,name=payment_method_txn_params,json=paymentMethodTxnParams,proto3" json:"payment_method_txn_params,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3" bson:"pm_txn_params"`
	// @inject_tag: bson:"fixed_package"
	FixedPackage *FixedPackage `protobuf:"bytes,32,opt,name=fixed_package,json=fixedPackage,proto3" json:"fixed_package,omitempty" bson:"fixed_package"`
	// @inject_tag: bson:"payment_requisites" json:"-"
	PaymentRequisites map[string]string `protobuf:"bytes,33,rep,name=payment_requisites,json=paymentRequisites,proto3" json:"-" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3" bson:"payment_requisites"`
	// @inject_tag: bson:"psp_fee_amount"
	PspFeeAmount *OrderFeePsp `protobuf:"bytes,34,opt,name=psp_fee_amount,json=pspFeeAmount,proto3" json:"psp_fee_amount,omitempty" bson:"psp_fee_amount"`
	// @inject_tag: bson:"project_fee_amount"
	ProjectFeeAmount *OrderFee `protobuf:"bytes,35,opt,name=project_fee_amount,json=projectFeeAmount,proto3" json:"project_fee_amount,omitempty" bson:"project_fee_amount"`
	// @inject_tag: bson:"to_payer_fee_amount"
	ToPayerFeeAmount *OrderFee `protobuf:"bytes,36,opt,name=to_payer_fee_amount,json=toPayerFeeAmount,proto3" json:"to_payer_fee_amount,omitempty" bson:"to_payer_fee_amount"`
	// @inject_tag: bson:"vat_amount"
	VatAmount float64 `protobuf:"fixed64,37,opt,name=vat_amount,json=vatAmount,proto3" json:"vat_amount,omitempty" bson:"vat_amount"`
	// @inject_tag: bson:"ps_fee_amount"
	PaymentSystemFeeAmount *OrderFeePaymentSystem `protobuf:"bytes,38,opt,name=payment_system_fee_amount,json=paymentSystemFeeAmount,proto3" json:"payment_system_fee_amount,omitempty" bson:"ps_fee_amount"`
	XXX_NoUnkeyedLiteral   struct{}               `json:"-" bson:"-"`
	XXX_unrecognized       []byte                 `json:"-" bson:"-"`
	XXX_sizecache          int32                  `json:"-" bson:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_billing_aca9bda43472b59e, []int{17}
}
func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (dst *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(dst, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Order) GetProject() *ProjectOrder {
	if m != nil {
		return m.Project
	}
	return nil
}

func (m *Order) GetProjectOrderId() string {
	if m != nil {
		return m.ProjectOrderId
	}
	return ""
}

func (m *Order) GetProjectAccount() string {
	if m != nil {
		return m.ProjectAccount
	}
	return ""
}

func (m *Order) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Order) GetProjectIncomeAmount() float64 {
	if m != nil {
		return m.ProjectIncomeAmount
	}
	return 0
}

func (m *Order) GetProjectIncomeCurrency() *Currency {
	if m != nil {
		return m.ProjectIncomeCurrency
	}
	return nil
}

func (m *Order) GetProjectOutcomeAmount() float64 {
	if m != nil {
		return m.ProjectOutcomeAmount
	}
	return 0
}

func (m *Order) GetProjectOutcomeCurrency() *Currency {
	if m != nil {
		return m.ProjectOutcomeCurrency
	}
	return nil
}

func (m *Order) GetProjectLastRequestedAt() *timestamp.Timestamp {
	if m != nil {
		return m.ProjectLastRequestedAt
	}
	return nil
}

func (m *Order) GetProjectParams() map[string]string {
	if m != nil {
		return m.ProjectParams
	}
	return nil
}

func (m *Order) GetPayerData() *PayerData {
	if m != nil {
		return m.PayerData
	}
	return nil
}

func (m *Order) GetPaymentMethod() *PaymentMethodOrder {
	if m != nil {
		return m.PaymentMethod
	}
	return nil
}

func (m *Order) GetPaymentMethodTerminalId() string {
	if m != nil {
		return m.PaymentMethodTerminalId
	}
	return ""
}

func (m *Order) GetPaymentMethodOrderId() string {
	if m != nil {
		return m.PaymentMethodOrderId
	}
	return ""
}

func (m *Order) GetPaymentMethodOutcomeAmount() float64 {
	if m != nil {
		return m.PaymentMethodOutcomeAmount
	}
	return 0
}

func (m *Order) GetPaymentMethodOutcomeCurrency() *Currency {
	if m != nil {
		return m.PaymentMethodOutcomeCurrency
	}
	return nil
}

func (m *Order) GetPaymentMethodIncomeAmount() float64 {
	if m != nil {
		return m.PaymentMethodIncomeAmount
	}
	return 0
}

func (m *Order) GetPaymentMethodIncomeCurrency() *Currency {
	if m != nil {
		return m.PaymentMethodIncomeCurrency
	}
	return nil
}

func (m *Order) GetPaymentMethodIncomeCurrencyA3() string {
	if m != nil {
		return m.PaymentMethodIncomeCurrencyA3
	}
	return ""
}

func (m *Order) GetPaymentMethodOrderClosedAt() *timestamp.Timestamp {
	if m != nil {
		return m.PaymentMethodOrderClosedAt
	}
	return nil
}

func (m *Order) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Order) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Order) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Order) GetIsJsonRequest() bool {
	if m != nil {
		return m.IsJsonRequest
	}
	return false
}

func (m *Order) GetAmountInPspAccountingCurrency() float64 {
	if m != nil {
		return m.AmountInPspAccountingCurrency
	}
	return 0
}

func (m *Order) GetAmountInMerchantAccountingCurrency() float64 {
	if m != nil {
		return m.AmountInMerchantAccountingCurrency
	}
	return 0
}

func (m *Order) GetAmountOutMerchantAccountingCurrency() float64 {
	if m != nil {
		return m.AmountOutMerchantAccountingCurrency
	}
	return 0
}

func (m *Order) GetAmountInPaymentSystemAccountingCurrency() float64 {
	if m != nil {
		return m.AmountInPaymentSystemAccountingCurrency
	}
	return 0
}

func (m *Order) GetPaymentMethodPayerAccount() string {
	if m != nil {
		return m.PaymentMethodPayerAccount
	}
	return ""
}

func (m *Order) GetPaymentMethodTxnParams() map[string]string {
	if m != nil {
		return m.PaymentMethodTxnParams
	}
	return nil
}

func (m *Order) GetFixedPackage() *FixedPackage {
	if m != nil {
		return m.FixedPackage
	}
	return nil
}

func (m *Order) GetPaymentRequisites() map[string]string {
	if m != nil {
		return m.PaymentRequisites
	}
	return nil
}

func (m *Order) GetPspFeeAmount() *OrderFeePsp {
	if m != nil {
		return m.PspFeeAmount
	}
	return nil
}

func (m *Order) GetProjectFeeAmount() *OrderFee {
	if m != nil {
		return m.ProjectFeeAmount
	}
	return nil
}

func (m *Order) GetToPayerFeeAmount() *OrderFee {
	if m != nil {
		return m.ToPayerFeeAmount
	}
	return nil
}

func (m *Order) GetVatAmount() float64 {
	if m != nil {
		return m.VatAmount
	}
	return 0
}

func (m *Order) GetPaymentSystemFeeAmount() *OrderFeePaymentSystem {
	if m != nil {
		return m.PaymentSystemFeeAmount
	}
	return nil
}

func init() {
	proto.RegisterType((*Name)(nil), "billing.Name")
	proto.RegisterType((*Country)(nil), "billing.Country")
	proto.RegisterType((*Currency)(nil), "billing.Currency")
	proto.RegisterType((*Merchant)(nil), "billing.Merchant")
	proto.RegisterType((*FixedPackage)(nil), "billing.FixedPackage")
	proto.RegisterType((*FixedPackages)(nil), "billing.FixedPackages")
	proto.RegisterType((*ProjectPaymentMethod)(nil), "billing.ProjectPaymentMethod")
	proto.RegisterType((*ProjectPaymentMethods)(nil), "billing.ProjectPaymentMethods")
	proto.RegisterType((*Project)(nil), "billing.Project")
	proto.RegisterMapType((map[string]*FixedPackages)(nil), "billing.Project.FixedPackageEntry")
	proto.RegisterMapType((map[string]*ProjectPaymentMethods)(nil), "billing.Project.PaymentMethodsEntry")
	proto.RegisterType((*ProjectOrder)(nil), "billing.ProjectOrder")
	proto.RegisterType((*PaymentSystem)(nil), "billing.PaymentSystem")
	proto.RegisterType((*PaymentMethodParams)(nil), "billing.PaymentMethodParams")
	proto.RegisterMapType((map[string]string)(nil), "billing.PaymentMethodParams.OtherEntry")
	proto.RegisterType((*PaymentMethodOrder)(nil), "billing.PaymentMethodOrder")
	proto.RegisterType((*PayerData)(nil), "billing.PayerData")
	proto.RegisterType((*OrderFee)(nil), "billing.OrderFee")
	proto.RegisterType((*OrderFeePsp)(nil), "billing.OrderFeePsp")
	proto.RegisterType((*OrderFeePaymentSystem)(nil), "billing.OrderFeePaymentSystem")
	proto.RegisterType((*Order)(nil), "billing.Order")
	proto.RegisterMapType((map[string]string)(nil), "billing.Order.PaymentMethodTxnParamsEntry")
	proto.RegisterMapType((map[string]string)(nil), "billing.Order.PaymentRequisitesEntry")
	proto.RegisterMapType((map[string]string)(nil), "billing.Order.ProjectParamsEntry")
}

func init() { proto.RegisterFile("billing/billing.proto", fileDescriptor_billing_aca9bda43472b59e) }

var fileDescriptor_billing_aca9bda43472b59e = []byte{
	// 2342 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x59, 0x4b, 0x73, 0x1b, 0xc7,
	0xf1, 0x2f, 0x80, 0x0f, 0x00, 0x0d, 0x80, 0x8f, 0xe1, 0x6b, 0x09, 0x92, 0x22, 0x05, 0xdb, 0x12,
	0x8b, 0x96, 0xc9, 0xff, 0x9f, 0x94, 0x53, 0x8e, 0x12, 0xd9, 0x82, 0x28, 0x29, 0x46, 0xf4, 0x62,
	0xad, 0x24, 0xe7, 0x51, 0xe5, 0x6c, 0x0d, 0x77, 0x87, 0xe4, 0x58, 0x8b, 0xdd, 0xcd, 0xce, 0x2c,
	0x23, 0xe4, 0x98, 0xca, 0x31, 0xe7, 0x7c, 0x8b, 0x1c, 0xf3, 0x35, 0x52, 0xa9, 0xca, 0x47, 0x70,
	0xe5, 0x1b, 0xe4, 0x94, 0x53, 0x6a, 0xe7, 0xb1, 0xd8, 0x17, 0x40, 0x51, 0x17, 0x27, 0x27, 0x62,
	0x7a, 0xba, 0x7f, 0xd3, 0x33, 0xdd, 0xfd, 0x9b, 0x9e, 0x25, 0xac, 0x9c, 0x52, 0xd7, 0xa5, 0xde,
	0xf9, 0x81, 0xfa, 0xbb, 0x1f, 0x84, 0x3e, 0xf7, 0x51, 0x4d, 0x0d, 0x3b, 0xdb, 0xe7, 0xbe, 0x7f,
	0xee, 0x92, 0x03, 0x21, 0x3e, 0x8d, 0xce, 0x0e, 0x38, 0x1d, 0x10, 0xc6, 0xf1, 0x20, 0x90, 0x9a,
	0xdd, 0x5b, 0x30, 0xfd, 0x02, 0x0f, 0x08, 0x9a, 0x83, 0x2a, 0xf1, 0x8c, 0xca, 0x4e, 0x65, 0xb7,
	0x61, 0x56, 0x89, 0x17, 0x8f, 0xc3, 0xc8, 0xa8, 0xca, 0x71, 0x18, 0x75, 0xff, 0x54, 0x85, 0xda,
	0xb1, 0x1f, 0x79, 0x3c, 0x1c, 0xa2, 0x75, 0xa8, 0xdb, 0xbe, 0x43, 0x2c, 0xea, 0x71, 0x61, 0x31,
	0x63, 0xd6, 0xe2, 0x71, 0xdf, 0xe3, 0x68, 0x0d, 0xc4, 0x4f, 0x0b, 0x1f, 0x2a, 0xdb, 0xd9, 0x78,
	0xd8, 0x3b, 0x1c, 0x4d, 0x1c, 0x19, 0x53, 0xa9, 0x89, 0x23, 0x74, 0x13, 0xa6, 0x3d, 0x3c, 0x20,
	0xc6, 0xf4, 0x4e, 0x65, 0xb7, 0x79, 0xd8, 0xde, 0xd7, 0x1b, 0x89, 0xbd, 0x32, 0xc5, 0x14, 0xda,
	0x80, 0x06, 0x65, 0x16, 0xb6, 0x39, 0xbd, 0x24, 0xc6, 0xcc, 0x4e, 0x65, 0xb7, 0x6e, 0xd6, 0x29,
	0xeb, 0x89, 0x31, 0xfa, 0x31, 0x80, 0x1d, 0x12, 0xcc, 0x89, 0x63, 0x61, 0x6e, 0xcc, 0x0a, 0x94,
	0xce, 0xbe, 0xdc, 0xf6, 0xbe, 0xde, 0xf6, 0xfe, 0x6b, 0xbd, 0x6d, 0xb3, 0xa1, 0xb4, 0x7b, 0x3c,
	0x36, 0x8d, 0x02, 0x47, 0x9b, 0xd6, 0xae, 0x36, 0x55, 0xda, 0x3d, 0xde, 0xfd, 0x57, 0x05, 0xea,
	0xc7, 0x51, 0x18, 0x12, 0xcf, 0x7e, 0xbf, 0xf3, 0x38, 0xca, 0x9c, 0xc7, 0xff, 0xea, 0xb6, 0xbf,
	0x9f, 0x82, 0xfa, 0x73, 0x12, 0xda, 0x17, 0xd8, 0xe3, 0x71, 0x8a, 0x50, 0x47, 0x6c, 0xb8, 0x65,
	0x56, 0xa9, 0x83, 0xb6, 0xa1, 0x49, 0xde, 0x71, 0x12, 0x7a, 0xd8, 0xb5, 0xa8, 0xa3, 0xf6, 0x0b,
	0x5a, 0xd4, 0x77, 0xd0, 0x32, 0xcc, 0x90, 0x01, 0xa6, 0xae, 0xca, 0x00, 0x39, 0x40, 0x28, 0x75,
	0x12, 0x0d, 0xb5, 0xf5, 0xbd, 0xf8, 0xd8, 0x44, 0xb2, 0x89, 0x8d, 0x37, 0x0f, 0x17, 0x92, 0x03,
	0x52, 0x49, 0x68, 0x6a, 0x05, 0xf4, 0x29, 0x2c, 0x62, 0x5b, 0x0c, 0xa8, 0x77, 0x6e, 0x05, 0x24,
	0xa4, 0xbe, 0x23, 0x0e, 0xa4, 0x61, 0x2e, 0x8c, 0x26, 0x4e, 0x84, 0x1c, 0x7d, 0x06, 0x75, 0x5b,
	0x85, 0x4d, 0xed, 0x7c, 0x71, 0x84, 0xac, 0x26, 0xcc, 0x44, 0x05, 0x7d, 0x0c, 0x73, 0x94, 0x59,
	0x97, 0x98, 0x5b, 0xc4, 0xc3, 0xa7, 0x2e, 0x71, 0x8c, 0xba, 0x88, 0x43, 0x8b, 0xb2, 0x6f, 0x30,
	0x7f, 0x2c, 0x65, 0xe8, 0x01, 0x6c, 0x51, 0x66, 0xd9, 0xfe, 0x60, 0x40, 0x19, 0xa3, 0xbe, 0x67,
	0x71, 0xdf, 0x8a, 0x18, 0x09, 0x13, 0xa3, 0x86, 0x30, 0x5a, 0xa7, 0xec, 0x38, 0xd1, 0x79, 0xed,
	0xbf, 0x61, 0x24, 0xd4, 0x08, 0xab, 0x30, 0xcb, 0x38, 0xe6, 0x11, 0x33, 0x40, 0xe4, 0x8f, 0x1a,
	0xe5, 0xa2, 0xdc, 0xfc, 0xf0, 0x28, 0xb7, 0xae, 0x13, 0xe5, 0xbf, 0x54, 0xa1, 0xf5, 0x84, 0xbe,
	0x23, 0xce, 0x09, 0xb6, 0xdf, 0xe2, 0x73, 0x92, 0x8a, 0x74, 0x43, 0x44, 0x5a, 0x87, 0xac, 0x9a,
	0x0a, 0xd9, 0x4d, 0x68, 0xe9, 0x63, 0x13, 0x85, 0x30, 0x25, 0x36, 0xd2, 0xd4, 0xb2, 0xb8, 0x18,
	0x96, 0x61, 0x26, 0x08, 0xa9, 0x2d, 0x43, 0x5d, 0x31, 0xe5, 0xe0, 0xbf, 0x30, 0xcd, 0x33, 0x59,
	0x52, 0xbf, 0x32, 0x4b, 0xba, 0x4f, 0xa1, 0x9d, 0x3e, 0x2e, 0x86, 0xee, 0x41, 0xfb, 0x2c, 0x16,
	0x58, 0x81, 0x94, 0x18, 0x95, 0x9d, 0xa9, 0xdd, 0xe6, 0xe1, 0x4a, 0x02, 0x92, 0x56, 0x37, 0x5b,
	0x67, 0xa9, 0x51, 0xf7, 0x5b, 0x58, 0x3e, 0x09, 0xfd, 0xef, 0x88, 0xcd, 0x4f, 0xf0, 0x70, 0x40,
	0x3c, 0xfe, 0x9c, 0xf0, 0x0b, 0xdf, 0x29, 0xc4, 0xe0, 0x73, 0xa8, 0x63, 0xc7, 0x91, 0x9b, 0xab,
	0x5e, 0xb9, 0xb9, 0x9a, 0xd0, 0xed, 0xf1, 0xae, 0x05, 0x2b, 0x65, 0xf0, 0x0c, 0x3d, 0x81, 0xf9,
	0x40, 0x4a, 0xac, 0x81, 0x14, 0x29, 0xaf, 0xb7, 0x12, 0xaf, 0xcb, 0x0c, 0xcd, 0xb9, 0x20, 0x83,
	0xd3, 0xfd, 0x3b, 0x40, 0x4d, 0x29, 0x16, 0x18, 0xe2, 0x4b, 0x58, 0xb4, 0xb1, 0xeb, 0x9e, 0x62,
	0xfb, 0xad, 0x95, 0x1c, 0x70, 0x75, 0xdc, 0x01, 0x2f, 0x68, 0xdd, 0x84, 0x68, 0x3f, 0x4d, 0xd9,
	0x8b, 0x4d, 0xda, 0xbe, 0x26, 0x93, 0x44, 0xf9, 0x44, 0xc9, 0xd1, 0x7d, 0xd8, 0x90, 0xc9, 0x60,
	0x51, 0xef, 0xd2, 0xa7, 0x36, 0xb1, 0xb0, 0xeb, 0xfa, 0xbf, 0x23, 0x8e, 0x15, 0x85, 0x2e, 0x33,
	0xa6, 0x77, 0xa6, 0x76, 0x1b, 0xa6, 0x21, 0x55, 0xfa, 0x52, 0xa3, 0x27, 0x15, 0xde, 0x84, 0x2e,
	0x8b, 0x73, 0x60, 0xa0, 0x98, 0x4e, 0x71, 0xd0, 0xc8, 0x45, 0x4d, 0x81, 0x66, 0xa2, 0x82, 0xbe,
	0x84, 0xcd, 0x38, 0x8b, 0x63, 0x00, 0xcb, 0x19, 0x7a, 0x78, 0x40, 0x6d, 0xcb, 0xf3, 0x39, 0x3d,
	0x1b, 0xca, 0xe5, 0x66, 0x45, 0x62, 0x1b, 0x94, 0x89, 0x35, 0x1e, 0x49, 0x8d, 0x17, 0x42, 0x41,
	0x2c, 0xf7, 0x10, 0x6e, 0x14, 0xec, 0x43, 0xe2, 0xd0, 0x90, 0xd8, 0x5c, 0x22, 0xd4, 0x04, 0x42,
	0x27, 0x8b, 0x60, 0x2a, 0x15, 0x81, 0x71, 0x0f, 0xe6, 0x5d, 0x3a, 0xa0, 0x9c, 0x59, 0x57, 0x67,
	0xef, 0x9c, 0xd4, 0x4c, 0x8e, 0x76, 0x0f, 0x16, 0x9e, 0xe3, 0x77, 0x2a, 0xb4, 0xbd, 0x41, 0xcc,
	0x9a, 0x82, 0xb6, 0x2a, 0x66, 0x41, 0x2e, 0x74, 0xa9, 0x97, 0xd5, 0x05, 0xa5, 0x9b, 0x93, 0xc7,
	0x54, 0x11, 0x5f, 0x69, 0x82, 0xbb, 0x1a, 0xa6, 0xec, 0x35, 0xba, 0xd0, 0x92, 0x3b, 0x7f, 0x1c,
	0x5f, 0x00, 0xcc, 0x68, 0x89, 0x50, 0x64, 0x64, 0xf1, 0x1a, 0x2f, 0x3d, 0x77, 0x28, 0x0a, 0x45,
	0x42, 0x31, 0xa3, 0x2d, 0x4e, 0xa0, 0x20, 0x47, 0x9b, 0xd0, 0x78, 0x45, 0xec, 0x90, 0xf0, 0xa7,
	0x64, 0x68, 0xcc, 0x89, 0x85, 0x46, 0x02, 0xb4, 0x0b, 0xf3, 0xaf, 0x88, 0xe7, 0xa4, 0xd0, 0x8d,
	0x79, 0x01, 0x94, 0x17, 0xc7, 0x9a, 0x6f, 0xcc, 0x67, 0xc7, 0x17, 0xc4, 0x7e, 0xdb, 0x93, 0x17,
	0x87, 0xb1, 0x20, 0xd0, 0xf2, 0x62, 0x74, 0x07, 0x16, 0xdf, 0x98, 0xcf, 0x4e, 0x42, 0xdf, 0x26,
	0x8c, 0xa9, 0x0d, 0x1b, 0x8b, 0x42, 0xb7, 0x38, 0xa1, 0x70, 0x75, 0xa8, 0x9e, 0xc4, 0x1e, 0xa0,
	0x04, 0x37, 0x2d, 0x46, 0xfb, 0x80, 0x52, 0xa2, 0x57, 0x91, 0x1d, 0xc3, 0x18, 0x4b, 0x42, 0xb9,
	0x64, 0x06, 0xfd, 0x2c, 0x4f, 0x34, 0x6b, 0xa2, 0x64, 0xbb, 0xf9, 0x92, 0xcd, 0x10, 0xce, 0x63,
	0x71, 0x7f, 0x66, 0x58, 0x07, 0x3d, 0x2f, 0x56, 0xbf, 0x21, 0xa0, 0x3e, 0x2e, 0x40, 0x65, 0x79,
	0x43, 0x82, 0xe5, 0x48, 0x00, 0x75, 0xa0, 0xde, 0x57, 0x14, 0x6e, 0x2c, 0x4b, 0x4a, 0xef, 0x97,
	0x53, 0xfa, 0xca, 0x87, 0x53, 0xfa, 0xea, 0x35, 0x28, 0xbd, 0xf3, 0x0b, 0x58, 0x2c, 0x9c, 0x01,
	0x5a, 0x80, 0xa9, 0xb7, 0x64, 0xa8, 0x48, 0x35, 0xfe, 0x89, 0xee, 0xc0, 0xcc, 0x25, 0x76, 0x23,
	0xa2, 0x58, 0x69, 0xb5, 0x94, 0xb1, 0x99, 0x29, 0x95, 0xee, 0x55, 0xbf, 0xa8, 0x74, 0x30, 0x2c,
	0x95, 0x9c, 0x48, 0x09, 0xf4, 0xdd, 0x2c, 0xf4, 0x8d, 0x89, 0xb4, 0x9a, 0x5e, 0xa2, 0xfb, 0xe7,
	0x29, 0x68, 0x29, 0xa5, 0x97, 0xa1, 0x43, 0xc2, 0x02, 0xaf, 0x96, 0xdd, 0xc7, 0xdb, 0xd0, 0x8c,
	0x42, 0xd7, 0x62, 0x2a, 0x87, 0x24, 0x4b, 0x42, 0x14, 0xba, 0x3a, 0x77, 0xd6, 0xa1, 0x1e, 0x2b,
	0x9c, 0xc5, 0xe9, 0x28, 0x7b, 0xaf, 0x5a, 0x14, 0xba, 0x22, 0x0d, 0x3f, 0x82, 0xb6, 0xe2, 0x2e,
	0x22, 0x2b, 0x74, 0x46, 0x56, 0xa8, 0x97, 0xae, 0xd0, 0x2d, 0x00, 0x26, 0x8a, 0xcc, 0x8a, 0x37,
	0x2a, 0x1b, 0xae, 0x06, 0x4b, 0xca, 0x6e, 0x0f, 0x16, 0x19, 0xf1, 0x1c, 0x2b, 0x0d, 0xa4, 0x38,
	0x6c, 0x9e, 0xe5, 0x0a, 0x6f, 0x0f, 0x16, 0x63, 0x57, 0xec, 0xb8, 0xc4, 0x2c, 0xd5, 0xb3, 0x09,
	0xea, 0x6a, 0x98, 0xf3, 0x51, 0xe8, 0x66, 0x4a, 0x6f, 0x1f, 0x96, 0x62, 0xdd, 0x40, 0x96, 0x98,
	0xa5, 0x12, 0x4f, 0x70, 0x55, 0xc3, 0x8c, 0x61, 0x72, 0xc5, 0x57, 0x7a, 0x67, 0xc0, 0x98, 0x3b,
	0x23, 0x4d, 0xfa, 0xcd, 0x2b, 0x49, 0xbf, 0xfb, 0x7d, 0x15, 0xda, 0x6a, 0x9d, 0x57, 0x43, 0xc6,
	0xc9, 0xe0, 0xbd, 0x22, 0xb3, 0x97, 0xbc, 0xa4, 0x44, 0x54, 0x4a, 0x9b, 0x5b, 0xfd, 0xd4, 0x7a,
	0x08, 0x4b, 0xa9, 0xe6, 0x36, 0xa1, 0xf5, 0xe9, 0x71, 0xb4, 0x8e, 0x46, 0xda, 0xe9, 0x5b, 0xb3,
	0xd8, 0x20, 0xcf, 0x8c, 0x69, 0x90, 0x33, 0xdd, 0xd8, 0xec, 0xc4, 0x6e, 0xac, 0xf6, 0xe1, 0xa5,
	0x5b, 0xbf, 0x4e, 0x3b, 0xfa, 0xcf, 0x4a, 0xae, 0xc4, 0x4e, 0x70, 0x88, 0x07, 0x0c, 0x19, 0x50,
	0xbb, 0xc0, 0x9e, 0xe3, 0x92, 0x50, 0x95, 0x99, 0x1e, 0xc6, 0xf4, 0xc3, 0x49, 0x38, 0xa0, 0x1e,
	0x76, 0xd5, 0xc9, 0x27, 0xe3, 0xfc, 0x2b, 0x65, 0xaa, 0xf0, 0x4a, 0xb9, 0x0f, 0x33, 0x3e, 0xbf,
	0x20, 0xa1, 0xe8, 0x10, 0x9a, 0x87, 0xb7, 0x47, 0x75, 0x5a, 0xf4, 0x61, 0xff, 0x65, 0xac, 0x29,
	0x39, 0x50, 0x5a, 0x75, 0xbe, 0x00, 0x18, 0x09, 0x4b, 0x68, 0x60, 0x39, 0x4d, 0x03, 0x8d, 0x74,
	0x99, 0xff, 0xad, 0x02, 0x28, 0xb3, 0xc6, 0xfb, 0x17, 0xfb, 0x5d, 0x98, 0x0d, 0x84, 0x43, 0x2a,
	0xa3, 0x36, 0x27, 0x39, 0x6d, 0x2a, 0x5d, 0x74, 0x1f, 0x34, 0x6f, 0x5b, 0x4c, 0xa4, 0xaf, 0xca,
	0xab, 0xd5, 0xbc, 0xb5, 0x4c, 0x6e, 0xb3, 0x1d, 0x64, 0x72, 0x7d, 0x1b, 0x9a, 0xe7, 0xa1, 0x1f,
	0x05, 0x16, 0x76, 0x29, 0x66, 0x2a, 0xa3, 0x40, 0x88, 0x7a, 0xb1, 0xa4, 0xfb, 0x87, 0x2a, 0x34,
	0x4e, 0xf0, 0x90, 0x84, 0x8f, 0x30, 0xc7, 0x62, 0x1f, 0x41, 0xd2, 0xc0, 0x06, 0xe8, 0x16, 0xcc,
	0xab, 0x27, 0x9c, 0x95, 0xfd, 0x64, 0xd0, 0x56, 0xe2, 0x63, 0xf9, 0xe5, 0xe0, 0xff, 0xa0, 0xa5,
	0xf5, 0xc4, 0xbe, 0xa7, 0xca, 0x5e, 0xcc, 0x4d, 0xa5, 0xf2, 0x42, 0x3e, 0x45, 0xa6, 0x6d, 0xca,
	0x87, 0x63, 0xde, 0xd6, 0xf1, 0x14, 0xda, 0x81, 0x26, 0x8b, 0x4e, 0x1d, 0x7a, 0x49, 0xe3, 0xc7,
	0x98, 0xf2, 0x3d, 0x2d, 0x12, 0x39, 0x44, 0x07, 0xe4, 0xf7, 0xbe, 0x47, 0x14, 0xb9, 0x25, 0x63,
	0xf1, 0x90, 0xb9, 0x88, 0x27, 0x6a, 0x32, 0x86, 0x62, 0x30, 0x7a, 0xde, 0xd6, 0x53, 0xcf, 0xdb,
	0xee, 0x1f, 0x2b, 0x50, 0x17, 0x81, 0x7c, 0x42, 0x08, 0x7a, 0x00, 0x1b, 0xb2, 0x69, 0xc9, 0x84,
	0x45, 0x57, 0xaa, 0x38, 0x9c, 0x8a, 0x39, 0x49, 0x05, 0xfd, 0x08, 0x56, 0xe5, 0xb4, 0xa6, 0xa3,
	0xe3, 0x74, 0x1f, 0x5d, 0x31, 0xc7, 0xcc, 0x76, 0xff, 0x5a, 0x81, 0xa6, 0x76, 0xe3, 0x84, 0x05,
	0x3f, 0x9c, 0x27, 0x71, 0xef, 0xa4, 0x60, 0x59, 0x90, 0x98, 0x4c, 0x09, 0x93, 0xe2, 0x44, 0xf7,
	0x1f, 0x15, 0x58, 0x49, 0xfc, 0xce, 0xa4, 0xdf, 0x0f, 0xb7, 0x83, 0xfc, 0xca, 0xd2, 0xa1, 0xdc,
	0x5e, 0x26, 0xa9, 0x74, 0xff, 0xbd, 0x0c, 0x33, 0xe5, 0xd5, 0x7d, 0x00, 0xb5, 0x40, 0x5e, 0xf5,
	0xaa, 0x4f, 0x58, 0xc9, 0xf7, 0x09, 0xc2, 0xce, 0xd4, 0x5a, 0x68, 0x17, 0x16, 0xd4, 0x4f, 0xcb,
	0x8f, 0x67, 0x46, 0xa4, 0x36, 0x17, 0xa4, 0x0c, 0xfa, 0x0e, 0xba, 0x0d, 0xf3, 0x5a, 0x53, 0xdf,
	0xb1, 0xd3, 0x19, 0x45, 0x7d, 0xc5, 0xee, 0x40, 0xd3, 0x21, 0xcc, 0x0e, 0x69, 0xc0, 0x53, 0xc5,
	0x91, 0x12, 0xa1, 0x43, 0x58, 0xd1, 0x50, 0xd4, 0xb3, 0xfd, 0x01, 0xb1, 0xb0, 0x7c, 0x06, 0xcc,
	0x8a, 0xbd, 0x2f, 0xa9, 0xc9, 0xbe, 0x98, 0x53, 0x2f, 0x81, 0x3e, 0xac, 0xe5, 0x6c, 0xae, 0xfe,
	0x12, 0xb3, 0x92, 0x01, 0x4a, 0x02, 0x70, 0x17, 0x56, 0x93, 0x3d, 0x47, 0x3c, 0xbd, 0x7e, 0x5d,
	0xac, 0xbf, 0xac, 0x77, 0x2e, 0x27, 0x95, 0x03, 0x4f, 0xc1, 0xc8, 0x5b, 0x25, 0x1e, 0x34, 0xc6,
	0x79, 0xb0, 0x9a, 0x85, 0x4a, 0x5c, 0x78, 0x03, 0xeb, 0x1a, 0xcc, 0xc5, 0x8c, 0x5b, 0x21, 0xf9,
	0x6d, 0x44, 0x98, 0xba, 0xde, 0xe0, 0xca, 0xeb, 0x4d, 0xc3, 0x3e, 0xc3, 0x8c, 0x9b, 0xda, 0xb4,
	0xc7, 0xd1, 0xd7, 0xa0, 0x83, 0x61, 0x29, 0x42, 0x6f, 0x8a, 0x5b, 0xe8, 0x66, 0xe2, 0x99, 0x88,
	0xe6, 0xa8, 0x67, 0x8c, 0x75, 0xe4, 0xfd, 0xd3, 0x0e, 0xd2, 0x32, 0xf4, 0xff, 0x00, 0x41, 0xcc,
	0xbd, 0x96, 0x83, 0x39, 0x56, 0xdf, 0x7f, 0x50, 0x9a, 0xd8, 0x25, 0x2d, 0x9b, 0x8d, 0x20, 0x61,
	0xe8, 0x87, 0xa3, 0xfb, 0x40, 0x3e, 0x02, 0xc4, 0x8b, 0xab, 0x79, 0xb8, 0x51, 0x7e, 0x9b, 0xc8,
	0x44, 0x6c, 0x67, 0x5a, 0x7f, 0xf4, 0x13, 0xe8, 0x64, 0x31, 0x2c, 0x7d, 0xf3, 0xc6, 0x89, 0x29,
	0x1f, 0x67, 0x6b, 0x19, 0x93, 0xd7, 0x6a, 0xbe, 0xef, 0xa0, 0xcf, 0x61, 0x2d, 0x67, 0x9c, 0xa4,
	0xf4, 0xbc, 0xb0, 0x5c, 0x0e, 0x0a, 0x0e, 0xf4, 0x1d, 0xd4, 0x83, 0xad, 0xbc, 0x59, 0x36, 0x2b,
	0x16, 0x44, 0x56, 0x74, 0xb2, 0xc6, 0x99, 0xdc, 0xf8, 0x25, 0x6c, 0x8f, 0x81, 0x48, 0x52, 0x64,
	0x71, 0x5c, 0x8a, 0x6c, 0x96, 0xe1, 0x26, 0x89, 0xf2, 0x15, 0x6c, 0xe6, 0x90, 0xb3, 0x15, 0x83,
	0x84, 0x6f, 0xeb, 0x19, 0x8c, 0x4c, 0xdd, 0x7c, 0x03, 0x37, 0xca, 0x01, 0x12, 0xcf, 0x96, 0xc6,
	0x79, 0xb6, 0x51, 0x82, 0x9a, 0x38, 0xf6, 0x35, 0xdc, 0x9c, 0x8c, 0x6b, 0xe1, 0x23, 0xf1, 0x78,
	0x6b, 0x98, 0x5b, 0x13, 0x70, 0x7a, 0x47, 0xe8, 0x37, 0x05, 0x0f, 0x65, 0xd8, 0x6c, 0xd7, 0x67,
	0xef, 0xfb, 0xca, 0xeb, 0x14, 0x23, 0x7b, 0x2c, 0xcc, 0x7b, 0x3c, 0xf5, 0x75, 0x74, 0x75, 0xc2,
	0xd7, 0xd1, 0xb5, 0x0f, 0x6f, 0x47, 0x8d, 0xeb, 0x7c, 0x1c, 0xbc, 0x05, 0xf3, 0x94, 0x59, 0xdf,
	0x31, 0xdf, 0xd3, 0x45, 0x6f, 0xac, 0x8b, 0x3e, 0xb9, 0x4d, 0xd9, 0xcf, 0x99, 0xef, 0xa9, 0x72,
	0x8e, 0xcf, 0x57, 0x86, 0xd8, 0xa2, 0x9e, 0x15, 0xb0, 0xc0, 0x2a, 0x6b, 0xe4, 0x3b, 0x22, 0xfa,
	0x5b, 0x52, 0xb1, 0xef, 0x9d, 0xb0, 0xa0, 0x57, 0x6c, 0xe0, 0x4d, 0xb8, 0x35, 0x42, 0xd2, 0x8f,
	0x8f, 0x52, 0xb8, 0x0d, 0x01, 0xd7, 0xd5, 0x70, 0xfa, 0xe6, 0x2a, 0xc1, 0x7c, 0x0d, 0xb7, 0x15,
	0xa6, 0x1f, 0xf1, 0xc9, 0xa0, 0x9b, 0x02, 0xf4, 0x23, 0xa9, 0xfe, 0x32, 0xe2, 0x13, 0x50, 0xbf,
	0x85, 0x3b, 0xa9, 0x3d, 0x67, 0x7a, 0xcb, 0x52, 0xe8, 0x2d, 0x01, 0x7d, 0x3b, 0xd9, 0x7e, 0xfa,
	0xb2, 0x2c, 0x81, 0x2f, 0xd6, 0x92, 0xa4, 0x38, 0x7d, 0x9d, 0xdd, 0x10, 0xd9, 0x9a, 0xad, 0x25,
	0xc1, 0x74, 0xfa, 0x66, 0x23, 0xb0, 0x9e, 0x67, 0xa7, 0x77, 0x9e, 0x66, 0xda, 0x6d, 0xc1, 0xb4,
	0x7b, 0x79, 0xa6, 0xcd, 0x70, 0xd5, 0x3b, 0x2f, 0x4d, 0xb9, 0xab, 0x41, 0xe9, 0x64, 0xf1, 0xfb,
	0xef, 0x4e, 0xee, 0x2a, 0x1f, 0xff, 0xfd, 0x17, 0xbd, 0x06, 0xa4, 0x5d, 0x8c, 0xd3, 0x8b, 0x32,
	0xca, 0x09, 0x33, 0x6e, 0x0a, 0xdf, 0x3e, 0x29, 0xf7, 0xcd, 0x4c, 0xf4, 0xa4, 0x5b, 0x8b, 0x41,
	0x5e, 0x8e, 0xee, 0xc1, 0x5c, 0x9c, 0x82, 0x67, 0x24, 0xe1, 0x9d, 0xae, 0x70, 0x69, 0x39, 0x8b,
	0x28, 0x9b, 0x43, 0xb3, 0x15, 0xb0, 0xe0, 0x09, 0xd1, 0x04, 0xf4, 0x15, 0x20, 0x7d, 0x27, 0xa5,
	0xec, 0x3f, 0xca, 0x91, 0x8e, 0xb6, 0x37, 0x75, 0x3b, 0x32, 0x02, 0x78, 0x00, 0x4b, 0xdc, 0x57,
	0xa1, 0x4a, 0x21, 0x7c, 0x3c, 0x16, 0x81, 0xfb, 0x22, 0x6a, 0x23, 0x84, 0x2d, 0x80, 0x4b, 0xcc,
	0xb5, 0xe1, 0x27, 0x22, 0x6b, 0x1a, 0x97, 0x58, 0x7f, 0x64, 0xfc, 0xd5, 0x28, 0xac, 0x2a, 0xd9,
	0x52, 0xcb, 0xdc, 0xca, 0x7d, 0x6e, 0x29, 0xed, 0x26, 0x93, 0x50, 0xca, 0x61, 0xb2, 0x72, 0xe7,
	0x01, 0xa0, 0xe2, 0x5d, 0x7b, 0x9d, 0x67, 0x5d, 0xa7, 0x0f, 0x1b, 0x13, 0x72, 0xe8, 0x5a, 0x50,
	0x8f, 0x60, 0xb5, 0x3c, 0xe4, 0xd7, 0x41, 0x79, 0xf8, 0xd3, 0x5f, 0xdf, 0x3b, 0xa7, 0xfc, 0x22,
	0x3a, 0xdd, 0xb7, 0xfd, 0xc1, 0x81, 0xfe, 0xf6, 0xf1, 0xf2, 0xc5, 0xe3, 0x83, 0x00, 0x0f, 0x7d,
	0x8f, 0x7c, 0x16, 0x92, 0xc0, 0x67, 0x94, 0xfb, 0xe1, 0xf0, 0x20, 0x78, 0x7b, 0x2e, 0xff, 0x77,
	0xac, 0xff, 0xc1, 0x7c, 0x3a, 0x2b, 0x86, 0x47, 0xff, 0x09, 0x00, 0x00, 0xff, 0xff, 0x6c, 0x1f,
	0x16, 0xff, 0x7a, 0x1e, 0x00, 0x00,
}
