// Code generated by protoc-gen-go. DO NOT EDIT.
// source: billing/xsolla.proto

package billing // import "github.com/ProtocolONE/payone-repository/pkg/proto/billing"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type XSollaUser struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Ip                   string   `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Phone                string   `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Name                 string   `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Country              string   `protobuf:"bytes,6,opt,name=country,proto3" json:"country,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *XSollaUser) Reset()         { *m = XSollaUser{} }
func (m *XSollaUser) String() string { return proto.CompactTextString(m) }
func (*XSollaUser) ProtoMessage()    {}
func (*XSollaUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_xsolla_2b415e5388c2a386, []int{0}
}
func (m *XSollaUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XSollaUser.Unmarshal(m, b)
}
func (m *XSollaUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XSollaUser.Marshal(b, m, deterministic)
}
func (dst *XSollaUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XSollaUser.Merge(dst, src)
}
func (m *XSollaUser) XXX_Size() int {
	return xxx_messageInfo_XSollaUser.Size(m)
}
func (m *XSollaUser) XXX_DiscardUnknown() {
	xxx_messageInfo_XSollaUser.DiscardUnknown(m)
}

var xxx_messageInfo_XSollaUser proto.InternalMessageInfo

func (m *XSollaUser) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *XSollaUser) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *XSollaUser) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *XSollaUser) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *XSollaUser) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *XSollaUser) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

type XSollaVirtualCurrency struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Sku                  string   `protobuf:"bytes,2,opt,name=sku,proto3" json:"sku,omitempty"`
	Quantity             int32    `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Currency             string   `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Amount               float64  `protobuf:"fixed64,5,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *XSollaVirtualCurrency) Reset()         { *m = XSollaVirtualCurrency{} }
func (m *XSollaVirtualCurrency) String() string { return proto.CompactTextString(m) }
func (*XSollaVirtualCurrency) ProtoMessage()    {}
func (*XSollaVirtualCurrency) Descriptor() ([]byte, []int) {
	return fileDescriptor_xsolla_2b415e5388c2a386, []int{1}
}
func (m *XSollaVirtualCurrency) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XSollaVirtualCurrency.Unmarshal(m, b)
}
func (m *XSollaVirtualCurrency) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XSollaVirtualCurrency.Marshal(b, m, deterministic)
}
func (dst *XSollaVirtualCurrency) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XSollaVirtualCurrency.Merge(dst, src)
}
func (m *XSollaVirtualCurrency) XXX_Size() int {
	return xxx_messageInfo_XSollaVirtualCurrency.Size(m)
}
func (m *XSollaVirtualCurrency) XXX_DiscardUnknown() {
	xxx_messageInfo_XSollaVirtualCurrency.DiscardUnknown(m)
}

var xxx_messageInfo_XSollaVirtualCurrency proto.InternalMessageInfo

func (m *XSollaVirtualCurrency) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *XSollaVirtualCurrency) GetSku() string {
	if m != nil {
		return m.Sku
	}
	return ""
}

func (m *XSollaVirtualCurrency) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *XSollaVirtualCurrency) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *XSollaVirtualCurrency) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type XSollaPurchase struct {
	VirtualCurrency      *XSollaVirtualCurrency `protobuf:"bytes,1,opt,name=virtual_currency,json=virtualCurrency,proto3" json:"virtual_currency,omitempty"`
	Checkout             *XSollaCheckout        `protobuf:"bytes,2,opt,name=checkout,proto3" json:"checkout,omitempty"`
	VirtualItems         *XSollaVirtualItems    `protobuf:"bytes,3,opt,name=virtual_items,json=virtualItems,proto3" json:"virtual_items,omitempty"`
	Total                *XSollaTotal           `protobuf:"bytes,4,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *XSollaPurchase) Reset()         { *m = XSollaPurchase{} }
func (m *XSollaPurchase) String() string { return proto.CompactTextString(m) }
func (*XSollaPurchase) ProtoMessage()    {}
func (*XSollaPurchase) Descriptor() ([]byte, []int) {
	return fileDescriptor_xsolla_2b415e5388c2a386, []int{2}
}
func (m *XSollaPurchase) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XSollaPurchase.Unmarshal(m, b)
}
func (m *XSollaPurchase) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XSollaPurchase.Marshal(b, m, deterministic)
}
func (dst *XSollaPurchase) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XSollaPurchase.Merge(dst, src)
}
func (m *XSollaPurchase) XXX_Size() int {
	return xxx_messageInfo_XSollaPurchase.Size(m)
}
func (m *XSollaPurchase) XXX_DiscardUnknown() {
	xxx_messageInfo_XSollaPurchase.DiscardUnknown(m)
}

var xxx_messageInfo_XSollaPurchase proto.InternalMessageInfo

func (m *XSollaPurchase) GetVirtualCurrency() *XSollaVirtualCurrency {
	if m != nil {
		return m.VirtualCurrency
	}
	return nil
}

func (m *XSollaPurchase) GetCheckout() *XSollaCheckout {
	if m != nil {
		return m.Checkout
	}
	return nil
}

func (m *XSollaPurchase) GetVirtualItems() *XSollaVirtualItems {
	if m != nil {
		return m.VirtualItems
	}
	return nil
}

func (m *XSollaPurchase) GetTotal() *XSollaTotal {
	if m != nil {
		return m.Total
	}
	return nil
}

type XSollaCheckout struct {
	Currency             string   `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	Amount               float64  `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *XSollaCheckout) Reset()         { *m = XSollaCheckout{} }
func (m *XSollaCheckout) String() string { return proto.CompactTextString(m) }
func (*XSollaCheckout) ProtoMessage()    {}
func (*XSollaCheckout) Descriptor() ([]byte, []int) {
	return fileDescriptor_xsolla_2b415e5388c2a386, []int{3}
}
func (m *XSollaCheckout) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XSollaCheckout.Unmarshal(m, b)
}
func (m *XSollaCheckout) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XSollaCheckout.Marshal(b, m, deterministic)
}
func (dst *XSollaCheckout) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XSollaCheckout.Merge(dst, src)
}
func (m *XSollaCheckout) XXX_Size() int {
	return xxx_messageInfo_XSollaCheckout.Size(m)
}
func (m *XSollaCheckout) XXX_DiscardUnknown() {
	xxx_messageInfo_XSollaCheckout.DiscardUnknown(m)
}

var xxx_messageInfo_XSollaCheckout proto.InternalMessageInfo

func (m *XSollaCheckout) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *XSollaCheckout) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type XSollaItem struct {
	Sku                  string   `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Amount               float64  `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *XSollaItem) Reset()         { *m = XSollaItem{} }
func (m *XSollaItem) String() string { return proto.CompactTextString(m) }
func (*XSollaItem) ProtoMessage()    {}
func (*XSollaItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_xsolla_2b415e5388c2a386, []int{4}
}
func (m *XSollaItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XSollaItem.Unmarshal(m, b)
}
func (m *XSollaItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XSollaItem.Marshal(b, m, deterministic)
}
func (dst *XSollaItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XSollaItem.Merge(dst, src)
}
func (m *XSollaItem) XXX_Size() int {
	return xxx_messageInfo_XSollaItem.Size(m)
}
func (m *XSollaItem) XXX_DiscardUnknown() {
	xxx_messageInfo_XSollaItem.DiscardUnknown(m)
}

var xxx_messageInfo_XSollaItem proto.InternalMessageInfo

func (m *XSollaItem) GetSku() string {
	if m != nil {
		return m.Sku
	}
	return ""
}

func (m *XSollaItem) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type XSollaVirtualItems struct {
	Items                []*XSollaItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Currency             string        `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	Amount               float64       `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *XSollaVirtualItems) Reset()         { *m = XSollaVirtualItems{} }
func (m *XSollaVirtualItems) String() string { return proto.CompactTextString(m) }
func (*XSollaVirtualItems) ProtoMessage()    {}
func (*XSollaVirtualItems) Descriptor() ([]byte, []int) {
	return fileDescriptor_xsolla_2b415e5388c2a386, []int{5}
}
func (m *XSollaVirtualItems) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XSollaVirtualItems.Unmarshal(m, b)
}
func (m *XSollaVirtualItems) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XSollaVirtualItems.Marshal(b, m, deterministic)
}
func (dst *XSollaVirtualItems) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XSollaVirtualItems.Merge(dst, src)
}
func (m *XSollaVirtualItems) XXX_Size() int {
	return xxx_messageInfo_XSollaVirtualItems.Size(m)
}
func (m *XSollaVirtualItems) XXX_DiscardUnknown() {
	xxx_messageInfo_XSollaVirtualItems.DiscardUnknown(m)
}

var xxx_messageInfo_XSollaVirtualItems proto.InternalMessageInfo

func (m *XSollaVirtualItems) GetItems() []*XSollaItem {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *XSollaVirtualItems) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *XSollaVirtualItems) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type XSollaTotal struct {
	Currency             string   `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	Amount               float64  `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *XSollaTotal) Reset()         { *m = XSollaTotal{} }
func (m *XSollaTotal) String() string { return proto.CompactTextString(m) }
func (*XSollaTotal) ProtoMessage()    {}
func (*XSollaTotal) Descriptor() ([]byte, []int) {
	return fileDescriptor_xsolla_2b415e5388c2a386, []int{6}
}
func (m *XSollaTotal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XSollaTotal.Unmarshal(m, b)
}
func (m *XSollaTotal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XSollaTotal.Marshal(b, m, deterministic)
}
func (dst *XSollaTotal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XSollaTotal.Merge(dst, src)
}
func (m *XSollaTotal) XXX_Size() int {
	return xxx_messageInfo_XSollaTotal.Size(m)
}
func (m *XSollaTotal) XXX_DiscardUnknown() {
	xxx_messageInfo_XSollaTotal.DiscardUnknown(m)
}

var xxx_messageInfo_XSollaTotal proto.InternalMessageInfo

func (m *XSollaTotal) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *XSollaTotal) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type XSollaCheckNotification struct {
	NotificationType     string      `protobuf:"bytes,1,opt,name=notification_type,json=notificationType,proto3" json:"notification_type,omitempty"`
	User                 *XSollaUser `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *XSollaCheckNotification) Reset()         { *m = XSollaCheckNotification{} }
func (m *XSollaCheckNotification) String() string { return proto.CompactTextString(m) }
func (*XSollaCheckNotification) ProtoMessage()    {}
func (*XSollaCheckNotification) Descriptor() ([]byte, []int) {
	return fileDescriptor_xsolla_2b415e5388c2a386, []int{7}
}
func (m *XSollaCheckNotification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XSollaCheckNotification.Unmarshal(m, b)
}
func (m *XSollaCheckNotification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XSollaCheckNotification.Marshal(b, m, deterministic)
}
func (dst *XSollaCheckNotification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XSollaCheckNotification.Merge(dst, src)
}
func (m *XSollaCheckNotification) XXX_Size() int {
	return xxx_messageInfo_XSollaCheckNotification.Size(m)
}
func (m *XSollaCheckNotification) XXX_DiscardUnknown() {
	xxx_messageInfo_XSollaCheckNotification.DiscardUnknown(m)
}

var xxx_messageInfo_XSollaCheckNotification proto.InternalMessageInfo

func (m *XSollaCheckNotification) GetNotificationType() string {
	if m != nil {
		return m.NotificationType
	}
	return ""
}

func (m *XSollaCheckNotification) GetUser() *XSollaUser {
	if m != nil {
		return m.User
	}
	return nil
}

type XSollaTransaction struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ExternalId           string   `protobuf:"bytes,2,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	PaymentDate          string   `protobuf:"bytes,3,opt,name=payment_date,json=paymentDate,proto3" json:"payment_date,omitempty"`
	PaymentMethod        string   `protobuf:"bytes,4,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	DryRun               int32    `protobuf:"varint,5,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *XSollaTransaction) Reset()         { *m = XSollaTransaction{} }
func (m *XSollaTransaction) String() string { return proto.CompactTextString(m) }
func (*XSollaTransaction) ProtoMessage()    {}
func (*XSollaTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_xsolla_2b415e5388c2a386, []int{8}
}
func (m *XSollaTransaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XSollaTransaction.Unmarshal(m, b)
}
func (m *XSollaTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XSollaTransaction.Marshal(b, m, deterministic)
}
func (dst *XSollaTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XSollaTransaction.Merge(dst, src)
}
func (m *XSollaTransaction) XXX_Size() int {
	return xxx_messageInfo_XSollaTransaction.Size(m)
}
func (m *XSollaTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_XSollaTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_XSollaTransaction proto.InternalMessageInfo

func (m *XSollaTransaction) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *XSollaTransaction) GetExternalId() string {
	if m != nil {
		return m.ExternalId
	}
	return ""
}

func (m *XSollaTransaction) GetPaymentDate() string {
	if m != nil {
		return m.PaymentDate
	}
	return ""
}

func (m *XSollaTransaction) GetPaymentMethod() string {
	if m != nil {
		return m.PaymentMethod
	}
	return ""
}

func (m *XSollaTransaction) GetDryRun() int32 {
	if m != nil {
		return m.DryRun
	}
	return 0
}

type XSollaPayment struct {
	Currency             string   `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	Amount               float64  `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *XSollaPayment) Reset()         { *m = XSollaPayment{} }
func (m *XSollaPayment) String() string { return proto.CompactTextString(m) }
func (*XSollaPayment) ProtoMessage()    {}
func (*XSollaPayment) Descriptor() ([]byte, []int) {
	return fileDescriptor_xsolla_2b415e5388c2a386, []int{9}
}
func (m *XSollaPayment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XSollaPayment.Unmarshal(m, b)
}
func (m *XSollaPayment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XSollaPayment.Marshal(b, m, deterministic)
}
func (dst *XSollaPayment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XSollaPayment.Merge(dst, src)
}
func (m *XSollaPayment) XXX_Size() int {
	return xxx_messageInfo_XSollaPayment.Size(m)
}
func (m *XSollaPayment) XXX_DiscardUnknown() {
	xxx_messageInfo_XSollaPayment.DiscardUnknown(m)
}

var xxx_messageInfo_XSollaPayment proto.InternalMessageInfo

func (m *XSollaPayment) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *XSollaPayment) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type XSollaVat struct {
	Currency             string   `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	Amount               float64  `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *XSollaVat) Reset()         { *m = XSollaVat{} }
func (m *XSollaVat) String() string { return proto.CompactTextString(m) }
func (*XSollaVat) ProtoMessage()    {}
func (*XSollaVat) Descriptor() ([]byte, []int) {
	return fileDescriptor_xsolla_2b415e5388c2a386, []int{10}
}
func (m *XSollaVat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XSollaVat.Unmarshal(m, b)
}
func (m *XSollaVat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XSollaVat.Marshal(b, m, deterministic)
}
func (dst *XSollaVat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XSollaVat.Merge(dst, src)
}
func (m *XSollaVat) XXX_Size() int {
	return xxx_messageInfo_XSollaVat.Size(m)
}
func (m *XSollaVat) XXX_DiscardUnknown() {
	xxx_messageInfo_XSollaVat.DiscardUnknown(m)
}

var xxx_messageInfo_XSollaVat proto.InternalMessageInfo

func (m *XSollaVat) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *XSollaVat) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type XSollaPayout struct {
	Currency             string   `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	Amount               float64  `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *XSollaPayout) Reset()         { *m = XSollaPayout{} }
func (m *XSollaPayout) String() string { return proto.CompactTextString(m) }
func (*XSollaPayout) ProtoMessage()    {}
func (*XSollaPayout) Descriptor() ([]byte, []int) {
	return fileDescriptor_xsolla_2b415e5388c2a386, []int{11}
}
func (m *XSollaPayout) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XSollaPayout.Unmarshal(m, b)
}
func (m *XSollaPayout) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XSollaPayout.Marshal(b, m, deterministic)
}
func (dst *XSollaPayout) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XSollaPayout.Merge(dst, src)
}
func (m *XSollaPayout) XXX_Size() int {
	return xxx_messageInfo_XSollaPayout.Size(m)
}
func (m *XSollaPayout) XXX_DiscardUnknown() {
	xxx_messageInfo_XSollaPayout.DiscardUnknown(m)
}

var xxx_messageInfo_XSollaPayout proto.InternalMessageInfo

func (m *XSollaPayout) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *XSollaPayout) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type XSollaXsollaFee struct {
	Currency             string   `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	Amount               float64  `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *XSollaXsollaFee) Reset()         { *m = XSollaXsollaFee{} }
func (m *XSollaXsollaFee) String() string { return proto.CompactTextString(m) }
func (*XSollaXsollaFee) ProtoMessage()    {}
func (*XSollaXsollaFee) Descriptor() ([]byte, []int) {
	return fileDescriptor_xsolla_2b415e5388c2a386, []int{12}
}
func (m *XSollaXsollaFee) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XSollaXsollaFee.Unmarshal(m, b)
}
func (m *XSollaXsollaFee) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XSollaXsollaFee.Marshal(b, m, deterministic)
}
func (dst *XSollaXsollaFee) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XSollaXsollaFee.Merge(dst, src)
}
func (m *XSollaXsollaFee) XXX_Size() int {
	return xxx_messageInfo_XSollaXsollaFee.Size(m)
}
func (m *XSollaXsollaFee) XXX_DiscardUnknown() {
	xxx_messageInfo_XSollaXsollaFee.DiscardUnknown(m)
}

var xxx_messageInfo_XSollaXsollaFee proto.InternalMessageInfo

func (m *XSollaXsollaFee) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *XSollaXsollaFee) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type XSollaPaymentMethodFee struct {
	Currency             string   `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	Amount               float64  `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *XSollaPaymentMethodFee) Reset()         { *m = XSollaPaymentMethodFee{} }
func (m *XSollaPaymentMethodFee) String() string { return proto.CompactTextString(m) }
func (*XSollaPaymentMethodFee) ProtoMessage()    {}
func (*XSollaPaymentMethodFee) Descriptor() ([]byte, []int) {
	return fileDescriptor_xsolla_2b415e5388c2a386, []int{13}
}
func (m *XSollaPaymentMethodFee) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XSollaPaymentMethodFee.Unmarshal(m, b)
}
func (m *XSollaPaymentMethodFee) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XSollaPaymentMethodFee.Marshal(b, m, deterministic)
}
func (dst *XSollaPaymentMethodFee) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XSollaPaymentMethodFee.Merge(dst, src)
}
func (m *XSollaPaymentMethodFee) XXX_Size() int {
	return xxx_messageInfo_XSollaPaymentMethodFee.Size(m)
}
func (m *XSollaPaymentMethodFee) XXX_DiscardUnknown() {
	xxx_messageInfo_XSollaPaymentMethodFee.DiscardUnknown(m)
}

var xxx_messageInfo_XSollaPaymentMethodFee proto.InternalMessageInfo

func (m *XSollaPaymentMethodFee) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *XSollaPaymentMethodFee) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type XSollaRepatriationCommission struct {
	Currency             string   `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	Amount               float64  `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *XSollaRepatriationCommission) Reset()         { *m = XSollaRepatriationCommission{} }
func (m *XSollaRepatriationCommission) String() string { return proto.CompactTextString(m) }
func (*XSollaRepatriationCommission) ProtoMessage()    {}
func (*XSollaRepatriationCommission) Descriptor() ([]byte, []int) {
	return fileDescriptor_xsolla_2b415e5388c2a386, []int{14}
}
func (m *XSollaRepatriationCommission) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XSollaRepatriationCommission.Unmarshal(m, b)
}
func (m *XSollaRepatriationCommission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XSollaRepatriationCommission.Marshal(b, m, deterministic)
}
func (dst *XSollaRepatriationCommission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XSollaRepatriationCommission.Merge(dst, src)
}
func (m *XSollaRepatriationCommission) XXX_Size() int {
	return xxx_messageInfo_XSollaRepatriationCommission.Size(m)
}
func (m *XSollaRepatriationCommission) XXX_DiscardUnknown() {
	xxx_messageInfo_XSollaRepatriationCommission.DiscardUnknown(m)
}

var xxx_messageInfo_XSollaRepatriationCommission proto.InternalMessageInfo

func (m *XSollaRepatriationCommission) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *XSollaRepatriationCommission) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type XSollaPaymentDetails struct {
	Payment                *XSollaPayment                `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"`
	Vat                    *XSollaVat                    `protobuf:"bytes,2,opt,name=vat,proto3" json:"vat,omitempty"`
	PayoutCurrencyRate     float64                       `protobuf:"fixed64,3,opt,name=payout_currency_rate,json=payoutCurrencyRate,proto3" json:"payout_currency_rate,omitempty"`
	Payout                 *XSollaPayout                 `protobuf:"bytes,4,opt,name=payout,proto3" json:"payout,omitempty"`
	XsollaFee              *XSollaXsollaFee              `protobuf:"bytes,5,opt,name=xsolla_fee,json=xsollaFee,proto3" json:"xsolla_fee,omitempty"`
	PaymentMethodFee       *XSollaPaymentMethodFee       `protobuf:"bytes,6,opt,name=payment_method_fee,json=paymentMethodFee,proto3" json:"payment_method_fee,omitempty"`
	RepatriationCommission *XSollaRepatriationCommission `protobuf:"bytes,7,opt,name=repatriation_commission,json=repatriationCommission,proto3" json:"repatriation_commission,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}                      `json:"-"`
	XXX_unrecognized       []byte                        `json:"-"`
	XXX_sizecache          int32                         `json:"-"`
}

func (m *XSollaPaymentDetails) Reset()         { *m = XSollaPaymentDetails{} }
func (m *XSollaPaymentDetails) String() string { return proto.CompactTextString(m) }
func (*XSollaPaymentDetails) ProtoMessage()    {}
func (*XSollaPaymentDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_xsolla_2b415e5388c2a386, []int{15}
}
func (m *XSollaPaymentDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XSollaPaymentDetails.Unmarshal(m, b)
}
func (m *XSollaPaymentDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XSollaPaymentDetails.Marshal(b, m, deterministic)
}
func (dst *XSollaPaymentDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XSollaPaymentDetails.Merge(dst, src)
}
func (m *XSollaPaymentDetails) XXX_Size() int {
	return xxx_messageInfo_XSollaPaymentDetails.Size(m)
}
func (m *XSollaPaymentDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_XSollaPaymentDetails.DiscardUnknown(m)
}

var xxx_messageInfo_XSollaPaymentDetails proto.InternalMessageInfo

func (m *XSollaPaymentDetails) GetPayment() *XSollaPayment {
	if m != nil {
		return m.Payment
	}
	return nil
}

func (m *XSollaPaymentDetails) GetVat() *XSollaVat {
	if m != nil {
		return m.Vat
	}
	return nil
}

func (m *XSollaPaymentDetails) GetPayoutCurrencyRate() float64 {
	if m != nil {
		return m.PayoutCurrencyRate
	}
	return 0
}

func (m *XSollaPaymentDetails) GetPayout() *XSollaPayout {
	if m != nil {
		return m.Payout
	}
	return nil
}

func (m *XSollaPaymentDetails) GetXsollaFee() *XSollaXsollaFee {
	if m != nil {
		return m.XsollaFee
	}
	return nil
}

func (m *XSollaPaymentDetails) GetPaymentMethodFee() *XSollaPaymentMethodFee {
	if m != nil {
		return m.PaymentMethodFee
	}
	return nil
}

func (m *XSollaPaymentDetails) GetRepatriationCommission() *XSollaRepatriationCommission {
	if m != nil {
		return m.RepatriationCommission
	}
	return nil
}

type XSollaPaymentNotification struct {
	NotificationType     string                `protobuf:"bytes,1,opt,name=notification_type,json=notificationType,proto3" json:"notification_type,omitempty"`
	Purchase             *XSollaPurchase       `protobuf:"bytes,2,opt,name=purchase,proto3" json:"purchase,omitempty"`
	User                 *XSollaUser           `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Transaction          *XSollaTransaction    `protobuf:"bytes,4,opt,name=transaction,proto3" json:"transaction,omitempty"`
	PaymentDetails       *XSollaPaymentDetails `protobuf:"bytes,5,opt,name=payment_details,json=paymentDetails,proto3" json:"payment_details,omitempty"`
	CustomParameters     map[string]string     `protobuf:"bytes,6,rep,name=custom_parameters,json=customParameters,proto3" json:"custom_parameters,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *XSollaPaymentNotification) Reset()         { *m = XSollaPaymentNotification{} }
func (m *XSollaPaymentNotification) String() string { return proto.CompactTextString(m) }
func (*XSollaPaymentNotification) ProtoMessage()    {}
func (*XSollaPaymentNotification) Descriptor() ([]byte, []int) {
	return fileDescriptor_xsolla_2b415e5388c2a386, []int{16}
}
func (m *XSollaPaymentNotification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XSollaPaymentNotification.Unmarshal(m, b)
}
func (m *XSollaPaymentNotification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XSollaPaymentNotification.Marshal(b, m, deterministic)
}
func (dst *XSollaPaymentNotification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XSollaPaymentNotification.Merge(dst, src)
}
func (m *XSollaPaymentNotification) XXX_Size() int {
	return xxx_messageInfo_XSollaPaymentNotification.Size(m)
}
func (m *XSollaPaymentNotification) XXX_DiscardUnknown() {
	xxx_messageInfo_XSollaPaymentNotification.DiscardUnknown(m)
}

var xxx_messageInfo_XSollaPaymentNotification proto.InternalMessageInfo

func (m *XSollaPaymentNotification) GetNotificationType() string {
	if m != nil {
		return m.NotificationType
	}
	return ""
}

func (m *XSollaPaymentNotification) GetPurchase() *XSollaPurchase {
	if m != nil {
		return m.Purchase
	}
	return nil
}

func (m *XSollaPaymentNotification) GetUser() *XSollaUser {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *XSollaPaymentNotification) GetTransaction() *XSollaTransaction {
	if m != nil {
		return m.Transaction
	}
	return nil
}

func (m *XSollaPaymentNotification) GetPaymentDetails() *XSollaPaymentDetails {
	if m != nil {
		return m.PaymentDetails
	}
	return nil
}

func (m *XSollaPaymentNotification) GetCustomParameters() map[string]string {
	if m != nil {
		return m.CustomParameters
	}
	return nil
}

func init() {
	proto.RegisterType((*XSollaUser)(nil), "billing.XSollaUser")
	proto.RegisterType((*XSollaVirtualCurrency)(nil), "billing.XSollaVirtualCurrency")
	proto.RegisterType((*XSollaPurchase)(nil), "billing.XSollaPurchase")
	proto.RegisterType((*XSollaCheckout)(nil), "billing.XSollaCheckout")
	proto.RegisterType((*XSollaItem)(nil), "billing.XSollaItem")
	proto.RegisterType((*XSollaVirtualItems)(nil), "billing.XSollaVirtualItems")
	proto.RegisterType((*XSollaTotal)(nil), "billing.XSollaTotal")
	proto.RegisterType((*XSollaCheckNotification)(nil), "billing.XSollaCheckNotification")
	proto.RegisterType((*XSollaTransaction)(nil), "billing.XSollaTransaction")
	proto.RegisterType((*XSollaPayment)(nil), "billing.XSollaPayment")
	proto.RegisterType((*XSollaVat)(nil), "billing.XSollaVat")
	proto.RegisterType((*XSollaPayout)(nil), "billing.XSollaPayout")
	proto.RegisterType((*XSollaXsollaFee)(nil), "billing.XSollaXsollaFee")
	proto.RegisterType((*XSollaPaymentMethodFee)(nil), "billing.XSollaPaymentMethodFee")
	proto.RegisterType((*XSollaRepatriationCommission)(nil), "billing.XSollaRepatriationCommission")
	proto.RegisterType((*XSollaPaymentDetails)(nil), "billing.XSollaPaymentDetails")
	proto.RegisterType((*XSollaPaymentNotification)(nil), "billing.XSollaPaymentNotification")
	proto.RegisterMapType((map[string]string)(nil), "billing.XSollaPaymentNotification.CustomParametersEntry")
}

func init() { proto.RegisterFile("billing/xsolla.proto", fileDescriptor_xsolla_2b415e5388c2a386) }

var fileDescriptor_xsolla_2b415e5388c2a386 = []byte{
	// 925 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0xdb, 0x6e, 0xdb, 0x46,
	0x10, 0x05, 0x25, 0x4b, 0xb2, 0x87, 0xbe, 0xc8, 0x5b, 0xd9, 0x66, 0xdd, 0x4b, 0x52, 0xa1, 0x41,
	0xd3, 0x16, 0x91, 0x02, 0x19, 0x68, 0x83, 0x20, 0x40, 0xdb, 0xc8, 0x0e, 0x60, 0xa0, 0x49, 0x8d,
	0x6d, 0x5a, 0x04, 0x7d, 0xa8, 0xb0, 0xa6, 0x36, 0x16, 0x61, 0x92, 0xcb, 0x2e, 0x97, 0x82, 0xf9,
	0x03, 0x7d, 0xeb, 0x77, 0xf4, 0x13, 0xfa, 0x2b, 0xfd, 0x9a, 0xa2, 0xd8, 0xab, 0x29, 0x46, 0x46,
	0x00, 0xbe, 0x71, 0x66, 0x67, 0x0f, 0xcf, 0xcc, 0x9c, 0x9d, 0x5d, 0x18, 0x5c, 0x46, 0x71, 0x1c,
	0xa5, 0x57, 0xe3, 0x9b, 0x9c, 0xc5, 0x31, 0x19, 0x65, 0x9c, 0x09, 0x86, 0x7a, 0xc6, 0x3b, 0xfc,
	0xd3, 0x03, 0x78, 0xf3, 0xb3, 0x5c, 0xf9, 0x25, 0xa7, 0x1c, 0xed, 0x42, 0x2b, 0x9a, 0x07, 0xde,
	0x7d, 0xef, 0xe1, 0x16, 0x6e, 0x45, 0x73, 0x65, 0x67, 0x41, 0xcb, 0xd8, 0x19, 0x1a, 0x40, 0x27,
	0x5b, 0xb0, 0x94, 0x06, 0x6d, 0xe5, 0xd2, 0x86, 0xf4, 0xd2, 0x84, 0x44, 0x71, 0xb0, 0xa1, 0xbd,
	0xca, 0x40, 0x08, 0x36, 0x52, 0x92, 0xd0, 0xa0, 0xa3, 0x9c, 0xea, 0x1b, 0x05, 0xd0, 0x0b, 0x59,
	0x91, 0x0a, 0x5e, 0x06, 0x5d, 0xe5, 0xb6, 0xe6, 0xf0, 0x2f, 0x0f, 0x0e, 0x34, 0x91, 0x5f, 0x23,
	0x2e, 0x0a, 0x12, 0x4f, 0x0b, 0xce, 0x69, 0x1a, 0x96, 0x0e, 0xc7, 0xab, 0xe0, 0xf4, 0xa1, 0x9d,
	0x5f, 0x17, 0x86, 0x98, 0xfc, 0x44, 0xc7, 0xb0, 0xf9, 0x47, 0x41, 0x52, 0x11, 0x89, 0x52, 0x91,
	0xeb, 0x60, 0x67, 0xcb, 0xb5, 0xd0, 0xa0, 0x19, 0x8a, 0xce, 0x46, 0x87, 0xd0, 0x25, 0x89, 0xe4,
	0xa0, 0x78, 0x7a, 0xd8, 0x58, 0xc3, 0xff, 0x3c, 0xd8, 0xd5, 0x7c, 0x2e, 0x0a, 0x1e, 0x2e, 0x48,
	0x4e, 0xd1, 0x39, 0xf4, 0x97, 0x9a, 0xdb, 0xcc, 0xc1, 0x49, 0x52, 0xfe, 0xe4, 0xd3, 0x91, 0xa9,
	0xe7, 0x68, 0x6d, 0x0a, 0x78, 0x6f, 0x59, 0xcb, 0xe9, 0x04, 0x36, 0xc3, 0x05, 0x0d, 0xaf, 0x59,
	0x21, 0x54, 0x12, 0xfe, 0xe4, 0xa8, 0x06, 0x31, 0x35, 0xcb, 0xd8, 0x05, 0xa2, 0xef, 0x61, 0xc7,
	0xfe, 0x3f, 0x12, 0x34, 0xc9, 0x55, 0x9e, 0xfe, 0xe4, 0xa3, 0xf5, 0x3f, 0x3f, 0x97, 0x21, 0x78,
	0x7b, 0x59, 0xb1, 0xd0, 0x57, 0xd0, 0x11, 0x4c, 0x10, 0xdd, 0x28, 0x7f, 0x32, 0xa8, 0xed, 0x7c,
	0x2d, 0xd7, 0xb0, 0x0e, 0x19, 0x9e, 0xda, 0xfc, 0x2d, 0x93, 0x95, 0x32, 0x7a, 0x77, 0x96, 0xb1,
	0xb5, 0x52, 0xc6, 0x6f, 0xac, 0xbc, 0x24, 0x01, 0xdb, 0x36, 0xef, 0xb6, 0x6d, 0x77, 0xed, 0xcb,
	0x01, 0xbd, 0x9b, 0x0d, 0xfa, 0x12, 0x3a, 0x3a, 0x73, 0xef, 0x7e, 0xfb, 0xa1, 0x3f, 0xf9, 0xa0,
	0xc6, 0x5f, 0x06, 0x61, 0x1d, 0xb1, 0x42, 0xb6, 0x75, 0x27, 0xd9, 0xf6, 0xca, 0x4f, 0x7f, 0x00,
	0xbf, 0x52, 0x88, 0x46, 0xf9, 0x32, 0x38, 0xaa, 0x54, 0xed, 0x15, 0x13, 0xd1, 0xdb, 0x28, 0x24,
	0x22, 0x62, 0x29, 0xfa, 0x1a, 0xf6, 0xd3, 0x8a, 0x3d, 0x13, 0x65, 0x66, 0x45, 0xdd, 0xaf, 0x2e,
	0xbc, 0x2e, 0x33, 0x8a, 0xbe, 0x80, 0x8d, 0x22, 0xa7, 0xdc, 0x88, 0xa3, 0x9e, 0xa8, 0x3c, 0xab,
	0x58, 0x05, 0x0c, 0xff, 0xf6, 0x60, 0xdf, 0x90, 0xe6, 0x24, 0xcd, 0x49, 0xa8, 0xfe, 0x55, 0x3f,
	0xc7, 0xf7, 0xc0, 0xa7, 0x37, 0x82, 0xf2, 0x54, 0x6a, 0x67, 0x6e, 0x0a, 0x02, 0xd6, 0x75, 0x3e,
	0x47, 0x9f, 0xc1, 0x76, 0x46, 0xca, 0x84, 0xa6, 0x62, 0x36, 0x27, 0xc2, 0x9e, 0x6f, 0xdf, 0xf8,
	0x4e, 0x89, 0xa0, 0xe8, 0x01, 0xec, 0xda, 0x90, 0x84, 0x8a, 0x05, 0x9b, 0x9b, 0xb3, 0xb4, 0x63,
	0xbc, 0x2f, 0x95, 0x13, 0x1d, 0x41, 0x6f, 0xce, 0xcb, 0x19, 0x2f, 0x52, 0x75, 0xa2, 0x3a, 0xb8,
	0x3b, 0xe7, 0x25, 0x2e, 0xd2, 0xe1, 0x14, 0x76, 0xcc, 0x81, 0xd2, 0xf1, 0x8d, 0xea, 0xfb, 0x1d,
	0x6c, 0x19, 0x5d, 0x90, 0x66, 0x00, 0xcf, 0x61, 0xdb, 0xb1, 0x68, 0x2a, 0xea, 0x33, 0xd8, 0xd3,
	0x18, 0x6f, 0xd4, 0x4c, 0x7d, 0x41, 0x69, 0x23, 0x98, 0x1f, 0xe1, 0x70, 0xa5, 0x20, 0xba, 0x80,
	0x4d, 0xd1, 0x30, 0x7c, 0xac, 0xd1, 0x30, 0xcd, 0x88, 0xe0, 0x91, 0xd2, 0xd2, 0x94, 0x25, 0x49,
	0x94, 0xe7, 0x52, 0x12, 0x4d, 0x30, 0xff, 0x69, 0xc3, 0x60, 0x85, 0xe2, 0x29, 0x15, 0x24, 0x8a,
	0x73, 0xf4, 0x18, 0x7a, 0xa6, 0xeb, 0x66, 0x02, 0x1e, 0xd6, 0x14, 0x6a, 0xe2, 0xb1, 0x0d, 0x43,
	0x9f, 0x43, 0x7b, 0x49, 0xec, 0xb0, 0x43, 0xf5, 0x91, 0x45, 0x04, 0x96, 0xcb, 0xe8, 0x31, 0x0c,
	0x32, 0xd5, 0x17, 0x37, 0x61, 0x67, 0xdc, 0xca, 0xd1, 0xc3, 0x48, 0xaf, 0xb9, 0xb1, 0x2a, 0x55,
	0xf9, 0x08, 0xba, 0xda, 0x6b, 0x66, 0xda, 0xc1, 0xbb, 0x44, 0xe4, 0x14, 0x35, 0x41, 0xe8, 0x5b,
	0x00, 0x7d, 0x11, 0xce, 0xde, 0x52, 0x7d, 0x35, 0xf9, 0x93, 0xa0, 0xb6, 0xc5, 0x75, 0x15, 0x6f,
	0xdd, 0xb8, 0x06, 0xbf, 0x04, 0xb4, 0xaa, 0x7e, 0x05, 0xd0, 0x55, 0x00, 0xf7, 0xd6, 0x27, 0xef,
	0xfa, 0x89, 0xfb, 0x59, 0xbd, 0xc3, 0xbf, 0xc3, 0x11, 0xaf, 0xf4, 0x69, 0x16, 0xba, 0x46, 0x05,
	0x3d, 0x85, 0xf9, 0xa0, 0x86, 0xb9, 0xbe, 0xab, 0xf8, 0x90, 0xaf, 0xf5, 0x0f, 0xff, 0x6d, 0xc3,
	0x87, 0x2b, 0x64, 0x9a, 0x8f, 0xa2, 0x13, 0xd8, 0xcc, 0xcc, 0x15, 0x78, 0xc7, 0x5d, 0x65, 0x6f,
	0x48, 0xec, 0x02, 0xdd, 0xfc, 0x6a, 0xbf, 0x67, 0x7e, 0xa1, 0x67, 0xe0, 0x8b, 0xdb, 0xc1, 0x65,
	0x9a, 0x78, 0x5c, 0xbf, 0x98, 0x6e, 0x23, 0x70, 0x35, 0x1c, 0xbd, 0x80, 0x3d, 0x37, 0xb6, 0xb4,
	0x34, 0x4d, 0x4f, 0x3f, 0x59, 0xdf, 0x12, 0xa3, 0x5f, 0x6c, 0x27, 0x99, 0xd5, 0x33, 0x85, 0xfd,
	0xb0, 0xc8, 0x05, 0x4b, 0x66, 0x19, 0xe1, 0x24, 0xa1, 0x82, 0xf2, 0x3c, 0xe8, 0xaa, 0x4b, 0xe6,
	0xc9, 0x7a, 0xa4, 0x6a, 0x3d, 0x47, 0x53, 0xb5, 0xf7, 0xc2, 0x6d, 0x3d, 0x93, 0x4f, 0x1a, 0xdc,
	0x0f, 0x6b, 0xee, 0xe3, 0x29, 0x1c, 0xac, 0x0d, 0x95, 0x17, 0xe3, 0x35, 0xb5, 0xe7, 0x52, 0x7e,
	0xca, 0x37, 0xd5, 0x92, 0xc4, 0x05, 0x35, 0xb3, 0x5a, 0x1b, 0x4f, 0x5b, 0x4f, 0xbc, 0xe7, 0xcf,
	0x7e, 0x7b, 0x7a, 0x15, 0x89, 0x45, 0x71, 0x39, 0x0a, 0x59, 0x32, 0xbe, 0x90, 0xef, 0xb9, 0x90,
	0xc5, 0x3f, 0xbd, 0x3a, 0x1b, 0x4b, 0x8d, 0xa7, 0xf4, 0x11, 0xa7, 0x19, 0xcb, 0x23, 0xc1, 0x78,
	0x39, 0xce, 0xae, 0xaf, 0xc6, 0xea, 0xc5, 0x37, 0x36, 0x49, 0x5c, 0x76, 0x95, 0x79, 0xf2, 0x7f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xaf, 0x56, 0x0a, 0x9b, 0x18, 0x0a, 0x00, 0x00,
}
